### ISSUE TITLE
Return a custom static file 

### ISSUE THREAD

**Issue by toringer** [justcoding121/Titanium-Web-Proxy#103]
Is there a way to return a custom static file?

I want to return a static file for all requests to the proxy server. Before returning the file, the request url will be repleced into the file. I also need control of the headers to turn off cache and control the file name.

**Comment by justcoding121** [comment]
You can [use e.Ok(bodyBytes) function. ](https://github.com/justcoding121/Titanium-Web-Proxy/blob/master/Titanium.Web.Proxy/EventArguments/SessionEventArgs.cs#L364) in your request.

Also a the correct headers relavant to the file type your are returning
