### ISSUE TITLE
Cannot access a disposed object

### ISSUE THREAD

**Issue by pfiggins** [justcoding121/Titanium-Web-Proxy#107]
In initial testing, I noticed a lot of errors being thrown (and handled) within Titanium. One that seems avoidable is "Cannot access a disposed object" on the following line in ProxyServer.cs

```
                            tcpClient.LingerState = new LingerOption(true, 0);
                            tcpClient.Client.Shutdown(SocketShutdown.Both);
                            tcpClient.Client.Close();
                            tcpClient.Client.Dispose();

                            tcpClient.Close();
```

Have you considered inheriting TcpClient into a custom object that tracks if it's disposing and allows for checking prior to calling these lines? I started down the path of doing so when I figured it might be smart to ask you first if you've considered this and/or if there's an issue with doing so...

**Comment by justcoding121** [comment]
That's a good idea!

**Comment by ilushka85** [comment]
Is there any update on this?

**Comment by honfika** [comment]
In both .NET Framework and .NET Core setting a `LingerState` on a `TcpClient` object calls the `SetSocketOption` method on the `TcpClient.Client` `Socket` object.

This method checks the `CleanedUp` internal property which exists in both .NET Framework and .NET Core.

.NET Core source (.NET Fw is very similar):
https://github.com/dotnet/corefx/blob/c51694a1065e40f6c92d1fb8d82f3d879cb3d4ad/src/System.Net.Sockets/src/System/Net/Sockets/Socket.cs#L1777

So I have added a check which gets the value of the `CleanedUp` property and calls the `LingerState` setter only when the property does not exist or the value is false. So It will work even if the internal property of the Socket object will be removed from the framework. A cached property getter was added for the best performance.

@justcoding121 Please check it: https://github.com/justcoding121/Titanium-Web-Proxy/commit/40cd60cce64f1e2e307517c48ffde4a20d05dec7

**Comment by honfika** [comment]
@pfiggins, @ilushka85 Please try the latest version (beta or stable). Is it ok? May I close this issue?

**Comment by honfika** [comment]
I close this issue, please reopen if needed.
