### ISSUE TITLE
Certificate store Local Machine causes deadlock

### ISSUE THREAD

**Issue by pfiggins** [justcoding121/Titanium-Web-Proxy#111]
Setting both stores to Local Machine causes a deadlock on the call to makecert. I can step through and see it calling tcs.SetResult, but the await never continues in ProxyServer.cs. Switching MyStore back to Current User fixed the issue, but for the life of me, I don't see why it's deadlocking there with MyStore set to Local Machine. Any idea why?

**Comment by justcoding121** [comment]
Have to investigate. I am in the middle of a move, sorry for not being involved as I used to.

**Comment by ilushka85** [comment]
This has been resolved as soon as pull request #123 is merged in as it replaces makecert with certenroll
