### ISSUE TITLE
Connection Count per IP Address

### ISSUE THREAD

**Issue by chancity** [justcoding121/Titanium-Web-Proxy#113]
Is there an easy way to see how many connections a single IP address has to the proxy server?

**Comment by justcoding121** [comment]
As of now, I don't think there is anyway to find it.

**Comment by chancity** [comment]
@justcoding121 where would the best place be to implement this?

**Comment by justcoding121** [comment]
I think [here](https://github.com/justcoding121/Titanium-Web-Proxy/blob/master/Titanium.Web.Proxy/ProxyServer.cs#L387) would be the right place. So you add new IP to the dictionary incrementing its value. And when the finally block is hit decrement the IP count. Get the client IP from TcpClient object.

**Comment by chancity** [comment]
@justcoding121 I tried adding it there and it seemed really inaccurate.  I'll do some further playing though

**Comment by honfika** [comment]
@chancity May I close this issue?

**Comment by honfika** [comment]
I close this issue now, feel free to reopen it if needed.
