### ISSUE TITLE
Certificate name and issuer cannot be changed

### ISSUE THREAD

**Issue by bechny** [justcoding121/Titanium-Web-Proxy#114]
This is related to #20. It seems it is not possible to change those properties anymore since CertificateManager instance is created before those properties can be assigned: https://github.com/justcoding121/Titanium-Web-Proxy/blob/master/Titanium.Web.Proxy/ProxyServer.cs#L135

**Comment by justcoding121** [comment]
Fixed in release branch. Should be in latest beta nuget. Thanks.
