### ISSUE TITLE
Is SNI Required?

### ISSUE THREAD

**Issue by ilushka85** [justcoding121/Titanium-Web-Proxy#120]
In order to do https proxying without having to install our root cert, do we need sni support in sslstream?   How is Squid doing this?

**Comment by justcoding121** [comment]
Not sure how squid can do that. Only way I can think of is that Squid owns a root certificate which it purchased from authority. So when it signs it with that certificate clients would trust it.

SNI have nothing to do with proxying without having to install root. SNI have something to do with reverse proxying.

**Comment by ilushka85** [comment]
I actually see what they are doing... they are not acting at mitm proxy but are just relaying the connection.  If we do that, we can avoid security issues.  Should we add a mode for this?

**Comment by justcoding121** [comment]
@ilushka85 That's a good idea if we can give an option for that.

**Comment by ilushka85** [comment]
Yes I will add code in for this.

**Comment by keyoti** [comment]
@ilushka85 was the relaying code added?  Which branch is it in?  Thanks!
