### ISSUE TITLE
Chain to upstream gateway behaviour

### ISSUE THREAD

**Issue by aricih** [justcoding121/Titanium-Web-Proxy#128]
There is a ChainToUpstreamGateway falg in FiddlerCore which handles automatic proxy discovery. How does/should ProxyServer in Titanium handles PAC scripts/automatic proxy configuration?

**Comment by justcoding121** [comment]
@ArachisH  We currently don't have any such support. 

If we were to add this support, I would think we should have a flag to let user decide on that. By default it should be true.

**Comment by aricih** [comment]
I'll try to implement this one. Again it's @aricih not @ArachisH :)

**Comment by justcoding121** [comment]
@aricih Sorry Man. Autocomplete picks other name some times.
