### ISSUE TITLE
Creating and storing certificates into Personal store

### ISSUE THREAD

**Issue by BaderAlmudarra** [justcoding121/Titanium-Web-Proxy#13]
Hi,

I am not sure if this is an issue or not. I noticed there are some certificates are generated with this parameter "-sky exchange" and then are stored in personal store.

I don't see this behavior exists in some other proxy servers like Fiddler or ieinspector.

Is there anyway we can stop creating certificates after importing the main certificate into "trusted root" store.

Thanks

**Comment by titanium007** [comment]
Well the reason for that is because we cache certificates to personal certificate store in addition to application level caching. I will consider your request to create an option to disable personal certificate store cache in future. Or you can do a PR if you can contribute.

**Comment by justcoding121** [comment]
Fixed in latest release
