### ISSUE TITLE
Not possible to run ProxyServer as embedded server in NUnit

### ISSUE THREAD

**Issue by janvolck** [justcoding121/Titanium-Web-Proxy#135]
NUnit works with different AppDomains when launching tests, this to isolate the code being run.
Because of this the Assembly.GetEntryAssembly() returns null and causes a NPE in CertificateManager when calling `System.IO.Path.GetDirectoryName(System.Reflection.Assembly.GetEntryAssembly().Location`

Next to this, it is not very interesting to have a dialog popup in the automated unit tests when the generated certificates are added to the certificate store. To avoid this, the root certificate should be added to the Root of the LocalMachine and not to the Root of te CurrentUser.

Attach you can find a patch that solved the issues I encountered.
[patch.txt](https://github.com/justcoding121/Titanium-Web-Proxy/files/521853/patch.txt)

**Comment by justcoding121** [comment]
You could avoid certificate warnings if you provide the name of a trusted root pfx you already have in app directory.

In future we may give an option to let the user choose the store to install roots when not provided one.

The appdomain issue looks interesting.
