### ISSUE TITLE
Documentation on where / how to generate or install certs?

### ISSUE THREAD

**Issue by Zarigan** [justcoding121/Titanium-Web-Proxy#147]
Trying to set up a fairly simple re-writing proxy to insert meta into web pages (for use by a web crawler).  I have http working just fine but https is causing me issues.  I have it working locally (request and proxy on the same dev machine) so I'm guessing it's just cert problems.

Any documentation / hints on generating certs for the machine running the proxy and the machine running the crawler?

I tried taking the root cert generated on my dev machine and using it on the proxy server but that didn't seem to work ("The underlying connection was closed: An unexpected error occurred on a send.").  Then I tried letting the proxy server generate it's own cert ("The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.").

Then I tried setting my system proxy to the proxy server and browsing to the end site.  Viewing the cert through Chrome I see "The issuer of this certificate could not be found."  Picking a different site for comparison, I instead see "This certificate has an invalid digital signature."

Given the requests are coming from my dev machine, can the root cert generated locally clash in any way with the root cert on the proxy server?

Suggestions on how to debug further?  Thanks.

**Comment by justcoding121** [comment]
FYI each time you clean and build the old root certificate .pfx file is lost. So next time proxy will try to install it again.

Proxy should install the root in current user root certificate store and in current user store. Once its in the store, windows applications including chrome browser can verify the validity of certificates signed by our root certificate. If the browser couldn't verify, it will show the error. So likely you are signing with a certificate not installed in the store.

**Comment by kevinrmcd** [comment]
Is there a publicly exposed mechanism to generate the certificate on the fly?  My organization has adopted this proxy as the base class for a mocking/proxy API (or we will when the generic response code I added moves from the develop branch to the stable branch).  If we try to use this in an unattended lab environment, code progression is blocked waiting for approval in the UI to install the cert.  If we could install the cert beforehand, that would solve the problem.

**Comment by justcoding121** [comment]
To avoid warning prompt I think we need to add the Root to Local Machine Store, not to current user Store.
http://stackoverflow.com/questions/4196997/certificate-install-security-warning-workaround

By default the proxy installs it to Current User Store.
https://github.com/justcoding121/Titanium-Web-Proxy/blob/develop/Titanium.Web.Proxy/Network/CertificateManager.cs#L190

We probably can expose this option as public in Proxy Class.

**Comment by justcoding121** [comment]
The proxy do generate certificate on fly if not provided one.
https://github.com/justcoding121/Titanium-Web-Proxy/blob/develop/Titanium.Web.Proxy/Network/CertificateManager.cs#L103
