### ISSUE TITLE
Feature Request: HTTP-only mode (i.e. Don't Generate rootCert.pfx)

### ISSUE THREAD

**Issue by RadarNyan** [justcoding121/Titanium-Web-Proxy#149]
I'm using Titanium-Web-Proxy together with CefSharp to create a toy browser, I don't wanna mess around with https so I only set http proxy of Cef to Titanium-Web-Proxy (and https traffic goes directly). Everything works as I expected except for ```rootCert.pfx``` being automatically generated in program folder. This is not a problem or a bug feature-wise, but it's totally unecessary considering that certificate is never used.

Could you add an option to not generate that file automatically?

**Comment by TeeTrizZz** [comment]
I would appreciate such a possibility.

Titanium works pretty much flawlessly with Mono on Linux. There are, of course, a few functions which don't work (e.g. ```SetAsSystemHttpProxy```) but Titanium does what it should. The only problem is the certificate stuff as COM (and therefore ```GetTypeFromProgID``` in the ```CertificateMaker``` constructor) isn't supported by Mono/Linux. I don't know if there are other ways to create a certificate, but making this part optional would also help to address issue #50.

**Comment by justcoding121** [comment]
Added RootCertificate Property and certificate is not generated in HTTP only mode.
