### ISSUE TITLE
Linux: Inconsistent line endings lead to a WebException (protocol violation)

### ISSUE THREAD

**Issue by TeeTrizZz** [justcoding121/Titanium-Web-Proxy#151]
Hi @justcoding121,

**Problem:**

According to the RFC, HTTP/1.1 should always use ```\r\n``` as line ending. Unfortunately, these are not the default line break characters on Linux. As Titanium uses ```WriteLineAsync``` and therefore the OS-specific line breaks, the HTTP's header (and body?) use ```\n``` on Linux instead of the desired ```\r\n```. This, e.g, leads to a protocol violation exception when connecting with C#'s ```WebRequest``` class ("unsafe header").

**Solution:**

```StreamWriter```'s ```NewLine``` property should be manually set to ```\r\n``` to always ensure correct line endings:

https://msdn.microsoft.com/en-us/library/system.io.streamwriter_properties(v=vs.110).aspx

Thanks!

**Comment by justcoding121** [comment]
Thanks for reporting, I currently don't work on a Linux environment. Will try to fix this one day I create a VM, or may be other contributors can PR.

**Comment by TeeTrizZz** [comment]
I created a PR. This fixes the problem while it shouldn't change anything on Windows.

**Comment by zaforic** [comment]
I also had to change all the Environment.NewLine to "\r\n" for it to work with mono.
