### ISSUE TITLE
HTTP Headers without space

### ISSUE THREAD

**Issue by JavierJGit** [justcoding121/Titanium-Web-Proxy#154]
Hi,

Problem:
Sending a file to a router is rejected because there is no space in the HTTP headers between the name and the value. As:
Connection:keep-alive

Solution
Modifying the file Titanium.Web.Proxy.Http.HttpWebClient in lines 93 and 105 is solved. You have to change ':' by ":" to insert the space.

**Comment by JavierJGit** [comment]
Hi,

I'm sorry, they are an error in my comment, the ": " must include an space after colon. The commit should be modified, sorry again.

**Comment by justcoding121** [comment]
Not sure if Rfc says we need a space after colon. I would think that a good router would trim the space regardless.

Updated it.
