### ISSUE TITLE
System proxy no longer works

### ISSUE THREAD

**Issue by OlsonDev** [justcoding121/Titanium-Web-Proxy#156]
The system proxy stopped working on me; I've been using it for months with success... I don't know why it stopped working because I haven't touched the proxy-related code in my project. I do know it has something to do with `InternetOptionSettingsChanged`. The reason why I know that is I started the proxy, add the explicit endpoint, set it as a system proxy (no effect), then added this:

```c#
var key = Registry.CurrentUser.OpenSubKey("Software\\Microsoft\\Windows\\CurrentVersion\\Internet Settings", true);
var aEnable = key.GetValue("ProxyEnable");
var aServer = key.GetValue("ProxyServer");
var aProxyOverride = key.GetValue("ProxyOverride");

key.SetValue("ProxyEnable", 1);
key.SetValue("ProxyServer", "http=127.0.0.1:8000");
key.SetValue("ProxyOverride", "<-loopback>");

var bEnable = key.GetValue("ProxyEnable");
var bServer = key.GetValue("ProxyServer");
var bProxyOverride = key.GetValue("ProxyOverride");

NativeMethods.InternetSetOption(IntPtr.Zero, InternetOptionSettingsChanged, IntPtr.Zero, 0);

var cEnable = key.GetValue("ProxyEnable");
var cServer = key.GetValue("ProxyServer");
var cProxyOverride = key.GetValue("ProxyOverride");

NativeMethods.InternetSetOption(IntPtr.Zero, InternetOptionRefresh, IntPtr.Zero, 0);

var dEnable = key.GetValue("ProxyEnable");
var dServer = key.GetValue("ProxyServer");
var dProxyOverride = key.GetValue("ProxyOverride");
```

Here's the result of that:

![image](https://cloud.githubusercontent.com/assets/308072/20694203/3d12c7d8-b5a9-11e6-9ad2-8a47cc7d1a8e.png)

I tried with and without the `ProxyOverride` since Titanium doesn't set that property (I noticed Fiddler does).

I run the Windows 10 Insider Preview so that might have something to do with it...?

![image](https://cloud.githubusercontent.com/assets/308072/20694260/8f096c2c-b5a9-11e6-8427-94be70f7fbf0.png)

Any ideas? Things I can try?

**Comment by OlsonDev** [comment]
Not sure if it would've helped but I also tried adding `Marshal.GetLastWin32Error()` after both the native calls. Both of them returned `0` so...

**Comment by OlsonDev** [comment]
Opening up Internet Options and configuring the proxy through the UI makes my app start working:

![image](https://cloud.githubusercontent.com/assets/308072/20695703/9934214c-b5b3-11e6-99cb-ce8c3a711651.png)

![image](https://cloud.githubusercontent.com/assets/308072/20695699/93c78f0a-b5b3-11e6-8db5-6144d982f570.png)

![image](https://cloud.githubusercontent.com/assets/308072/20695693/8b1575d4-b5b3-11e6-928f-bda0d3739831.png)

Still not sure why Titanium fails to register it as a system proxy.

**Comment by samuel-allan** [comment]
The only real way to fix these kinds of problems for good is to use a robust technique like using a TUN/TAP device, which would effectively redirect all traffic through the device.

**Comment by nordinrahman** [comment]
@OlsonDev, followup questions, for anyone to troubleshoot this.

  1. I wonder which Nuget package version you use?
  2. Sorry if this is too dumb, just want to make sure here, is the app run as Administrator?
  3. Any other error message (like, in Windows Event Viewer)?

TQ.

**Comment by dmakaroff** [comment]
I am experiencing the same issue when I test using a virtual machine running Windows 7. Surprisingly it works on my Windows 10 development host. I am using NuGet package version 3.0.8.

**Comment by justcoding121** [comment]
Probably relates to #256

**Comment by nredondo26** [comment]
Hello I have the same problem with windows 8, 8.1 and 10 works perfectly, but with windows 7, every time I start my pc it works, but if I close it and open it again the process loads but does not activate the proxy.

Hola tengo el mismo problema con windows 8, 8.1 y 10 funciona perfectamente, pero con windows 7, cada vez que inicio mi pc funciona, pero si lo cierro y lo abro nuevamente el proceso se carga pero no activa el proxy.

**Comment by GF-Huang** [comment]
I had a similar problem with Windows 7.
