### ISSUE TITLE
Capture specific process(es) by group(s) or name

### ISSUE THREAD

**Issue by featureRequestOnly** [justcoding121/Titanium-Web-Proxy#169]
Hi, it would be so cool if i could strict Titanium to capture only specific applications by group (web browsers) or by process names.

**Comment by justcoding121** [comment]
We can't specifically capture from specific process, we listen on an endpoint and whatever traffic comes in we would read it. And note that you can use the [process id ](https://github.com/justcoding121/Titanium-Web-Proxy/blob/develop/Examples/Titanium.Web.Proxy.Examples.Basic/ProxyTestController.cs#L137)and skip reading the data in your code if you want, and proxy would relay the data. 


If you are thinking of selectively proxying applications you would probably should look for writing a low lever kernal network driver to redirect traffic selectively to proxy or via firewall.
