### ISSUE TITLE
How can I print the response body?

### ISSUE THREAD

**Issue by Rottweiler** [justcoding121/Titanium-Web-Proxy#176]
How can I print the response body in the Console?

**Comment by ricardoborges** [comment]
proxyServer.BeforeResponse += OnResponse;

**Comment by ricardoborges** [comment]
//Modify response
        public static async Task OnResponse(object sender, SessionEventArgs e)
        {
            //read response headers
            var responseHeaders = e.WebSession.Response.ResponseHeaders;

            //if (!e.ProxySession.Request.Host.Equals("medeczane.sgk.gov.tr")) return;
            if (e.WebSession.Request.Method == "GET" || e.WebSession.Request.Method == "POST")
            {
                if (e.WebSession.Response.ResponseStatusCode == "200")
                {
                    if (e.WebSession.Response.ContentType != null && e.WebSession.Response.ContentType.Trim().ToLower().Contains("text/html"))
                    {
                        byte[] bodyBytes = await e.GetResponseBody();
                        await e.SetResponseBody(bodyBytes);

                        string body = await e.GetResponseBodyAsString();
                        await e.SetResponseBodyString(body);
                    }
                }
            }
        }

**Comment by ricardoborges** [comment]
string body = await e.GetResponseBodyAsString();
