### ISSUE TITLE
Support for timers?

### ISSUE THREAD

**Issue by philippe-tr** [justcoding121/Titanium-Web-Proxy#178]
Hi. I am looking into profiling the performance of some Ajax http requests. Does this library support timers in a similar fashion to http://fiddler.wikidot.com/timers?

**Comment by justcoding121** [comment]
Fiddler is a web debugging proxy, and we are more focused on performance and being light weight.

So we don't support it. But you can accomplish some of the timer functionality but adding timers inside the request/response handlers
