### ISSUE TITLE
Possible to bind to specific IP for outgoing requests?

### ISSUE THREAD

**Issue by georgiosd** [justcoding121/Titanium-Web-Proxy#179]
Hi!

Is it possible to bind outgoing requests to a specific IP given to the machine's NIC? Usually done through `ServicePoint.BindIPEndpointDelegate`

Thanks

**Comment by justcoding121** [comment]
Yes.

https://github.com/justcoding121/Titanium-Web-Proxy/blob/develop/Titanium.Web.Proxy/ProxyServer.cs#L124

Adjust ProxyServer.UpStreamEndPoint

**Comment by georgiosd** [comment]
Rockstar! Thanks!
