### ISSUE TITLE
Upgrade header not in the request stream

### ISSUE THREAD

**Issue by ClownChu** [justcoding121/Titanium-Web-Proxy#182]
Hey,

I have a web application which uses jQuery SignalR to establish a WebSocket connection, when Titanium is on, the signalr/connect request always get aborted/fails because Titanium cannot identify that this is a socket upgrade.

When I add the upgrade header manually it seems to work fine, as it passes the "args.WebSession.Request.UpgradeToWebSocket" condition, which suggests me that Titanium does support web socket upgrade.

Now my question is, does anyone ever had this issue? If yes, why the client reader does not contain the upgrade headers?

Thank you!

**Comment by honfika** [comment]
I have a same problem with splix.io (a simple snake game) It seems that the Upgrade header for using websocket is only one way. Websocket can use a HTTP CONNECT verb (as HTTPS) from the first request, so no upgrade is needed.
I investigated a little bit, but didn't found any good way to detect which CONNECT is a HTTPS,, which is a websocket.
So @justcoding121: you can reproduce the problem with splix.io

**Comment by justcoding121** [comment]
Updated the code so that we will allow HTTPS only on well know ports. This can be modified 

https://github.com/justcoding121/Titanium-Web-Proxy/blob/develop/Titanium.Web.Proxy/Models/EndPoint.cs#L127

So this should allow CONNECT to Web-socket ports without upgrade.
