### ISSUE TITLE
ExcludedHttpsHostNameRegex is broken

### ISSUE THREAD

**Issue by dmakaroff** [justcoding121/Titanium-Web-Proxy#183]
Adding e.g. google.com to the list stops all the traffic going to said domain name.

**Comment by dmakaroff** [comment]
My bad. Seems to work.

**Comment by dmakaroff** [comment]
Nope, it's broken. Google is redirecting the browser to google.fi. Adding google.fi to ExcludedHttpsHostNameRegex breaks Google.

**Comment by justcoding121** [comment]
Should be fixed in latest develop. See #204
