### ISSUE TITLE
Initiate multiple requests (programatically) when handling the original request?

### ISSUE THREAD

**Issue by ZirakC** [justcoding121/Titanium-Web-Proxy#189]
Is there a way to for example, initiate multiple web requests to the server when intercepting one?

Basically Something like this:

Client POST -> Proxy Server (4 POST requests, 1 original and 3 custom post requests from proxy server) -> Web Server

Since it isn't the client doing the POST, it wouldn't expect the response for the other three, in which case I can suppress within the proxy.

Is this possible?

Thanks

**Comment by justcoding121** [comment]
Can't you achieve the same with a [WebClient](https://msdn.microsoft.com/en-us/library/system.net.webclient(v=vs.110).aspx) from the RequestHandler? Post the other three requests from web client with request handler to the server. (set webclient to use the proxy).
