### ISSUE TITLE
Titanium Proxy Wont Connect?

### ISSUE THREAD

**Issue by Cablekid** [justcoding121/Titanium-Web-Proxy#19]
Hello! I have launched and built Titanium Proxy. Console Says Listening for connections on localhost:49487 

I then try to go on another pc and connect via proxy manager but it will not connect?

**Comment by Cablekid** [comment]
I guess what i need is the program to open a Sock5 or Sock4 Proxy Server So Others Can Connect To it?

**Comment by titanium007** [comment]
Did you try connecting from other computer using IP address of the computer where proxy is running? 
Make sure firewall is allowing proxy to listen.

**Comment by titanium007** [comment]
I think [StackOverflow](http://stackoverflow.com/questions/tagged/titanium-web-proxy) would be a better place to address this. Make sure you ask with a Titanium-Web-Proxy as hashtag.
