### ISSUE TITLE
Incoming Http request in Transparent proxy fails to parse remote uri

### ISSUE THREAD

**Issue by adamlemmon** [justcoding121/Titanium-Web-Proxy#190]
I've wired up a TransparentProxyEndPoint to listen on for traffic from IPAddress.Any on port 8001 with EnableSsl = false. When a request comes in, it makes it to where it tries to parse out the httpRemoteUri in RequestHandler.cs line 447 on stable. This line tries to pull part of the uri out of httpCmdSplit[1] but this only contains the path portion of the uri and not the hostname and port information (e.g. just "/justcoding121/Titanium-Web-Proxy/issues/new" for a request to "http://github.com/justcoding121/Titanium-Web-Proxy/issues/new"). It looks like the args.WebSession.Request.Host has the hostname and port I'm looking for, but it ignores those because EnableSsl is false (so it doesn't get set earlier in the code).

Because this fails to build the Uri, I never get the ProxyServer.BeforeRequest event fired out to my client code.

Can someone help me get this to support http request proxying?

Below is my slightly adapted version of the demo code:

`class Program
    {
        static void Main(string[] args)
        {
            var proxyServer = new ProxyServer();

            //locally trust root certificate used by this proxy 
            proxyServer.TrustRootCertificate = true;

            proxyServer.BeforeRequest += OnRequest;
            proxyServer.BeforeResponse += OnResponse;
            proxyServer.ServerCertificateValidationCallback += OnCertificateValidation;
            proxyServer.ClientCertificateSelectionCallback += OnCertificateSelection;
            

            //Transparent endpoint is usefull for reverse proxying (client is not aware of the existance of proxy)
            //A transparent endpoint usually requires a network router port forwarding HTTP(S) packets to this endpoint
            //Currently do not support Server Name Indication (It is not currently supported by SslStream class)
            //That means that the transparent endpoint will always provide the same Generic Certificate to all HTTPS requests
            //In this example only google.com will work for HTTPS requests
            //Other sites will receive a certificate mismatch warning on browser
            var transparentEndPoint = new TransparentProxyEndPoint(IPAddress.Any, 8001, false)
            {
                GenericCertificateName = "localhost"
            };
            proxyServer.AddEndPoint(transparentEndPoint);
            proxyServer.Start();

            foreach (var endPoint in proxyServer.ProxyEndPoints)
                Console.WriteLine("Listening on '{0}' endpoint at Ip {1} and port: {2} ",
                    endPoint.GetType().Name, endPoint.IpAddress, endPoint.Port);

            //wait here (You can use something else as a wait function, I am using this as a demo)
            Console.Read();

            //Unsubscribe & Quit
            proxyServer.BeforeRequest -= OnRequest;
            proxyServer.BeforeResponse -= OnResponse;
            proxyServer.ServerCertificateValidationCallback -= OnCertificateValidation;
            proxyServer.ClientCertificateSelectionCallback -= OnCertificateSelection;

            proxyServer.Stop();
        }

        public static async Task OnRequest(object sender, SessionEventArgs e)
        {
            Console.WriteLine(e.WebSession.Request.Url);

            ////read request headers
            var requestHeaders = e.WebSession.Request.RequestHeaders;

            var method = e.WebSession.Request.Method.ToUpper();
            if ((method == "POST" || method == "PUT" || method == "PATCH"))
            {
                //Get/Set request body bytes
                byte[] bodyBytes = await e.GetRequestBody();
                await e.SetRequestBody(bodyBytes);

                //Get/Set request body as string
                string bodyString = await e.GetRequestBodyAsString();
                Console.Write(bodyString);
                await e.SetRequestBodyString(bodyString);

            }

            //To cancel a request with a custom HTML content
            //Filter URL
            if (e.WebSession.Request.RequestUri.AbsoluteUri.Contains("google.com"))
            {
                await e.Ok("<!DOCTYPE html>" +
                           "<html><body><h1>" +
                           "Website Blocked" +
                           "</h1>" +
                           "<p>Blocked by titanium web proxy.</p>" +
                           "</body>" +
                           "</html>");
            }
            //Redirect example
            if (e.WebSession.Request.RequestUri.AbsoluteUri.Contains("wikipedia.org"))
            {
                await e.Redirect("https://www.paypal.com");
            }

            //Here I'm trying to forward the request on to the actual destination on 9001.
            Console.WriteLine("Sending to: " + e.WebSession.Request.RequestUri.AbsoluteUri.Replace("8001", "9001"));
            await e.Redirect(e.WebSession.Request.RequestUri.AbsoluteUri.Replace("8001", "9001"));
        }

        //Modify response
        public static async Task OnResponse(object sender, SessionEventArgs e)
        {
            //read response headers
            var responseHeaders = e.WebSession.Response.ResponseHeaders;

            //if (!e.ProxySession.Request.Host.Equals("medeczane.sgk.gov.tr")) return;
            if (e.WebSession.Request.Method == "GET" || e.WebSession.Request.Method == "POST")
            {
                if (e.WebSession.Response.ResponseStatusCode == "200")
                {
                    if (e.WebSession.Response.ContentType != null && e.WebSession.Response.ContentType.Trim().ToLower().Contains("text/html"))
                    {
                        byte[] bodyBytes = await e.GetResponseBody();
                        await e.SetResponseBody(bodyBytes);

                        string body = await e.GetResponseBodyAsString();
                        await e.SetResponseBodyString(body);
                    }
                }
            }
        }

        /// Allows overriding default certificate validation logic
        public static Task OnCertificateValidation(object sender, CertificateValidationEventArgs e)
        {
            //set IsValid to true/false based on Certificate Errors
            if (e.SslPolicyErrors == System.Net.Security.SslPolicyErrors.None)
                e.IsValid = true;

            return Task.FromResult(0);
        }

        /// Allows overriding default client certificate selection logic during mutual authentication
        public static Task OnCertificateSelection(object sender, CertificateSelectionEventArgs e)
        {
            //set e.clientCertificate to override
            return Task.FromResult(0);
        }
    }`

**Comment by justcoding121** [comment]
I apologize, we haven't fully tested end to end for reverse proxy.
I have added the note to readme. Having said that some users have reported (for example #150  ) in other issues that it as working properly for HTTP connections. Once we test this fully we will update.

**Comment by honfika** [comment]
I close this issue due to inactivity. Feel free to reopen it when problem still exists.
