### ISSUE TITLE
IncludedHttpsHostNameRegex 

### ISSUE THREAD

**Issue by honfika** [justcoding121/Titanium-Web-Proxy#205]
Please add IncludedHttpsHostNameRegex similar to ExcludedHttpsHostNameRegex.
I want to decrypt only certain websites.

excluded = excluded || (endPoint.IncludedHttpsHostNameRegex != null 
                    && !endPoint.IncludedHttpsHostNameRegex.Any(x => Regex.IsMatch(httpRemoteUri.Host, x)));

I can create a pull request if it helps.

**Comment by justcoding121** [comment]
You can create a PR.

At the same time included would take priority over excluded. So if user tries to set excluded after setting included, your code should throw an ArgumentException("Cannot set excluded when included is set")
