### ISSUE TITLE
How to pass login credentials?

### ISSUE THREAD

**Issue by rnconync** [justcoding121/Titanium-Web-Proxy#22]
I was wondering if there is a way I can pass login credentials using your web proxy. I want to mostly use the proxy as a back end service that will be used for logging into multiple websites to access information without the users having or knowing the login credentials to those sites. So, they click a link, it sends it to the proxy, it logs them in and then they can view the contents of the logged in account. 
 I have been messing with the code foe a bit and can get it to semi work, I can go to the page but it does not auto login, I have to click the submit button to be able to login, but once that is done all works fine. I am trying to figure out a way to bypass having to  click the submit button and have them autologin with the credentials via the proxy.
Thanks for your time!

**Comment by titanium007** [comment]
IMO, the best way probably to do what your saying is to intercept redirect to login page response from response handler of proxy and then initiate a request to the server from there with the credentials. Once you receive the authentication cookie, you may reuse that for subsequent requests. Keep a dictionary of website host name and authentication data.

**Comment by rnconync** [comment]
I am not very experienced with building a proxy. Could I use your proxy as
a base for this or start fresh? I'm not really sure where to go. Right now
I am just using your proxy and when you split out with httpscmdsplit I am
modifying that and assigning the post commands to the Url on httpcmdsplit
[1] and then letting your proxy hand it off. But I obviously don't know
what I'm doing..haha.
Can you offer any further guidance or direction? I have been researching
for a week or two and am not getting the results I want. I either don't
know what I'm trying to search for or there are no real good examples of
what I am trying to accomplish. I don't know if my solution requires
something even simpler than your proxy or not. I have been using fiddler to
pull out the required post information and all, so I am getting somewhere
with that part.
Anyway, thanks again and I really appreciate your time and response and any
help you can give.

**Comment by titanium007** [comment]
I think StackOverflow would be a better place to address this. Make sure you ask with a Titanium-Web-Proxy as hashtag.
