### ISSUE TITLE
Content decoding failed error & hang

### ISSUE THREAD

**Issue by justcoding121** [justcoding121/Titanium-Web-Proxy#227]
With the change with CustomBufferedStream for Beta release I see a big improvement in performance, but I believe there are some issues with it.  One is as below, and the the whole page have messed up style due to failure to load files. 

![image](https://cloud.githubusercontent.com/assets/2637679/26075910/fd11b67a-3984-11e7-87d1-11ab963ef332.png)

@honfika Your input would be helpful. I've also tried to cleanup dispose() calls and added a property to keep track of total connections from clients.

**Comment by honfika** [comment]
Is this HTTP or HTTPS? Which url (if public)?

**Comment by justcoding121** [comment]
This was HTTPS, and an internal site. This is not occurring on public sites, but I can see some issues with public sites as well where it shows the html content of the page and the once refreshed goes away.

**Comment by honfika** [comment]
Could you please try it after PR #228?

**Comment by justcoding121** [comment]
Thanks! Looks like your latest PR fix removing ThreadStatic worked. I tested it via VPN since I am away from the network that hosts the site, will update if it doesn't work when on network.
