### ISSUE TITLE
HTTP Errors

### ISSUE THREAD

**Issue by chancity** [justcoding121/Titanium-Web-Proxy#232]
I have been using a version of Titanium that was about 8 months old until today.  I have an application that tests the proxy ever 5 seconds and it has never received the errors shown in the image below until switching to the current release.

![image](https://cloud.githubusercontent.com/assets/8220501/26091530/af115f02-39c0-11e7-8fdb-923225418220.png)

Edit - This error was actually occurring on the develop branch.  Doesn't appear to be happening on the stable branch.

**Comment by honfika** [comment]
Which revision did you try?
If it was a revision before 5e9e1297ba4dcb09b9866c324c34ddbde8f0a3a8 then please try the latest code.

**Comment by chancity** [comment]
@honfika it was this revision https://github.com/justcoding121/Titanium-Web-Proxy/commit/dff9ef7f3c46da80aa06d8e58723f4beeba7cbd7

I switched to the stable release and the error went away.

**Comment by honfika** [comment]
May I ask you a favor?
Could you please try develop branch e4a80e7ee37f2162b2b7f28f74785ed6b2962387 revision?
And if it is working then revision 5e9e1297ba4dcb09b9866c324c34ddbde8f0a3a8

**Comment by justcoding121** [comment]
@honfika The stable version has the fix for CustomBufferredStream. (removal of ThreadStatic).

I think what he talks about is the change after that, the ConcurrentQueue Change.

**Comment by honfika** [comment]
@justcoding121 Are you able to reproduce the problem with the ConcurrentQueue solution?
The performance benefit of this Queue is not so big, so we can simply remove it if it makes trouble.
But I dint understand why is it wrong.

The ThreadStatic was wrong because with async/await multiple parallel code runs on the same thread, but in this case unique buffer is used for each instance. It is returned to the queue only when the stream is disposed.

**Comment by justcoding121** [comment]
@chancity Please try this on latest develop if you can.

**Comment by chancity** [comment]
@justcoding121 join my discord https://discord.gg/hTn3G8a

**Comment by honfika** [comment]
Is this issue fixed?

**Comment by honfika** [comment]
I close this issue due to inactivity. Feel free to reopen it when problem still exists.
