### ISSUE TITLE
Way to prevent Firefox from throwing 'This Connection is Untrusted' page.

### ISSUE THREAD

**Issue by Stackoverload** [justcoding121/Titanium-Web-Proxy#24]
Hello, I was wondering if there was a way to prevent firefox from throwing the 'This Connection is Untrusted' page. I noticed it works perfectly fine within Chrome. But the moment you open Firefox and try to browse an https website, it throws that page saying 'This Connection is Untrusted'. Is there any way to prevent Firefox from doing this?

**Comment by Stackoverload** [comment]
Was trying to assign Question label, couldn't find a way.

**Comment by titanium007** [comment]
This is because Firefox don't respect windows certificate store. It have its own certificate management system. So HTTPS connections won't work, unless you import the Root Certificate used by the proxy to Firefox as a trusted root certificate.

**Comment by titanium007** [comment]
See [this link](http://www.telerik.com/blogs/configuring-firefox-for-fiddler) on details how this is done for another proxy. Same concept applies here

**Comment by Stackoverload** [comment]
Thank you so much! I'm going to find a way (if possible) to do this programically, my users aren't going to want to go through all these steps. Do you know of a way in-case I can't find any?

**Comment by titanium007** [comment]
I am not aware of any way to do it directly from .Net. You may find [this answer](http://stackoverflow.com/questions/1435000/programmatically-install-certificate-into-mozilla) in SO interesting.

**Comment by dmakaroff** [comment]
> As of version 49, Firefox can be experimentally configured to automatically search for and import CAs that have been added to the Windows certificate store by a user or administrator. To do so, set the preference "security.enterprise_roots.enabled" to true.

Even though I set **security.enterprise_roots.enabled** to **true** it still complains about untrusted connection. It works with Fiddler 4 without importing its certificate. I created issue #180.

**Comment by rvknth043** [comment]
Have we found any solution how to overcome this bug. any suggestion will be appreciated on how we set Firefox to use from windows certificate store and work normally.
