### ISSUE TITLE
ExternalProxy broken?

### ISSUE THREAD

**Issue by vitalyster** [justcoding121/Titanium-Web-Proxy#242]
I want to proxy client requests via chain of Titanium and external proxy.
I'm using basic example, just set UpstreamHttpsProxy and UpstreamHttpProxy to my external proxy. 
My external proxy does not receive any requests. In network dump I see example Titanium app is trying to authenticate with external proxy credentials on the original site, not on the external proxy.
Am I miss something or external proxy support just broken?
I've tried Titanium.Web.Proxy and Titanium.Web.Proxy -Pre from NuGet, and build it myself from develop branch, same issue everywhere.

**Comment by justcoding121** [comment]
Should be fixed in latest stable.

**Comment by vitalyster** [comment]
Great! Now it works it most cases, but still pass something wrong to destination site. https://yandex.ru/ for example return 404 with this proxy chain (works with titanium with external proxy and works with external proxy without titanium)

**Comment by justcoding121** [comment]
I chained Titanium with Fiddler and the site works just fine. Not sure how to reproduce.

**Comment by vitalyster** [comment]
I'm using squid, will try different proxy

**Comment by justcoding121** [comment]
Could be related #261

**Comment by vitalyster** [comment]
I just tried latest develop source and looks like problem gone, thanks!
