### ISSUE TITLE
Create less cerificates (using wildcard certificates)

### ISSUE THREAD

**Issue by honfika** [justcoding121/Titanium-Web-Proxy#246]
TWP generates much more certificate than another similar library.
It is using wildcard certificates, so while it is creating only one *.google.com certificate TWP creates the following certificates when I have an open gmail and a google search page:
ogs.google.com
clients4.google.com
etc (5 more)

So 7 times more certificate with only 2 browser window. Probably the number of certificates are much more when I'm using other google services.

**Comment by justcoding121** [comment]
I've added some adjustments for this, not sure if it is 100% correct.

**Comment by justcoding121** [comment]
Should be fixed now.
