### ISSUE TITLE
Bug in Kerberos/NTLM/Negotiate

### ISSUE THREAD

**Issue by justcoding121** [justcoding121/Titanium-Web-Proxy#251]
Outlook client appears is not syncing when on proxy and when the mail server is exchange with windows authentication. Https auto-discovery calls from outlook fails.

Marking this as open for investigation and fix. Specific file related to this is below.
https://github.com/justcoding121/Titanium-Web-Proxy/blob/develop/Titanium.Web.Proxy/WinAuthHandler.cs

**Comment by honfika** [comment]
@justcoding121 Is this problem fixed?

**Comment by justcoding121** [comment]
Appears to be fixed now.
