### ISSUE TITLE
Configure system proxy in one step

### ISSUE THREAD

**Issue by honfika** [justcoding121/Titanium-Web-Proxy#256]
For some reason on my friends machine when I quickly set Titanium as system proxy for HTTP and HTTPS (in this order), only one is applied (always only the HTTP)
I've traced the registry writing in TWP, it sets the ProxyServer (at the 2nd call) 
from: http=127.0.0.1:8877
to: http=127.0.0.1:8877;https=127.0.0.1:8877
So the problem is not in TWP.
But the value is restored to http=127.0.0.1:8877

It is a Windows 7 system. I tried to reproduce the problem on a virtual Win7, but I was not able to reproduce it. So maybe it is some protection in a 3rd party antivirus program. (I'm not sure what is the reason)

So I'd like to refactor the `SetAsSystemProxy` call to be able to set both in one step.
I'd like to change to `ProxyProtocolType` to Flags enum and make it public:
```
    [Flags]
    public enum ProxyProtocolType
    {
        Http = 1,
        Https = 2,
    }

```
And `SetAsSystemProxy` (Instead of the current `SetAsSystemHttpProxy` and `SetAsSystemHttpsProxy`) will accept this enum as parameter:
proxyServer.SetAsSystemProxy(ProxyProtocolType.Http | ProxyProtocolType.Https);

I'll keep the `SetAsSystemHttpProxy` and `SetAsSystemHttpsProxy` methods for comaptibility.

**Comment by justcoding121** [comment]
Sure. Please make a PR.

**Comment by honfika** [comment]
PR Created.

Now when you stop the proxy server, the ProxyEnable registry value is set to 0, ProxyServer value is set to empty string. I think it would be better to save the original values (before the first SetProxy call) and on Stop restore the saved values.

**Comment by justcoding121** [comment]
We used to reset original settings long time ago. I removed it because of the debugging inconvenience when closing the console window. Later we started to listen for Console exit event.

You can do a PR for the functionality if you like. So the settings should be restored not only when proxy is stopped by calling the API, but also when the process is exited (for example by closing the app). This is done only when proxy was set as system proxy.

**Comment by honfika** [comment]
It can be restored when the application normally exits, it is not a problem.
But no chance to restore the settings if the user kills the process from task manager.
Is it enough?

**Comment by justcoding121** [comment]
Ya that's fine.
