### ISSUE TITLE
Possibility to do proxy with http binding (address:80/proxy)

### ISSUE THREAD

**Issue by MartinStensaker** [justcoding121/Titanium-Web-Proxy#262]
Everything works as expected -- however, we'd like to use this with http bindings on port 80. Not sure if this case is supported or how to go about adding this functionality.

The case is that our services are deployed in very strict environments and we have a bunch of apps listening on port 80 (which is usually open), and this is done by using various binding techs (like NetTcpBinding and httpSelfHostServer). This allows access to different services on the same port (80) and access is determined by for example ipaddress/service/-addresses. I can see in the source code that TcpListener is widely used, which in turns expects an IPAddress type for what to listen to. What we'd like to do is enable the proxy to listen at ipaddress:80/proxy/ basically. Have you got any suggestion for how to achieve something like this?

**Comment by justcoding121** [comment]
I believe you are talking about sharing Port 80 with different applications. I am not sure how it can be achieved given that the Proxy uses TcpListener which need an explicit ownership of a port to be successful. For example in below example we are going to own port 9000.

https://github.com/justcoding121/Titanium-Web-Proxy/blob/develop/Examples/Titanium.Web.Proxy.Examples.Basic/ProxyTestController.cs#L51 

An option probably is to use IIS ARR to selectively forward requests to proxy which will be listening on a local port. Again I am not sure.

**Comment by MartinStensaker** [comment]
Yes, that's what we're aiming for. 

We have researched the topic further and found out that most technologies don't support proxy:80/path-proxies anyway. IIS ARR using subdomains might be a solution, thanks for the input.
