### ISSUE TITLE
Cannot find some values in Request

### ISSUE THREAD

**Issue by judebigj** [justcoding121/Titanium-Web-Proxy#277]
Hello,
         I am trying to compare the results of Fiddler and the proxy. I notice that the headers are coming fine, however, I fiddler, there is a "TextView\Syntax View" tab which show me some information which i am not able to find in Ccs.SsoOne.Proxy.Http.Request instance. 
Example
Following is the raw view as shown in fiddler :

**POST https://docs.google.com/sharing/commonshare HTTP/1.1
Host: docs.google.com
Connection: keep-alive
Content-Length: 586
X-Same-Domain: explorer
Cache-Control: no-cache
Origin: https://docs.google.com
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
Content-Type: application/x-www-form-urlencoded;charset=UTF-8
X-Client-Data: CIu2yQEIo7bJAQjEtskBCPucygEIqZ3KAQjQnsoB
Accept: */*
Referer: https://docs.google.com/sharing/share?id=1-GolHk42bhEH48Ffs6DH_W3cJ_KByKU7DDrS8BgeVxs&foreignService=kix&gaiaService=writely&shareService=kix&command=init_share&subapp=10&popupWindowsEnabled=true&shareUiType=default&hl=en&authuser=1&rand=1497956822537&locationHint=unknown&preload=false
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.8
Cookie: SID=0wQee9SAM6qsVuSZR2ZndgudBoFVx9O2dl_3Z0OxxTqq-G5zfbe39PGHbcljetjU50xYhw.; HSID=A1d8E8HhUrj9vAMjp; SSID=A78NydqS75EkLGIHe; APISID=8Ke4AXN6MOuVNE3D/AOCeB2IuNA1zoSlr6; SAPISID=p80Sy5ISYYyXIK0s/A4_a2Rj0BH7l-65PU; S=explorer=9z5Mkob8pJSyakk8jXaZK3HfSt6VGuNZ; NID=106=qG1J4UuJEezmtWsTkVyNYSmvYuVHsk9p8itxvoIWP2dIimxA3CgJu2_DTLFKO5sd_SaE6Tc1Pv4WyD7aK_cMPwF2TSrd0IZxLh5g0IxUa_v8P7Smpi3U1i2lm6gLvRfGdCP5-VcXUmOYqM3tGa0doqIzR2e67q_wegF9y0h3HQyVL8NbrIyPda1gZW1AdXofNb9wKfgnvgmFAj33tuUGFg; lbcs=3; SIDCC=AA248bfajZnkAOfqw2x63oxYLZdx1mvRgUZ6UZqkJH7tw_5whhKuootfgEdnNc5S1Jg0CPum7lZajCAs5N8FnQ

hl=en_US&token=AFNOsBZk-Z2WJfXxJLU6gfCssd_ro9PQIw%3A1497956824550&foreignService=kix&shareService=kix&authuser=1&locale=en_US&requestType=email&itemIds=1-GolHk42bhEH48Ffs6DH_W3cJ_KByKU7DDrS8BgeVxs&confirmed=false&notificationInfo=%7B%22messageType%22%3A%22attach%22%2C%22recipient%22%3A%22%5C%22Jude%20Aloysius%5C%22%20%3Caloysius.j%40sysanc.org%3E%22%2C%22subject%22%3A%22test1232113%22%2C%22message%22%3A%22fdaz%22%2C%22optionValues%22%3A%7B%22ccMe%22%3Afalse%7D%2C%22exportMimeTypes%22%3A%7B%221-GolHk42bhEH48Ffs6DH_W3cJ_KByKU7DDrS8BgeVxs%22%3A%22application%2Fpdf%22%7D%7D**

Notice that "hl=en_US&token......."  value .I am not able to find this value in the request object in your API.
I am attaching the screen shot of the same.
![screenshot](https://user-images.githubusercontent.com/9862996/27334335-a360f0cc-55e6-11e7-8524-ec872b0c738d.png)

Can you please help me find this.

**Comment by justcoding121** [comment]
What you are seeing consolidated in fiddler is headers and request body. Try `string bodyString = await e.GetRequestBodyAsString();` to get the request body you are looking for.

**Comment by judebigj** [comment]
Thanks that did the trick. Also can let me know what format is this body in and how do i parse it.

**Comment by judebigj** [comment]
I used HtmlUtility.UrlDecode to decode the body.
Thanks for your help.
