### ISSUE TITLE
Keep the header  + body data after session complete

### ISSUE THREAD

**Issue by honfika** [justcoding121/Titanium-Web-Proxy#280]
Now the `Request.Dispose` method is the following (`Response.Dispose` is similar):
```
        public void Dispose()
        {
            //not really needed since GC will collect it
            //but just to be on safe side

            RequestHeaders = null;

            RequestBody = null;
            RequestBody = null; // btw, this should be RequestBodyString
        }

```

I've created a GUI demo application where I'm collection all the previous sessions to a list. I'd like to show details when the user selects an item from the list.
But now when the session completes all the header and body data is cleared. However the it would be possible to store the data in the application which uses TWP, but I think it would be better to keep it in this object and delete them when the object is finalized by GC.
I think it is much more user friendly, now the user of the TWP library can be confused why are they null.

At least for the Header property, because it is public, but I'd like to change the Body property to public get too, and change the comment that it is only available if the user asked TWP to read it in BeforeRequest event.

What do you think about it?

**Comment by justcoding121** [comment]
We are doing this only at the end of session. If you keep a reference, for example assigning the RequestHeaders and RequestBody to a dictionary or even another variablr, it will be still accessible after the end of session. 

The fact the we are setting the above objects to null have no bearing on other references to the same objects. Other references will not become null.

**Comment by justcoding121** [comment]
Also we don't keep headers or body after the session so that developers don't blame the proxy for possible out of memory  exceptions. If they need it they can always keep their own datastructure for it, and reference the headers and body. The content is volatile from the perspective of proxy. 

If you look at the basic example project I've shown how one can use RequestId to store and access past requests in to a ConcurrentDictionary.

**Comment by honfika** [comment]
I think at least the header collection should be available after the session ends (which means that the response is received)
The Resuest and Response classes has a lot of useful properties/methods, which works only if the headers are there.
Now the user has 2 possibilities if he wants to use the Request/Response classes after session end (like in my GUI demo):
- Save the header collection when it is available. Later set it back with reflection (because the setter is private)
- Create an own Request class, and copy the properties

None of them are good solution.

So I'd prefer keep the headers, it is small and it will be freed by GC when the request object is deleted anyway...

**Comment by justcoding121** [comment]
You can create a PR for this.

**Comment by justcoding121** [comment]
Wait. I've added a demo on how to keep headers for later use just now. Wouldn't that suffice?

**Comment by justcoding121** [comment]
After looking at #326 I kinda agree with your suggestion now :-), WebSession.Dispose() should not be manually called by the proxy. It should be called by GC when its ready to be collected.
