### ISSUE TITLE
Problem with secured pages

### ISSUE THREAD

**Issue by doronsaar** [justcoding121/Titanium-Web-Proxy#283]
Hi and thank you for this development.
I bulit a Windows service in c# which works with Titanium-Web-Proxy.
I'll be happy to share it as part of this project when it works well.

The problem:

With regular http pages it works just fine.
With secured https pages it works OK when using local server as a proxy (not very useful I just used it to debug my Windows service), but with secured pages I get an error in the browser NET::ERR_CERT_INVALID.

I downloaded the source code of Titanium-Web-Proxy and tried to debug it.
I noticed that this line in RequestHandler.cs:

                    //Now read the actual HTTPS request line
                    httpCmd = await clientStreamReader.ReadLineAsync();

assigning null to httpCmd.

Any Ideas?

(
Please try with the following url maybe it makes any difference: 
https://mslworld.egged.co.il/#/linenumber/1/0/0-0/
)

**Comment by honfika** [comment]
Hi,

Is this problem occurs only if you use it in a Windows Service?
Which user executes the service?  Local system? Local service? Your user?
Could you please try it with your user?

**Comment by doronsaar** [comment]
I now created a Console Application wraping my service to test it.
No difference. 

The put the user Administrator.

**Comment by bicdomain** [comment]
I had the exact same issue running under a Windows Service.  The way I got it to work was by explicitly referencing the root cert on the file system E.g.:

`    FileInfo executableFileInfo = new FileInfo(Application.ExecutablePath);
                string executableDirectoryName = executableFileInfo.DirectoryName;

                proxyServer = new ProxyServer();
                proxyServer.RootCertificate = new X509Certificate2(Path.Combine(executableDirectoryName, "rootCert.pfx"), string.Empty, X509KeyStorageFlags.Exportable);
                proxyServer.TrustRootCertificate = true;
`
Hope this helps.

**Comment by doronsaar** [comment]
Where do I get the PFX file from?

**Comment by honfika** [comment]
You should generate your own certificate. For exmaple you can use makecert.exe.
Or if you download and start the demo project from Titanium repository (https://github.com/justcoding121/Titanium-Web-Proxy/tree/develop/Examples/Titanium.Web.Proxy.Examples.Basic), it will genereate a root certificate next to the application. (in the bin/Debug folder)

**Comment by honfika** [comment]
I close this issue, feel free to reopen if needed.
