### ISSUE TITLE
Websocket requests 

### ISSUE THREAD

**Issue by justcoding121** [justcoding121/Titanium-Web-Proxy#284]
With the latest major changes Websocket requests are broken.

Related PR https://github.com/justcoding121/Titanium-Web-Proxy/pull/281

@honfika 

I believe the issue started after the changes on SendRaw method. And inside that specifically CopyAsync method changes. Because web-socket requests are relayed as you probably know. Look my screenshot below. TLS connection itself could not be tunneled. This is from Console example.

Meanwhile I am not sure how exactly the DataSent & DataReceived functions are to behave. 
Are they supposed to be called anytime data is sent to server or to client? In current implementations I don't think its behaving well.

![image](https://user-images.githubusercontent.com/2637679/27516720-5956fc4c-598d-11e7-95ce-b56b23957e05.png)

**Comment by honfika** [comment]
DataSent and DataReceived events should be called for websockets every time when any data is received or sent. 
For simple http sessions DataReceived is called at least at the end of content. So they are mainly for websockets, but it can be imporved for simple http, too... For example in chunked reponse.
Now (in PR #285) the received and sent bytes are working in the GUI demo for websockets.

**Comment by justcoding121** [comment]
No problem

**Comment by honfika** [comment]
You wrote that you don't mind the int for status codes. Then I'd like to change them to int in a PR.
