### ISSUE TITLE
HTTP Upstream missing code, HTTPS is fine

### ISSUE THREAD

**Issue by chancity** [justcoding121/Titanium-Web-Proxy#289]
```
                    if (useHttpProxy)
                    {
                        client = new TcpClient(server.UpStreamEndPoint);
                        await client.ConnectAsync(externalHttpProxy.HostName, externalHttpProxy.Port);
                        stream = new CustomBufferedStream(client.GetStream(), server.BufferSize);

                        using (var writer = new StreamWriter(stream, Encoding.ASCII, server.BufferSize, true) { NewLine = ProxyConstants.NewLine })
                        {
                            await writer.WriteLineAsync($"CONNECT {remoteHostName}:{remotePort} HTTP/{httpVersion}");
                            await writer.WriteLineAsync($"Host: {remoteHostName}:{remotePort}");
                            await writer.WriteLineAsync("Connection: Keep-Alive");

                            if (!string.IsNullOrEmpty(externalHttpProxy.UserName) && externalHttpProxy.Password != null)
                            {
                                await writer.WriteLineAsync("Proxy-Connection: keep-alive");
                                await writer.WriteLineAsync("Proxy-Authorization" + ": Basic " + Convert.ToBase64String(Encoding.UTF8.GetBytes(externalHttpProxy.UserName + ":" + externalHttpProxy.Password)));
                            }
                            await writer.WriteLineAsync();
                            await writer.FlushAsync();
                            writer.Close();
                        }

                        using (var reader = new CustomBinaryReader(stream, server.BufferSize))
                        {
                            var result = await reader.ReadLineAsync();

                            if (!new[] { "200 OK", "connection established" }.Any(s => result.ContainsIgnoreCase(s)))
                            {
                                throw new Exception("Upstream proxy failed to create a secure tunnel");
                            }

                            await reader.ReadAndIgnoreAllLinesAsync();
                        }
                    }`
```

**Comment by justcoding121** [comment]
Is this a problem in develop or last stable?

**Comment by chancity** [comment]
Latest stable.  Looks like you took out the HTTP and HTTPS in the latest develop..... 

https://github.com/justcoding121/Titanium-Web-Proxy/blob/develop/Titanium.Web.Proxy/Network/Tcp/TcpConnectionFactory.cs#L56-L97

**Comment by honfika** [comment]
Yes, it was simplified by me. But it should work with HTTP and HTTPS as before. What is the problem?

**Comment by chancity** [comment]
HTTP is working but its not authenticating if a username and password is specified https://github.com/justcoding121/Titanium-Web-Proxy/blob/stable/Titanium.Web.Proxy/Network/Tcp/TcpConnectionFactory.cs#L125-L130

**Comment by honfika** [comment]
So it should not authenticate for HTTP, only for HTTPS?

**Comment by justcoding121** [comment]
I think what he is saying is that the upstream Proxy Authentication works only for HTTPS but not for HTTP upstream proxy.

https://github.com/justcoding121/Titanium-Web-Proxy/blob/stable/Titanium.Web.Proxy/Network/Tcp/TcpConnectionFactory.cs#L125

I wonder we ever supported HTTP upstream proxy authentication.

**Comment by honfika** [comment]
It was not supported earlier. The externalProxy.UserName was used only in the HTTPS case. 
As you can see it here, in the "old" code:
https://github.com/justcoding121/Titanium-Web-Proxy/blob/stable/Titanium.Web.Proxy/Network/Tcp/TcpConnectionFactory.cs#L125

But when I simplified it, i "fixed" it to use it in both (common code) case. However I did not try the proxy authentication.
So if earleir it was working, but now not, then it is my fault, and it should NOT send the authentication header for HTTP. In this case it is enough to add an "isHttps &&" check to the 
`if (!string.IsNullOrEmpty(externalProxy.UserName) && externalProxy.Password != null)
condition.

**Comment by justcoding121** [comment]
I did'nt work on this part either. It was by some other contributer. Looking at the spec, I think the way we handle it is not correct.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Proxy-Authorization

Only after a 407 response from upstream proxy should we [send the credentials.](https://github.com/justcoding121/Titanium-Web-Proxy/blob/stable/Titanium.Web.Proxy/Network/Tcp/TcpConnectionFactory.cs#L89)

**Comment by justcoding121** [comment]
And I think we can do the same for HTTP as well, given that we are already doing that for clients on  both [HTTP](https://github.com/justcoding121/Titanium-Web-Proxy/blob/develop/Titanium.Web.Proxy/RequestHandler.cs#L314) and [HTTPS](https://github.com/justcoding121/Titanium-Web-Proxy/blob/develop/Titanium.Web.Proxy/RequestHandler.cs#L106). 

https://github.com/justcoding121/Titanium-Web-Proxy/blob/develop/Titanium.Web.Proxy/ProxyAuthorizationHandler.cs

**Comment by honfika** [comment]
Do you know any small, simple proxy server which supports authentication?
I'd like to fix this issue,  but I don't want to spend a lot of time to install/configure an unknown proxy server.
Or is there a public, accessible server?

**Comment by chancity** [comment]
Squid proxy.  I can setup an interface for you to test with.

**Comment by honfika** [comment]
Ok, then please setup it for both http and https. And send me the user+password in email. my github user name gmail.com

**Comment by chancity** [comment]
Titanium:Titanium@158.69.115.45:3128

**Comment by honfika** [comment]
Thanks, you can turn it off.

**Comment by honfika** [comment]
@justcoding121 It works if the authentication header is sent in the first request. The mozilla site writes only "usually after 407".
Yes, thats true, it seems to be unnecessary to call the `CheckAuthorization` method on keep alive. At least if the result of the `AuthenticateUserFunc` is time invariant.

**Comment by honfika** [comment]
Browsers sends the authentacion headers on every request in a TCP session, so the current behavior is not wrong, authentication should work on keep alive connections. And maybe it can be useful if you want to block a user who already has an open connection:)

**Comment by justcoding121** [comment]
Okay. I think then we should also remove the check for [`httpsConnectHostname == null`](https://github.com/justcoding121/Titanium-Web-Proxy/blob/develop/Titanium.Web.Proxy/RequestHandler.cs#L314)? Since the user may decide to change the password.

**Comment by chancity** [comment]
I'm going to add an interface to swap out an upstream proxy with another if certain conditions are meet within a response/request.  This might be really specific to my use case though.  Would this feature be PR worthy? Seems it might be out of the core codes scope....

**Comment by justcoding121** [comment]
Let's have some sanity first with all these issues. Later we may be able to allow dynamically changing upstream proxy.

**Comment by chancity** [comment]
You should setup a gitter, discord, or slack for us to chat in 💃

**Comment by honfika** [comment]
I think we should not remove the `httpsConnectNostname == null`, becasue it is false only when we are in a decrypted HTTPS session. I'm not sure, but i think in this case the proxy autentication header is not added. It is added to the connect request.
