### ISSUE TITLE
Communication outside PRs and issues.

### ISSUE THREAD

**Issue by chancity** [justcoding121/Titanium-Web-Proxy#292]
@justcoding121 You should setup a gitter, discord, or slack for us to chat in and put it in the readme.

**Comment by justcoding121** [comment]
I did join discord chat room that you send long time ago. But I am not available now since I work Monday-Friday business hours, even though I take a peek here at times when I am free.

**Comment by justcoding121** [comment]
I will get something put in readme later for slack or discord.

**Comment by honfika** [comment]
I'd prefer https://gitter.im/
Only some clicks to create a room. Just login with a github account. It can also add the link to the readme.md file automatically (creates pull request).

**Comment by justcoding121** [comment]
Done #354
