### ISSUE TITLE
Upstream override

### ISSUE THREAD

**Issue by justcoding121** [justcoding121/Titanium-Web-Proxy#309]
I think one of the users requested the ability to override upstream proxy settings on a per request basis. ~~I think a good way would be to add similar properties inside session event for request so that user can override it if needed.~~ I think along with this .~~[ForwardToUpstreamGateway](https://github.com/justcoding121/Titanium-Web-Proxy/blob/develop/Titanium.Web.Proxy/ProxyServer.cs#L235).~~ and [UpStreamEndPoint](https://github.com/justcoding121/Titanium-Web-Proxy/blob/develop/Titanium.Web.Proxy/ProxyServer.cs#L225) could be overridden. 

P.S: As per comment below upstream proxy can be overridden already. So other two options mentioned above need some work. May need to drop and recreate the current server connection if these two options change when using Http Keep-Alive.

**Comment by vitalyster** [comment]
Works already for me with GetCustomUpStreamHttpProxyFunc

**Comment by justcoding121** [comment]
I see. I was referring to below comment.

https://github.com/justcoding121/Titanium-Web-Proxy/issues/289#issuecomment-311746882
