### ISSUE TITLE
High CPU usage?

### ISSUE THREAD

**Issue by whc2001** [justcoding121/Titanium-Web-Proxy#310]
I just wrote a simple test program. It works perfectly, but as long as the proxy server was started, the CPU usage of yhe process goes up to around 30% even if nothing is processed through the proxy. Is that normal? If not, how can I solve this?

    internal class ProxyClass
    {
        private static ProxyServer server;

        private static Dictionary<Guid, string> requestList;

        public delegate void AfterSessionCompleteHandler(string api, string req, string resp);

        public static event AfterSessionCompleteHandler AfterSessionComplete;

        public static void Start(int localPort)
        {
            if (server == null)
                server = new ProxyServer();
            if (requestList == null)
                requestList = new Dictionary<Guid, string>();
            if (server.ProxyRunning)
                throw new InvalidOperationException("Proxy is running!");
            server.BeforeRequest += Server_BeforeRequest;
            server.BeforeResponse += Server_BeforeResponse;
            ExplicitProxyEndPoint local = new ExplicitProxyEndPoint(IPAddress.Any, localPort, false);
            server.AddEndPoint(local);
            server.Start();                //##CPU usage rises after executing this
        }

        public static void Stop()
        {
            if (!server.ProxyRunning)
                throw new InvalidOperationException("Proxy not running!");
            server.BeforeRequest -= Server_BeforeRequest;
            server.BeforeResponse -= Server_BeforeResponse;
            server.Stop();
            requestList.Clear();
        }

        private static async Task Server_BeforeResponse(object sender, Titanium.Web.Proxy.EventArguments.SessionEventArgs e)
        {
            try
            {
                if(requestList.ContainsKey(e.Id.ToString()))
                {
                    string url = e.WebSession.Request.Url;
                    string req = requestList[e.Id];
                    string resp = e.WebSession.Response.HasBody ? await e.GetResponseBodyAsString() : string.Empty;
                    AfterSessionComplete?.Invoke(url, req, resp);
                    requestList.Remove(e.Id);
                }
            }
            catch(Exception ex)
            {
                Console.WriteLine(ex.Message);
            }
        }

        private static async Task Server_BeforeRequest(object sender, Titanium.Web.Proxy.EventArguments.SessionEventArgs e)
        {
            requestList.Add(e.Id, e.WebSession.Request.HasBody ? await e.GetRequestBodyAsString() : string.Empty);
        }
    }

**Comment by honfika** [comment]
I can't reproduce the problem. So the proxy is not doing anything (no http request sent from anywhere) and the CPU usage is still high?

Btw, your sample class has a compile error at this line:
`if(requestList.ContainsKey(e.Id.ToString()))`

**Comment by whc2001** [comment]
Sorry about that. The problem has nothing to do with the proxy. And the error is because I used `requestList = new List<string, string>()` before and forgot to modify when paste to here.

**Comment by honfika** [comment]
I assume you used `Dictionary<string, string>`, List has only 1 generic parameter and has no `ContainsKey` method:)
What was the problem?

**Comment by whc2001** [comment]
I've said the problem has nothing to do with this project. It's my silly mistake that used `while(true)` to jam the main thread to wait for event but forget to add `Thread.Sleep()`. Sorry for that XD
