### ISSUE TITLE
Why always occur exception in ProxyServer.ExceptionFunc ?

### ISSUE THREAD

**Issue by GreatFireWall** [justcoding121/Titanium-Web-Proxy#312]
![image](https://user-images.githubusercontent.com/4510984/29358468-bf512182-82ad-11e7-8362-8795ceea32e2.png)
![image](https://user-images.githubusercontent.com/4510984/29358542-feae5a5c-82ad-11e7-9fe6-a5501e1df16d.png)

**Comment by honfika** [comment]
Since it is a SocketException, probably one of the connections (server or web browser) was disconnected.
