### ISSUE TITLE
Certificate issue in Firefox - Gmail

### ISSUE THREAD

**Issue by judebigj** [justcoding121/Titanium-Web-Proxy#315]
I have been working with chrome so far and the proxy works very well on it.
However I recently tested it on firefox it complained about "Connect not secure".
Following are the steps to reproduce the issue:

1. open firefox goto gmail.com (this open fine). Now login to gmail (open fine) no problem till here.
2. Now close firefox (without logging off).
3. Restart firefox and goto gmail.com. It throws the message "Your connection is not secure".

Can you please help me this?

**Comment by honfika** [comment]
When do you start the proxy? With which settings?
Did you enable the enterprise_roots settings in Firefox?

**Comment by judebigj** [comment]
My proxy is running as windows service (logged on as Admin). 
I instantiate it as 
```
 proxyServer = new ProxyServer();            
 proxyServer.TrustRootCertificate = true;
```
Enabling enterprise_root settings in Firefox fixed the problem.
I did this by creating a .js file in the installation folder of Firefox  under default\pref folder
with contents:
/* Allows Firefox reading Windows certificates */    
pref("security.enterprise_roots.enabled", true);

This solved the issue for firefox, Is there any specific step I need to do to make proxy work
on other browsers like Safari or IE?

Thanks for your quick response.

**Comment by honfika** [comment]
IE does not need any special settings. I don't know the other browsers.

**Comment by justcoding121** [comment]
Safari also looks at the Windows Store like Chrome, I have tested this some time time ago. Not sure if anything changed in latest versions.

**Comment by judebigj** [comment]
Thanks, any plan to develop proxy for emails clients (SMTP\IMAP proxy)?

**Comment by honfika** [comment]
No, no plans for email protocols.
I close this issue due to inactivity. Feel free to reopen it when problem still exists.
