### ISSUE TITLE
Problem in safari for gmail

### ISSUE THREAD

**Issue by judebigj** [justcoding121/Titanium-Web-Proxy#317]
Hello,
        I am facing problem accessing gmail on Safari browser when my proxy is enabled. Please find attached screen shot.

![2017-09-08](https://user-images.githubusercontent.com/9862996/30209331-24779852-94b5-11e7-9570-0aa4c5f77ddf.png)

**Comment by honfika** [comment]
I can't reproduce this problem. I've installed Safari 5.1.7 (7534.57.2) to Windows 10.
Could you please provide any other infromation which may help to solve this problem?
For example the HTTP(S) traffic.

Is this problem occurs only with gmail?
Or with all https site?
Or with all (http+http) sites?

**Comment by judebigj** [comment]
It works well for other https websites, its only gmail,com has the problem.
I am using same safari version as yours.

**Comment by honfika** [comment]
It is very strange... Can you reproduce the problem on another machine?
Did you try to reinstall the browser (or Windows?)

**Comment by vitalyster** [comment]
Safari 5.1 is from 2009, are you serious?

**Comment by honfika** [comment]
From 2012. It is the last version for Windows.

**Comment by judebigj** [comment]
I am facing another wherein I am not able to login from my eclipse IDE when the proxy is set,
Eclipse gives an option to sign into google account. I have to by-pass the proxy in order for the sign-in.

**Comment by honfika** [comment]
There was a pull request recently (#388), maybe the same issue.

Could you please try the latest beta?

**Comment by honfika** [comment]
I close this issue due to inactivity. Feel free to reopen it when problem still exists.
