### ISSUE TITLE
Multiple Proxy

### ISSUE THREAD

**Issue by judebigj** [justcoding121/Titanium-Web-Proxy#322]
Hi,
   I have a situation where I have a local proxy running using the titanium proxy and a network proxy running on firewall machine. Is there a way I can make the local Titanium proxy to forward the requests to the network proxy?

**Comment by honfika** [comment]
Hi,

Yes, Just set the `ProxyServer.UpStreamHttpProxy` and/or `ProxyServer.UpStreamHttpsProxy` properties.

**Comment by judebigj** [comment]
Thanks,
            Do I also need to set "ForwardToUpstreamGateway" to true?

**Comment by honfika** [comment]
No, that setting reads the upstream proxy from Windows . So if you configure the upstream proxy manually it is not needed.

**Comment by judebigj** [comment]
I am facing problem when i setup the ProxyServer.UpStreamHttpProxy and/or ProxyServer.UpStreamHttpsProxy.
Can you confirm whether following is correct:

 proxyServer.UpStreamHttpsProxy = new ExternalProxy();
 proxyServer.UpStreamHttpsProxy.HostName = "10.10.2.82";
 proxyServer.UpStreamHttpsProxy.Port = 808;
 proxyServer.UpStreamHttpsProxy.UserName = "jude";
 proxyServer.UpStreamHttpsProxy.Password = "jude@123";


"10.10.2.82" is ip of the machine in LAN which has CcProxy running.

**Comment by judebigj** [comment]
This got fixed with the latest version.
