### ISSUE TITLE
Support for multiple outgoing IPs

### ISSUE THREAD

**Issue by Wintereise** [justcoding121/Titanium-Web-Proxy#325]
Hi,

I'm looking to add support for multiple outgoing IPs (similar to Squid's tcp_outgoing_address) based on some sort of an arbitrary ACL.

Can one of the devs point me towards where the current selection is performed on the code body (i.e: where the connection is initialized)? I figured asking would be faster than fumbling through the code.

Thanks!

**Comment by justcoding121** [comment]
To forward all requests via a particular IP address of machine use proxyServer.UpStreamEndPoint

https://github.com/justcoding121/Titanium-Web-Proxy/blob/develop/Titanium.Web.Proxy/ProxyServer.cs#L233

To forward an per request basis from client use args.WebSession.UpStreamEndPoint.

https://github.com/justcoding121/Titanium-Web-Proxy/blob/develop/Titanium.Web.Proxy/Http/HttpWebClient.cs#L31

Note that changing connections too often on a per request basis will affect performance. See below for what happens internally.
https://github.com/justcoding121/Titanium-Web-Proxy/blob/develop/Titanium.Web.Proxy/RequestHandler.cs#L363

On a per host (server hostname) basis would be better args.WebSession.Request.RequestUri.Host.

**Comment by Wintereise** [comment]
Hi @justcoding121 

Thanks for that, I'll try it out.

Is there a way to tell which local endpoint (ExplicitEndpoint) a request came in via? I tried looking into the `OnRequest(object sender, SessionEventArgs eventArgs)` arguments, but don't think I noticed it.

**Comment by Wintereise** [comment]
So, this didn't seem to exist, but adding it was quite trivial. I've created a pull request, can you please review? @justcoding121

**Comment by honfika** [comment]
May I close this issue?

**Comment by Wintereise** [comment]
@honfika Absolutely.
