### ISSUE TITLE
ExternalProxy is missing a ToString() override

### ISSUE THREAD

**Issue by fabricedupre** [justcoding121/Titanium-Web-Proxy#327]
ExternalProxy is missing a ToString() override

        public override string ToString()
        {
            return HostName + " : " + Port.ToString();
        }

**Comment by honfika** [comment]
Added in this commit: https://github.com/justcoding121/Titanium-Web-Proxy/commit/758ca4abaf5f42bb767bbfc9bf0740945e6d8ae5
Please close this issue if everything is ok.

**Comment by fabricedupre** [comment]
Great !
