### ISSUE TITLE
Certificate issue in Firefox

### ISSUE THREAD

**Issue by harrip12** [justcoding121/Titanium-Web-Proxy#329]
Hi,
I have updated my Titanium-Web-Proxy code with new code. It is working fine with google chrome, but getting certificate issue with Firefox. Also I referred "Certificate issue in Firefox - Gmail #315" and it is not working. Here I am trying to monitor all the URLs.

List<string> fMonitoredUrls = new List<string>();
fMonitoredUrls.Add("http*.*");
explicitEndPoint.IncludedHttpsHostNameRegex = fMonitoredUrls;

**Comment by judebigj** [comment]
I am facing similar issue, the moment I took the latest develop.
Is this a known issue?

**Comment by justcoding121** [comment]
Hi. When you say updated can you provide the version number you upgraded from and to?

**Comment by harrip12** [comment]
Updated from one of the release of May, 2017 to latest 9 Oct, 2017 (3.0.150)

**Comment by honfika** [comment]
Are you sure that it works with the old code (from May) and the latest Firefox?
I tried several older versions of Titanium but it was not working with my latest Firefox version (I'm sure that it worked earlier - when enterprise_roots was enabled and the proxy was started in admin mode -, because I used it)

If it works with the latest Firefox, could you please specify exactly which stable or beta release is it from nuget.
And which certificate engine is used? DefaultWindows ot BouncyCastle. Also please specify the Bouncy Caslte nuget version.

**Comment by judebigj** [comment]
I am not sure about the version. I had downloaded the sources of titanium back in May-June.
Not sure where can I find the version in the sources.
I had followed the steps as mentioned in #315 and used the BouncyCastle v1.8.1 . Based on the old code

internal CertificateManager(CertificateEngine engine,
            string issuer,
            string rootCertificateName,
            Action<Exception> exceptionFunc)
        {
            this.exceptionFunc = exceptionFunc;

            //For Mono only Bouncy Castle is supported
            if (RunTime.IsRunningOnMono() 
                || engine == CertificateEngine.BouncyCastle)
            {
                certEngine = new BCCertificateMaker();
            }
            else
            {
                certEngine = new WinCertificateMaker();
            }

            Issuer = issuer;
            RootCertificateName = rootCertificateName;

            certificateCache = new ConcurrentDictionary<string, CachedCertificate>();
        }

WinCertificateMaker was being used, so
I tried setting the Engine type default in the new build. But still no success.

**Comment by judebigj** [comment]
Would a genuine certificate (rather than self signed one) resolve the issue?

**Comment by honfika** [comment]
Please try the latest beta. Please ensure that the root certificate is recreated, so for example delete the rootCert.pfx file is you use that.

@justcoding121 :Could you please merge it to the beta branch?

**Comment by justcoding121** [comment]
okay.

**Comment by honfika** [comment]
@harrip12, @judebigj May I close this issue?

**Comment by judebigj** [comment]
Yes you may.

**Comment by harrip12** [comment]
I want to use genuine certificate instead of self signed certificate(rootCert.pfx) to decrypt requests.
Is there any way to do that.

**Comment by honfika** [comment]
@harrip12 I'll close this issue now. Please reopen it if needed.
