### ISSUE TITLE
Titanium proxy hangs for a minute on first request

### ISSUE THREAD

**Issue by vtyutin** [justcoding121/Titanium-Web-Proxy#334]
I use exactly code from Titanium proxy example. 
But I faced with issue that proxy hangs on handling first request (I tested https://youtube.com) for about a minute. I mean I even don't get onRequest callback invoked for a long time. 
I use latest version from Nuget. 
The all further requests are going pretty fast. 
I suspect it might be DNS resolving issue or SSL issue because all next request (starting from second one) are handling fast.

**Comment by vtyutin** [comment]
Stacktrace

![capture](https://user-images.githubusercontent.com/7600429/33230228-d9ec6f48-d1f8-11e7-9f1f-c6295aa47988.PNG)

**Comment by vtyutin** [comment]
It's not SSL issue because I set breakpoint in OnCertificateValidation callback function and it's invoked after that long delay. 
Please see the stacktrace above. I just press pause in VS when titanium hangs for a minute to evaluate active threads.

**Comment by honfika** [comment]
The 1 minute wait is here:
https://github.com/justcoding121/Titanium-Web-Proxy/blob/cd6b1a1520fd7329d91e6cf40d506bee39260b11/Titanium.Web.Proxy/Network/Certificate/BCCertificateMaker.cs#L209

And similar for the WinCertMaker.

Which target framework do you use and which certificate provider?
.NET Framework or .NET Core?
WinCertificateMAker or BouncyCastle?

If you use .NET Core and WinCertMaker, then maybe I fixed the problem with my latest commit (on developer branch), otherwise probably it still exists.
https://github.com/justcoding121/Titanium-Web-Proxy/commit/65850f44762412c1c6b8b6cd59bcf181f90ef1fc#diff-5e25352875eace31f472ba72954389ccR268

**Comment by vtyutin** [comment]
I use .NET. How to switch to .NET core?
Not sure what is used for cert making. How to know it?
Can you upload the latest release to Nuget? Because I use version from Nuget

**Comment by honfika** [comment]
@justcoding121 Could you please merge develop to beta? Or am I allowed to do that sometimes?

**Comment by vtyutin** [comment]
Better if you do it yourself. 
By the way can I create my own certificate and use it in Titanium proxy to prevent proxy of generating certificate every time on startup? If so, how can I do it?

**Comment by justcoding121** [comment]
@honfika I think ideally all developers should create a PR for each change against develop. I will try to create PRs for my changes in future. To merge to beta you can open a PR from develop against beta. Collaborator is the only option for personal repository and there is no way to change standard permissions attached to collaborators.

**Comment by justcoding121** [comment]
You can merge your own changes to beta if it allows to do so via a PR.

**Comment by vtyutin** [comment]
@honfika two questions:
1. Why 1 minute wait is necessary in BCCertificateMaker? I could not find such code in WinCertificateMaker. Is it true? If so, how can I force Titanium to use this maker?
2. Can I avoid certificate creation at all? If I have my own pfx file. Can I use it for certificate so that Titanium does not create certificate at all?

**Comment by honfika** [comment]
@justcoding121 What should I do to release a preview nuget package? I thought that it is automatically released when merged to the beta branch.
@vtyutin By default Titanium is creating the certificate on the very first start only and saves it to the rootCert.pfx file next to the entry assembly.

Alternatively you can load and set the root certivifate manuallly with the `ProxyServer.RootCertificate `property.

**Comment by honfika** [comment]
I don't know why was it set to 1 minute.
Usually it should be much faster to generate a ceritficate.

Maybe there is an exception in the `MakeCertificateInternal `call and the 
```
 manualResetEvent?.Set();
```
is never called.

I think the timeout should be added to the `WinCertificateMaker`, too.

**Comment by vtyutin** [comment]
It seems not certificate making delay issue. Because I just set RootCertificate property and program still hangs inside Titanium code for 40-60 seconds on first request only. 
Could you take a look at stack trace I have attached above?

**Comment by honfika** [comment]
I already checked your screenshot, but it does not help.

**Comment by vtyutin** [comment]
But the freeze really exists. It hangs the whole app for a long time. what the root cause might? This is for the first request only. Even If I do request from Windows browser (not from browser inside my app) the first request is really long. Might it be due to DNS or some other thing? How can I help you to analyze the issue? 
Can you send me your dll for x64 created? I will try it in my project.

**Comment by vtyutin** [comment]
![capture](https://user-images.githubusercontent.com/7600429/33242008-691fb2d0-d2e7-11e7-9af2-89c4ccf8d01d.PNG)

**Comment by vtyutin** [comment]
@honfika
I have added Titanium project as reference to my solution and built them together. 
So It give me ability to debug. 
Please see the screenshot attached above. It seems there is two tasks of Titanium that hangs in HandleClient method:
line 753:
await HandleClient(endPoint as ExplicitProxyEndPoint, tcpClient);
Does it help?

**Comment by honfika** [comment]
Not really, that is normal.

What version did you add? the latest develop source?

**Comment by vtyutin** [comment]
yes, latest develop

**Comment by honfika** [comment]
Could you please try the latest preview build from nuget? 3.0.199-beta

And please set the following property:
`            proxyServer.ExceptionFunc = exception => Console.WriteLine(exception.Message);
`


Is the WriteLine called?

**Comment by justcoding121** [comment]
@honfika yes. It does it automatically when you merge develop to beta. Same process for stable when merging beta to stable. Stable can be done once a beta version is there for a while without any issues. So stable is on an ad hoc basis.

**Comment by judebigj** [comment]
Any update in this? I am not facing the same issue with the latest develop.

**Comment by honfika** [comment]
@judebigj Could you please try that exception func what I wrote in my last comment 5 days ago?
Maybe it would help us to solve the problem.

Do you use the preview nuget package or the stable?

**Comment by vtyutin** [comment]
I took the latest version from repository and built it as release. Now it starts pretty fast.

**Comment by judebigj** [comment]
@honfika I added the exception function and it gives me the following error 
Exception Raised :Error whilst authorizing request
Exception Raised: Error occured whilst handling session response
Exception Raised: Error occured whilst handling session request
Does the above error help?
I downloaded the sources and build the dll.

**Comment by honfika** [comment]
@judebigj: @vtyutin said that it was fixed for him. Do you still have problem? It should be ok with the latest stable package.

**Comment by judebigj** [comment]
Yes the latest build solved the problem. Thanks.
