### ISSUE TITLE
1. not supported https (reverse) proxy ?

### ISSUE THREAD

**Issue by lobster2012-user** [justcoding121/Titanium-Web-Proxy#335]
2. Add, please, log for any event for debug without source code.

Thank you.

**Comment by honfika** [comment]
You should add the event handlers and make the logs.
What event do you need?

I don't understand your request.

**Comment by lobster2012-user** [comment]
Hi, @honfika !
1. How use https reverse proxy for http site ?
chain : client->http->proxyserver->https->proxy->http site

2. I need verbose logs for proxy server.
Now there are no detailed messages in case of any errors.

**Comment by honfika** [comment]
2. Did you set the ProxyServer.ExceptionFunc?

What other detailed error message do you need?

**Comment by lobster2012-user** [comment]
@honfika 
2. I got some exception.
It is not clear at what step the error occurred.
For example, after sending an unencrypted message to an encrypted connection.

**Comment by honfika** [comment]
Please provide a reproducible sample code and the expected error message.

**Comment by lobster2012-user** [comment]
I found error for my proxy chain.
My external proxy is https. This class hos not property IsHttps.
ProxyServer use exnternal proxy as http proxy only.

**Comment by honfika** [comment]
3:

This is not OS dependent. The HTTP header uses \r\n line ending even from Linux/Mac. We are not saving them to a file. Or what do you mean?

**Comment by lobster2012-user** [comment]
@honfika 
I looked at the current code. Everything is good with `newline`.
Perhaps it seemed to me that a standard (stream) writer.
