### ISSUE TITLE
In multipart/form-data we cannot able to get the --WebKitFormBoundary details which contain the filename

### ISSUE THREAD

**Issue by surendharb** [justcoding121/Titanium-Web-Proxy#345]
We tried to Intercept the file uploading to any online storage. We can able to intercept file upload to google, dropbox etc. But yahoo use multipart/form-data to upload the file. We need to extract the filename from the request. In Titanium  we cant able to fine the --WebKitFormBoundary details which contain the filename.

We cannot able to get the filename in "e.WebSession.Request.Headers;"

**Comment by justcoding121** [comment]
As you have found, this is application layer decisions specific to each websites that we have no control over.

**Comment by honfika** [comment]
I've implemented a new event called `MultipartRequestPartSent`. With this event you will receive the HTTP headers for each part.

```
        public async Task OnRequest(object sender, SessionEventArgs e)
        {
            if (e.WebSession.Request.Host == "mail.yahoo.com" && e.WebSession.Request.IsMultipartFormData)
            {
                e.MultipartRequestPartSent += MultipartRequestPartSent;
            }
        }

        private void MultipartRequestPartSent(object sender, MultipartRequestPartSentEventArgs e)
        {
            var session = (SessionEventArgs)sender;
            Console.WriteLine(session.WebSession.Request.Url);
            foreach (var header in e.Headers)
            {
                Console.WriteLine(header);
            }
        }

```

Output:
https://mail.yahoo.com/ws/v3/mailboxes/xxxx
Content-Disposition: form-data; name="jsonString"

https://mail.yahoo.com/ws/v3/mailboxes/yyyy

Content-Disposition: form-data; name="file2"; filename="sample.mkv"
Content-Type: video/x-matroska

It seems that @justcoding121 is working on the branches, so hopefully it will be released as beta package soon.

**Comment by justcoding121** [comment]
Good work!

One concern on below line though. How would developers unsubscribe from this event? If they don't do it after the end of session I would think it would be recipe for memory leak. 

` e.MultipartRequestPartSent += MultipartRequestPartSent;`

I think we set it to null when [we dispose it](https://github.com/justcoding121/Titanium-Web-Proxy/blob/develop/Titanium.Web.Proxy/EventArguments/SessionEventArgs.cs#L525). Same for DataSent & DataReceived event handlers.

**Comment by honfika** [comment]
@surendharb Please try the latest beta package:
https://www.nuget.org/packages/Titanium.Web.Proxy/3.0.216-beta

**Comment by surendharb** [comment]
Thank you so much for update.
