### ISSUE TITLE
SslStream

### ISSUE THREAD

**Issue by justcoding121** [justcoding121/Titanium-Web-Proxy#349]
@honfika I noted that you added files from [SslStream libary](https://github.com/justcoding121/StreamExtended) to this repository. I adjusted the SslStream library to have a beta branch as well so that we have more freedom to do experimental changes. I would personally prefer to have Ssl related tools in SslStream library. 

But I don't mind if you would like to keep it here. If so I would think we should move it under Network folder below with a subfolder named SslTools. Just for the sake of better readability and organization.
https://github.com/justcoding121/Titanium-Web-Proxy/tree/develop/Titanium.Web.Proxy/Network

**Comment by honfika** [comment]
I have already removed them just 5 minutes before this issue:)
I merged the develop to beta, but no beta nuget was released, why?

**Comment by justcoding121** [comment]
Okay. Np. 
I think your beta release was successful. I can see it.

https://www.nuget.org/packages/Titanium.Web.Proxy/3.0.216-beta

**Comment by honfika** [comment]
Then it was only slow:) OK. I think you can close this issue, right?
