### ISSUE TITLE
Why are the before request/response events invoked parallel?

### ISSUE THREAD

**Issue by honfika** [justcoding121/Titanium-Web-Proxy#350]
For example in this line the `BeforeRequest` event handlers are called parallel:
https://github.com/justcoding121/Titanium-Web-Proxy/blob/a3d562e5c5a29930851a41b7b96aee49f0a28bee/Titanium.Web.Proxy/RequestHandler.cs#L352

I think usually these events has only 1 subscriber, but in case when they have multiple subscribers they should not be called parallel.

They should be asynchronous, because users may want to await the `GetRequestBody`, etc. functions, but the different event handlers should not be called parallel. It may cause problems if the `GetRequestBody` is called multiple times parallel.

So I suggest to change the Invoke function to

```
        public static async Task InvokeEventHandlersAsync<T>(this Func<object, T, Task> callback, object sender, T args, Action<Exception> exceptionFunc)
        {
            var invocationList = callback.GetInvocationList();

            for (int i = 0; i < invocationList.Length; i++)
            {
                await InvokeAsync((Func<object, T, Task>)invocationList[i], sender, args, exceptionFunc);
            }
        }

```

**Comment by justcoding121** [comment]
Yes. I agree.

**Comment by honfika** [comment]
Thanks, I changed to not to call parallel.
