### ISSUE TITLE
Chunked encoding broken

### ISSUE THREAD

**Issue by justcoding121** [justcoding121/Titanium-Web-Proxy#351]
@honfika 
I think your change below is the issue
https://github.com/justcoding121/Titanium-Web-Proxy/commit/6393b39accdc2acf3c58723c3a71832691e63dd9

I just found this when I pulled latest develop. This can be reproduced by visiting [this website](https://www.jw.org/en/) in incognito window on chrome. Dev console in chrome show bunch of load failure for some urls. I noted that some pictures were not loading when browsing with latest version of proxy.

**Comment by honfika** [comment]
It should be fixed in the latest develop. Could you please try it?
Thanks for reporting.

**Comment by justcoding121** [comment]
Looks good. Thx
