### ISSUE TITLE
Proxy fails to load HTTPS pages if projects are targeting .NetCore or .NetStandard

### ISSUE THREAD

**Issue by CosminGramada** [justcoding121/Titanium-Web-Proxy#356]
I'm trying to capture and analyze traffic for some automated tests using Selenium.

If my test project is targeting .NET Framework, I get the confirmation message about adding the Titanium Root Certificate (btw, any idea if I can accept it automatically, without user intervention?) and everything works like a charm.
The problem arises when my test project is targeting .NET Core or Standard. I never got the approval message for Titanium Root Certificate, the page cannot be loaded in the browser and no HTTPS traffic is captured (HTTP seems to be fine, although I didn't fully checked everything).

NOTE: The first one tried was .NET Core, then .NET Standard and .NET Framework was my last resort, so the certificate didn't exist.

The code looks like this:
```
    [TestFixture]
    public class CaptureHttpTrafficTests
    {
        private IWebDriver _driver;
        private ProxyServer _proxyServer;
        private readonly IDictionary<Guid, Proxy.Request> _requestsHistory =
            new ConcurrentDictionary<Guid, Proxy.Request>();
        private readonly IDictionary<Guid, Proxy.Response> _responsesHistory =
            new ConcurrentDictionary<Guid, Proxy.Response>();

        [OneTimeSetUp]
        public void ClassInit()
        {
            _proxyServer = new ProxyServer();
            _proxyServer.TrustRootCertificate = true;
            var explicitEndPoint = new ExplicitProxyEndPoint(System.Net.IPAddress.Any, 18882, true);
            _proxyServer.AddEndPoint(explicitEndPoint);
            _proxyServer.Start();
            _proxyServer.SetAsSystemHttpProxy(explicitEndPoint);
            _proxyServer.SetAsSystemHttpsProxy(explicitEndPoint);
            _proxyServer.BeforeRequest += OnRequestCaptureTrafficEventHandler;
            _proxyServer.BeforeResponse += OnResponseCaptureTrafficEventHandler;
        }

        [OneTimeTearDown]
        public void ClassCleanup()
        {
            _proxyServer.Stop();
        }

        [SetUp]
        public void TestInit()
        {
            var proxy = new OpenQA.Selenium.Proxy
            {
                HttpProxy = "http://localhost:18882",
                SslProxy = "http://localhost:18882",
                FtpProxy = "http://localhost:18882",

            };
            var options = new ChromeOptions
            {
                Proxy = proxy
            };
            _driver = new ChromeDriver(options);
        }

        [TearDown]
        public void TestCleanup()
        {
            _driver.Dispose();
            _requestsHistory.Clear();
            _responsesHistory.Clear();
        }

        [Test]
        public void AnalyticsRequestMade()
        {
            _driver.Navigate().GoToUrl("https://github.com/justcoding121/Titanium-Web-Proxy");
            Assert.IsTrue(_requestsHistory.Values.Any(r => r.RequestUri.ToString().Contains("analytics")));
        }

        private async Task OnRequestCaptureTrafficEventHandler(object sender, SessionEventArgs e)
        {
            await Task.Run(
                () =>
                {
                    if (!_requestsHistory.ContainsKey(e.Id))
                    {
                        _requestsHistory.Add(e.Id, e.WebSession.Request);
                    }
                });
        }

        private async Task OnResponseCaptureTrafficEventHandler(object sender, SessionEventArgs e)
        {
            await Task.Run(
                () =>
                {
                    if (!_responsesHistory.ContainsKey(e.Id))
                    {
                        _responsesHistory.Add(e.Id, e.WebSession.Response);
                    }
                });
        }
    }
}`

**Comment by justcoding121** [comment]
Proxy installs root certificate for .Net Framework target because it exposes specific API to Windows for installation. But other targets are meant for cross platform and I don't think we can do the same.

So you would need to install the root certificate used for .Net standard/core manually.

**Comment by CosminGramada** [comment]
I get what you're saying and it makes sense. Perhaps a more explicit description in the Wiki page to state this fact?

**Comment by honfika** [comment]
On Windows it should work with .NET Core, but there was a bug. It is fixed now in develop bracnh (https://github.com/justcoding121/Titanium-Web-Proxy/commit/0a3c9bb50f1fe86a0f669d08f9dd1c11fcc95531)
On other OSes it is still not working.

**Comment by CosminGramada** [comment]
Awesome, seems to be working. Thanks.

**Comment by CosminGramada** [comment]
I'm sorry for reopening this, but it seems I talked to early.
When I tested it at the time of closing this issue, I verified that the Trust Certificate can be installed, and assumed that everything will work as for .NET Framework.

Indeed the Trust Certificate can be installed, but the proxy is not allowing any connections. Again, as in the initial issue report, I compared the same piece of code that is working in Net Framework with the one in .Net Core and unfortunately, as mentioned, it's not working.

**Comment by honfika** [comment]
I can't reproduce the issue. I'm starting the Basic example project with dotnet Core (It says version 2.1.100-preview-007326) and the HTTPS sites are loaded in Chrome.

Can you reproduce it with the Basic example?

**Comment by CosminGramada** [comment]
@honfika 
Could you please share somewhere your project?
I'm still unable to make it work and I want to determine what's the difference between your working solution and my own.

**Comment by honfika** [comment]
It is here in github in this repository:
https://github.com/justcoding121/Titanium-Web-Proxy/tree/develop/Examples/Titanium.Web.Proxy.Examples.Basic

**Comment by CosminGramada** [comment]
Sorry for the delay. 
Seems to be working with the Basic example. Back to the drawing board to see what I've messed up in my setup.

Thanks for the patience.
