### ISSUE TITLE
Proxy for all Protocols?

### ISSUE THREAD

**Issue by judebigj** [justcoding121/Titanium-Web-Proxy#358]
Well, this is not an issue, but I would like some help developing a proxy for all the internet traffic.
I Idea is to listen to network adapter(packet sniffing) for all the incoming\outgoing traffic and forward it to a proxy which will decrypt the tcp packets.
Can you please give some suggestion if there is a way we can modify your existing proxy to decrypt the network packets.

**Comment by honfika** [comment]
How do you know the private keys for decripting the traffic? I think it is not really possible.

**Comment by justcoding121** [comment]
@judebigj Unless you can issue a root certificate that you own and clients would trust it is impossible as honfika mentioned.

**Comment by judebigj** [comment]
> 
@judebigj Unless you can issue a root certificate that you own and clients would trust,
> 
I believe currently that is what your web proxy is doing. Just as you use your root certificate (self signed)
and make it trusted, can it also be done  for the decrypt the packets being forwarded?

**Comment by justcoding121** [comment]
Yes if you can make clients trust the root certificate of the proxy. Note that by default proxy makes your system trust the root it uses. It cannot do the same for remote clients.

**Comment by judebigj** [comment]
Thanks for the quick response.

"It cannot do the same for remote clients."
@justcoding121  "It cannot do the same for remote clients."
Yes , understood.
 Can you please give me a head start as to what modification would be required in your existing proxy to achieve this?

**Comment by justcoding121** [comment]
If you have access to client computers then you just need to install the root certificate used by TWP to clients certificate store. You will have to then setup a transparent endpoint in this proxy and forward all client HTTP/HTTPS traffic to proxy.

Without you having access to client computer there is no way to decrypt the traffic. Clients are not going to let you install the certificate of proxy without you have access to it. So simply put we cannot force clients to trust our root certificate. For security reasons there is not such standard API/mechanism/protocol with which we can make clients trust our certificate. If there is such a mechanism then anybody in the world can eavesdrop HTTPS traffic by doing a man-in-middle attack. That's the whole point of HTTPS, its is secure end to end. Nothing including DNS spoofing or Certificate tampering will work.

**Comment by judebigj** [comment]
I do have access to the client machine, so installing root cert won't be a problem.

**Comment by honfika** [comment]
You wrote packet sniffing. For me it seems that you want to decrypt the packages which is sent between the remote client and the remote server without modifying the packets. It is not possible.
When a proxy is used the remote client communicates with the proxy server and the proxy server communicates with the remote server. In this case the packets are decrypted and encrypted again with another key. So it is not enough to sniff the packages, you have to modify them. (Even when the client has installed the root certificate of the proxy server)

**Comment by judebigj** [comment]
Let me give a little more elaboration:
I was planning to have the packet sniffing program to be installed on each client. 
Example (for the simplicity traditional web session, proxy runs on port 8080): Firefox.exe connects to https://www.google.com

1.  The program will listen to an network interface of the client machine for incoming\outgoing packet.

2. When a packet is destined to some server will be modified by my program and the destination address will be changed to the local proxy (example 192.168.1.25:8080 where of 192.168.1.25 is local ip of the client machine)
Ex:
packet 192.168.1.25:1025 -> 104.196.49.47:443 is converted to incoming 104.196.49.47:1025 -> 192.168.1.25:8080 (local proxy listening here)

3. Proxy sees this as incoming connection from 104.196.49.47:1025 to port 8080. Then proxy queries the original destination port providing 104.196.49.47:1025 as a key, thus getting the original destination port 443. Now proxy has the complete information to establish the connection to the original server.

4. When proxy accepts the redirected connection it results an outgoing SYN-ACK packet 192.168.1.25:8080 -> 104.196.49.47:1025 which is also intercepted by redirector and converted to incoming 104.196.49.47:443 -> 192.168.1.25:1025

5. All other followed packets between Firefox.exe are processed on the same way.

So other packets (POP\SMTP\IMAP etc) will be captured in same way. 
Can the above be possible? if so what changes needs to be done in TWP to achieve the above?

**Comment by justcoding121** [comment]
In theory if you goal is to force all client traffic through the proxy clandestinely then what you are looking for a low level driver in client OS (like WinPCap) to rewrite packet destination IP/port address for outgoing TCP packets to the proxy listening IP/port instead of actual host IP (like google' IP). When packets are send back by proxy you should do this rewrite in reverse. (packet sender IP should be the actual IP address instead of proxy IP address). 

Alternatively you could also do this in a more easier but transparent way by using DNS spoofing, using your own DNS server to resolve all queries by client to proxy address.

The proxy should listen on a transparent end point. Now if the TCP packet is not HTTP/HTTPS the proxy would drop the connection, but ideally it should instead relay the connection so that other protocols over TCP would run smoothly. (We don't support this as of now). The client should be trusting the root certificate in either case.

**Comment by justcoding121** [comment]
@honfika I think it would be good to add an flag that says something like below. 

`public bool RelayNonHttpTraffic {get;set;}`

By default this should be false which means any non-http traffic would be dropped by proxy. If it is true then we should relay the traffic.

**Comment by honfika** [comment]
@justcoding121 I don't understand what to do when it is true.

Now the client connects to the proxy (either with Explicit or with a Transparent endpoint) and reads the first line (optionally after creating an SSL tunnel) which is the HTTP command which contains the remote server name. And connects to this server. But what to do when it is not HTTP? How to connect?

**Comment by justcoding121** [comment]
You are right. :-) @honfika
