### ISSUE TITLE
Filtering traffic from parallel runs

### ISSUE THREAD

**Issue by CosminGramada** [justcoding121/Titanium-Web-Proxy#359]
I'm planning on capturing traffic from Selenium tests.
I set up Titanium-Web-Proxy and a simple test and everything seems to work fine.

Now, considering the fact that there will be a lot of tests, I was planning on running them in parallel (Nunit does the job perfectly).

Now, my question is, is there a way to filter the traffic?

1. The first thing that I was thought was that maybe I would be able to set the proxy to listen on a range of ports: e.g. 18000-18200 and then start each browser instance to run on a particular port.
2. Another thing, would be to be able to filter the traffic based on the process ID. 

Any idea if this could be possible? Some other solution maybe?

**Comment by justcoding121** [comment]
When you say filter the traffic, can you please explain?

You don't need multiple instances of proxy or need to listen on multiple ports. Send all traffic to one port proxy is listening, and inside Request handler of your code you can check for process Id to establish the source of traffic. Use below property on your handler.

`e.WebSession.ProcessId.Value`

See example below
https://github.com/justcoding121/Titanium-Web-Proxy/blob/develop/Examples/Titanium.Web.Proxy.Examples.Basic/ProxyTestController.cs

**Comment by CosminGramada** [comment]
Thank you, this is exactly what I was looking for. A way to filter the requests/responses based on the browser windows that "generates" them. 
For some reason I seem to have missed it.
