### ISSUE TITLE
Redirect POST calls

### ISSUE THREAD

**Issue by ffortunato** [justcoding121/Titanium-Web-Proxy#363]
Hi, i'm having issues redirecting POST calls. It seems that when redirecting the body is going empty.
Anyone can help?

**Comment by honfika** [comment]
You can read about redirecting the post data in this page: https://softwareengineering.stackexchange.com/questions/99894/why-doesnt-http-have-post-redirect

I think you need something else, not a redirect. For example catch the post data in the proxy and send it to another host without a redirect, and send back the response to the client.

**Comment by juedi998** [comment]
Do u want to chanage GET request to Post??? u can try to write with this :
`
var request = e.WebSession.Request;
  request.Method = "POST";
  if (request.ContentLength <= 0) {
                        request.RequestHeaders["content-length"] = new HttpHeader("content-length", "");
    }
`
Note: if u modify the request Method, then be set "content-length" in requestHeader, otherwise can not be tampered.

**Comment by honfika** [comment]
Close this issue due to inactiity. Feel free to reopen if neeed.
