### ISSUE TITLE
How to use genuine certificate instead of self signed certificate?

### ISSUE THREAD

**Issue by harrip12** [justcoding121/Titanium-Web-Proxy#364]
Hello,
I want to use genuine certificate instead of self signed certificate(rootCert.pfx) to decrypt requests.
Is there any way to do that.

**Comment by honfika** [comment]
Yes, you can set the RootCertificate property toy your certificate:
https://github.com/justcoding121/Titanium-Web-Proxy/blob/0a3c9bb50f1fe86a0f669d08f9dd1c11fcc95531/Titanium.Web.Proxy/ProxyServer.cs#L85
