### ISSUE TITLE
PROPFIND method is not supported

### ISSUE THREAD

**Issue by BLilian** [justcoding121/Titanium-Web-Proxy#367]
Hi
The PROPFIND method is not supported and more critically seems to stuck the proxy.

To make it work, the proxy HasBody method can be changed to:
`public bool HasBody => Method == "POST" || Method == "PUT" || Method == "PATCH" || Method == "PROPFIND";`

Cheers

**Comment by honfika** [comment]
I think we should check the Content-Length header instead of adding all non standard methods to this condition.

Could you please copy the full header. Is the Content-Length specified?

**Comment by honfika** [comment]
Please try the latest beta version (3.0.261-beta or newer)

**Comment by BLilian** [comment]
Hi
Looks good.
Thanks for the quick response.
