### ISSUE TITLE
Throwing exceptions randomly

### ISSUE THREAD

**Issue by Blaconix** [justcoding121/Titanium-Web-Proxy#368]
Hello,

I might be a fool, but I have a problem. I tried getting a simple proxy up and running, it worked until I made a request. After that it just threw these exceptions:
`Exception thrown: 'System.IO.FileLoadException' in Titanium.Web.Proxy.dll`
`Exception thrown: 'System.IO.FileLoadException' in mscorlib.dll`

I though I did something wrong, then I tried the official console Example. The same happened.
I tried installing the beta version, same stuff.

Everything seems to be where it should, so I am not sure why would it throw a FileLodException. The strangest thing of all is that the proxy server starts just fine, then after a request happens it just breaks.
Any ideas?

**Comment by honfika** [comment]
Is it an unhandled exception? Could you please attach the stacktrace, too?

**Comment by honfika** [comment]
What do you use? .NET Framework, Core or Mono (or any other)?

**Comment by Blaconix** [comment]
Looks like the issue was due to StreamExtended being an older version. When I installed TWP through NuGET, it installed the latest stable version of StreamExtrended, 1.0.81.0 which returned a conflict warning with version 1.0.110.0 of TWP. 

I reinstalled StreamExtended with '-Pre', the newest version and the problem seems to be solved. Using .NET Framework 4.5.2.
