### ISSUE TITLE
Visual Studio 2015 Community Edition Can not load the downloaded solution

### ISSUE THREAD

**Issue by mergoktas** [justcoding121/Titanium-Web-Proxy#373]
Titanium-Web-Proxy and Titanium.Web.Proxy.Examples.Basic load failed in VS2015.
Here is the error message given:
C:\Users\pc\Downloads\Titanium-Web-Proxy-develop (1)\Titanium-Web-Proxy-develop\Titanium.Web.Proxy\Titanium.Web.Proxy.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  C:\Users\pc\Downloads\Titanium-Web-Proxy-develop (1)\Titanium-Web-Proxy-develop\Titanium.Web.Proxy\Titanium.Web.Proxy.csproj

**Comment by honfika** [comment]
You need VS 2017 to load the source code of Titanium Web Proxy, sine it is using the new simplified project format.
