### ISSUE TITLE
Connection Reset

### ISSUE THREAD

**Issue by gillespd** [justcoding121/Titanium-Web-Proxy#375]
I'm getting intermittent "java.net.SocketException: Connection reset" errors when accessing resources through the proxy. The problematic connections happen when running an "await e.Ok(System.Text.Encoding.UTF8.GetBytes(ticketresponse), retHeaders);" in a BeforeRequest event handler. In the same event handler, before running the "await e.Ok", I'm running a few web service calls synchronously to other remote resources. Could that be the cause? These other calls are not taking long, so I don't suspect a timeout is the issue.

It doesn't always fail. All other requests that are proxied normally process successfully.

**Comment by honfika** [comment]
Please try the latest beta build.

**Comment by larrybeall** [comment]
I'm not sure if my issue is the same as this, but with both the latest stable & latest beta nuget I get a connection reset.  I have pulled your repo down and built the beta branch directly and that seems to work just fine with the exact same code.

**Comment by honfika** [comment]
It is very interesting, because the beta branch is always the same as the latest beta package (except for about 10 miunutes while the build is running aftert a merge)

Could you please try now the latest beta package?

**Comment by honfika** [comment]
Couold you please try again, in the past week I guess it was fixed.

**Comment by gillespd** [comment]
Yes, the latest build seems to be working for me. Thanks!

**Comment by honfika** [comment]
Then I close this issue now.
@larrybeall  Ihope it works for you, too. Feel free to reopen if you still have any problem.
