### ISSUE TITLE
Cert not created on Windows Vista

### ISSUE THREAD

**Issue by harrip12** [justcoding121/Titanium-Web-Proxy#380]
Hi,
    Titanium library is not able to create the root.pfx file. When I debugged further I found the following exception:

```
Exception has been thrown by the target of an invocation.
ERROR2018-03-07 13:17:53 - Stack Strace ::    at System.RuntimeType.InvokeDispMethod(String name, BindingFlags invokeAttr, Object target, Object[] args, Boolean[] byrefModifiers, Int32 culture, String[] namedParameters)
   at System.RuntimeType.InvokeMember(String name, BindingFlags bindingFlags, Binder binder, Object target, Object[] providedArgs, ParameterModifier[] modifiers, CultureInfo culture, String[] namedParams)
   at System.Type.InvokeMember(String name, BindingFlags invokeAttr, Binder binder, Object target, Object[] args)
   at Titanium.Web.Proxy.Network.Certificate.WinCertificateMaker.MakeCertificate(Boolean isRoot, String subject, String fullSubject, Int32 privateKeyLength, String hashAlg, DateTime validFrom, DateTime validTo, X509Certificate2 signingCertificate)
ERROR2018-03-07 13:17:53 - 
ERROR2018-03-07 13:17:53 - WinCertificateMaker -> MakeCertificate2() : CertEnroll::CX509Enrollment::CreatePFX: The requested property value is empty. 0x80094004 (-2146877436)
ERROR2018-03-07 13:17:53 - Stack Strace :: 
```
The Exception has come on following line 

`string empty = (string)typeX509Enrollment.InvokeMember("CreatePFX", BindingFlags.InvokeMethod, null, x509Enrollment, typeValue);`

This only happens on Windows Vista. Can you please help?

**Comment by honfika** [comment]
A workaround could be to use BouncyCastle certifiate engine. Is it enough for you?

**Comment by harrip12** [comment]
I used BouncyCastle certifiate engine, It is creating Cert.
But the problem is I am not able to browse internet on Firefox.
It is giving me following error:
     "Your connection is not secure"

**Comment by justcoding121** [comment]
We are not expecting to support everyplatform for Firefox. The feature to import certificate to firefox was created for convinience, and it has nothing to do with proxy itself. Since the root certificate is generate, you would need to figure out a way to import root certificate to firefox in vista. See wiki.

**Comment by honfika** [comment]
You can exprot the certificate with the follwoing code:
`File.WriteAllBytes("rootCert.cer", proxyServer.CertificateManager.RootCertificate.Export(X509ContentType.Cert));`

Then import it to Firefox as it is written in Fiddler's documenation:
https://docs.telerik.com/fiddler/Configure-Fiddler/Tasks/FirefoxHTTPS

Check issue: https://github.com/justcoding121/Titanium-Web-Proxy/issues/606

Alternatively you can enable security.enterprise_roots.enabled in Firefox (google it)
