### ISSUE TITLE
what is the equivalent of Task.FromResult() in .NET 3.5

### ISSUE THREAD

**Issue by surendharb** [justcoding121/Titanium-Web-Proxy#382]
I'm working in .NET 3.5 framework environment, I cannot able to user Task.FromResult(0).
Is there any replacement for Task.FromResult(0).

        public Task OnCertificateValidation(object sender, CertificateValidationEventArgs e)
        {

            e.IsValid = true;

            return Task.FromResult(0);
        }

**Comment by honfika** [comment]
Are you able to use TWP from .NET 3.5? all of the methods are async and it needs .NET 4.5+
