### ISSUE TITLE
Graceful Proxy shutdown

### ISSUE THREAD

**Issue by surendharb** [justcoding121/Titanium-Web-Proxy#384]
I have a scenario in which the user kills the client application from the task manager, at this point the proxy does not turn off as the client application is not active. Is there a way in which I can gracefully switch off the proxy when the client application is killed through the task manager?

Note: Proxy is active when the client application is running, When user kills the client application the access to internet is lost until the proxy switch in the settings is switched off manually by the user.

**Comment by honfika** [comment]
You need another program which monitors the proxy, since if you kill an application, it can't do anything:)

**Comment by surendharb** [comment]
Thanks @honfika  for the answer. I'll create new Windows Service to shutdown the proxy.
