### ISSUE TITLE
 CONNECT processing

### ISSUE THREAD

**Issue by obbana2** [justcoding121/Titanium-Web-Proxy#385]
Good afternoon. I use your proxy for my needs, I change it. Any proxoficator redirecting requests to the HTTPS proxy, wraps HTTP in CONNECT. Titanium does not see this and processes the request as CONNECT, I changed the code if I see that the first part of the body after CONNECT is HTTP, I send a request to the handler as a TRANSPARENT request and it works. It looks sad, but it works.

**Comment by obbana2** [comment]
I would also like to have a function to intercept the data without holding BODY - it is desirable to have separate Callback calls. To prevent large files from being loaded into RAM.

**Comment by honfika** [comment]
"To prevent large files from being loaded into RAM.":
By default it works in this way, the body only streamet to the client.

Do you call this methods?
```
await e.GetRequestBody();
or 
await e.GetRequestBodyAsString();

```

**Comment by obbana2** [comment]
Yes, I use these functions. Content-Size is not always present, Content-Type is not always present, and sometimes it is erroneous. content can be chunked. In this case, it would be nice to be able to specify the maximum size of the body that would be clipped when writing to the cache. I'm testing the proxy at a load of about 700,000 http requests per day. Https I can not and do not want to decrypt, but the decryption disabling features also do not? And I do not remember being too lazy to re-read the code, if SetRequestBody and SetRequestBodyAsString are re-compressed, if they were compressed? headers gzip after all remain.

**Comment by obbana2** [comment]
I try to get only html and javascript, but it does not always work correctly, I'm looking at the content-type or the end of the .html .js path. In the end, something hangs after about 10-15 minutes of work and I can not understand anything, since there are no exceptions and there is no VisualStudio on the server, and detailed logs would strongly slow down the proxy. In addition, I use the example with WPF as a basis, I probably have to disable the output of sessions on the screen, it turns out that synchronization and it slows down.

**Comment by obbana2** [comment]
Still (maybe it seems to me) you should not use await everywhere, somewhere you can send data asynchronously without waiting, just sending the data where to go, because the connection then waits for the reactions? I hope you will not judge an amateur novice.

**Comment by honfika** [comment]
What cache do you mean? We are not caching the body. Unless you set the 
`SessionEventArgs.WebSession.Response.KeepBody`
property to true, but it is false by default. (WPF example sets it, so if you used that as a sample, them probably you only need to remove that setting.)

GetRequestBody/AsString reads the complete body to the memory, but it is there only until the session is not finished (so basically until the response is sent to the client). It is mandatory, we should store it since it is needed to send it to the client. Unless you replace it with a new body, but in this case it will be unavailable at the moment when you replace it.

Why do you need the body? If you don't call this method, the body will be streamed without loading it to the memory.

Yes, it is compressing the body according to the header value.

**Comment by obbana2** [comment]
I insert a small page in the page (on top) about using my proxy and micro advertisement.
It happens that the content type html - but the file is binary, it turns out a lot of information gets into RAM, if this file is 5GB, will it crash?

**Comment by obbana2** [comment]
found an error in the develop branch, or rather it is an error in the CustomBinaryReader. Incorrect end-of-line processing, which is often wrong. Why could not I use the standard parent methods Stream.ReadLineAsync?

![screen](https://user-images.githubusercontent.com/27685343/37825956-b7b0d020-2ea2-11e8-9948-29d82ec07881.jpg)

**Comment by obbana2** [comment]
Checked, html together with chunked are found often!

**Comment by obbana2** [comment]
i replace
`//if new line
                if (lastChar == '\r' && newChar == '\n')
                {
                    return encoding.GetString(buffer, 0, bufferDataLength - 1);
                }`
on
`//if new line
                if (lastChar == '\r' && newChar == '\n')
                {
                    return encoding.GetString(buffer, 0, bufferDataLength - 1);
                }

                //if new line ends with '\n'
                if (newChar == '\n')
                {
                    return encoding.GetString(buffer, 0, bufferDataLength);
                }`
in CustomBinaryReader and this worked...

**Comment by honfika** [comment]
Thanks, fixed in the latest beta package. We can't use the standard `ReadLineAsync`. because the object called `stream` is not (always) a .NET `Stream` object.

**Comment by honfika** [comment]
So how can I help you with the chunked problem?

**Comment by obbana2** [comment]
the question is settled.

**Comment by justcoding121** [comment]
The user may want to access the stream directly to save large files to somewhere in file system or database, and then stream it again without loading full file to RAM. So one day soon we can perhaps add a new method to expose those respective streams. Something like 

```
//gets a wrapper stream to server 
//if request is chunked the wrapper stream will parse the chunks
//will throw exception if tried to access after request to server is finished
var serverStream = e.GetRequestBodyStream();
var read = 0;
while ((read = await serverStream.ReadAsync(buffer, 0, buffer.Length)) > 0)
{
 someUserStream.Write(buffer, 0, read);
}

//gets a wrapper stream to client
//if response is chunked the wrapper stream will encode the chunks
//will throw exception if tried to access this before request to server is finished
var clientStream = e.GetResponseBodyStream();
var read = 0;
while ((read = await  someUserStream.ReadAsync(buffer, 0, buffer.Length)) > 0)
{
 clientStream.WriteAsync(buffer, 0, read);
}
```


If the body is already read/send then this should throw exceptions. If the request/response is chunked then we should take care of it inside the methods. The user should be aware of the risks of directly using these streams.

**Comment by honfika** [comment]
Something similar is already possible with the DataReceived/DataSent events. It was not called in this case, but some miites ago I added it.

There are 2 problems with this (and it is true for your idea,too):
- it is read only, so the users can't modify the response (e.g: add an advertisement)
- when the body is compressed, the events/stream returns the compressed data

**Comment by justcoding121** [comment]
I think we can compress/decompress inside our wrapper stream using the header values for compression type. We can force chunked when using these new methods by updating the headers, so it wouldn't matter what the content length is. We will document this accordingly.
