### ISSUE TITLE
Redirect after reading response body

### ISSUE THREAD

**Issue by judebigj** [justcoding121/Titanium-Web-Proxy#392]
I am able to read the response body for the given request using the ResponseHandler of Titanium Proxy.
Based on the content of the response body (eg: check if the response string contains a keyword), I would like to redirect the user to a custom HTML page, similar to the way you have done in your example.

```
e.Ok("<!DOCTYPE html>" +
	      "<html><body><h1>" +
	      "Website Blocked" +
	      "</h1>" +
	      "<p>Blocked by titanium web proxy.</p>" +
	      "</body>" +
	      "</html>");
```

(However, the example redirect at Request time itself, whereas I am looking to redirect at Response time based on content of original response.)

Is it possible to achieve this? If so, can you please guide me in doing so.

**Comment by honfika** [comment]
In your case you should subscribe to the `proxyServer.BeforeResponse` and set the response headers and the body.

Maybe we can add helper methods (or make the current one to work in the response event, too) for this case, too.

**Comment by judebigj** [comment]
I tried using the `proxyServer.BeforeResponse` and clear the header and add my html page as you suggested. Instead of showing the html page, it downloads html file.

Let me also mention, that the corresponding request is a "download file request".
The response has the content of the file, which I am able to read in the BeforeResponse Handler.
So, instead of downloading the file, I would like to redirect the user to the custom html page(depending on the body content).

So for example, if I download "abc.txt" from the website, I get the response body in the BeforeResponse handler. I replace the body with my custom html script, clear the headers and add my own headers.
The result of this handler is I don't get the new custom page in my browser, instead the file named
"abc.txt" is still downloaded, but when I open the file I see the custom html script.

**Comment by honfika** [comment]
Copy you plese copy your code here? If you replace the body and the browser gets the original, then it is a bug in TWP. It can't be happen.

did you call the the 
`var bodyBytes = await e.GetResponseBody();`
before you set the body with
`await e.SetResponseBody(bodyBytes);`
?

**Comment by honfika** [comment]
Please try the following with the latest beta (3.0.379 or newer):

```
            var ext = System.IO.Path.GetExtension(e.WebSession.Request.RequestUri.AbsolutePath);

            if (ext == ".gif" || ext == ".png" || ext == ".jpg")
            {
                byte[] btBody = Encoding.UTF8.GetBytes("<!DOCTYPE html>" +
                                                       "<html><body><h1>" +
                                                       "Image is blocked" +
                                                       "</h1>" +
                                                       "<p>Blocked by Titanium</p>" +
                                                       "</body>" +
                                                       "</html>");

                var response = new OkResponse(btBody);
                response.HttpVersion = e.WebSession.Request.HttpVersion;

                e.Respond(response);
                e.TerminateServerConnection();
            }

```

**Comment by honfika** [comment]
I close this issue due to inactivity. Feel free to reopen if needed.
