### ISSUE TITLE
Concurrency issues with WinAuth

### ISSUE THREAD

**Issue by bjowes** [justcoding121/Titanium-Web-Proxy#394]
I have experienced concurrency issues between requests when using WinAuth. I managed to track it down to the ResponseHandler. 
With WinAuth, the 401 response is passsed to WinAuthHandler, which updates and resends the request. However, ResponseHandler then continues with processing of the response. In some cases, this caused a 401 to be returned back to the client.

My suggestion to fix this is to let WinAuth set the ReRequest flag when the request is resent to the server, that way the response handling is terminated correctly.

I have a local implementation with this fix, I will create a PR if the suggestion is accepted.

**Comment by honfika** [comment]
For me it is ok, please create PR for both (#393) issues.
