### ISSUE TITLE
Clarify what does ProxyEndPoint.EnableSsl means

### ISSUE THREAD

**Issue by honfika** [justcoding121/Titanium-Web-Proxy#402]
Currently it is not possible to set TWP as a system proxy for HTTPS if the endpoint.EnableSsl is false, because of this check:
https://github.com/justcoding121/Titanium-Web-Proxy/blob/930a82bfb1d5fe20382be3f86275876149c245e1/Titanium.Web.Proxy/ProxyServer.cs#L322-L325

What does this property exactly means? EnableSsl decrytption? In this case I think it should be allowed to set the HTTPS proxy, just do not decrypt the traffic.

If this property is not about the decryption, then is is just for blocking the uesr to set TWP as a HTTPS proxy, which is quite useless.

So is suggest to remove the check which throws exception in the `SetAsSystemProxy` method.

**Comment by justcoding121** [comment]
If I recall right it was to tunnel Https requests.

**Comment by honfika** [comment]
So if it is false we should close the client connection when it contains a tunnel connect? Not just simply forwarding without decrypting that?

**Comment by justcoding121** [comment]
We should be forwarding the tunnel connect. I think the property do not make sense in TransparentEndPoint. So we should be moving it to ExplicitEndPoint from ProxyEndPoint.

**Comment by justcoding121** [comment]
And perhaps rename it to TunnelHttps or something.

**Comment by justcoding121** [comment]
I renamed it.

**Comment by honfika** [comment]
Thank you.. sorry, I was a little bit busy in the week.
Why is it useless in transparent mode? It can be also decrypted or forwarded without decription.

**Comment by justcoding121** [comment]
No worries. You are right. We can use servername indication to find the host to connect. But if SNI hostname is not present then we can't forward it since we wont be knowing the server. You can implement this when you get time.
