### ISSUE TITLE
How can I configure Titanium Web Proxy to not use a self-signed certificate?

### ISSUE THREAD

**Issue by Luke03** [justcoding121/Titanium-Web-Proxy#407]
Hi,
I want to setup Titanium Web Proxy to NOT use  a self-signed certificate. My goal is to install Titanium Web Proxy on a server and allow clients to access TLS encrypted websites through the proxy without installing the titanium web proxy root certificate on their local machine. Is this possible?

Thank you!

**Comment by bjowes** [comment]
You can specify a custom root certificate with `proxyServer.CertificateManager.RootCertificate`
If the certificate has a password, specify it with `proxyServer.CertificateManager.PfxPassword`

See the CertificateManager class for additional options.

**Comment by bjowes** [comment]
Keep in mind that the root cert you specify still must be trusted by the clients.

**Comment by Luke03** [comment]
That's not what I am looking for. I don't want that the clients have to install any certificate. The proxy should just "forward" the certificate delivered by the website. I have another proxy software which does this by default, so I think this shouldn't be a big problem? Of course I can't decrypt/sniff the traffic in this case, but that's nothing I want to do anyway.

**Comment by bjowes** [comment]
I see. I believe that you can use the Excluded flag for this. Look for the example of `OnBeforeTunnelConnectRequest` in Readme.md. I haven't used it myself but from the documentation it seems to de what you are looking for.
And, just curious - what are you using the proxy for? I think the main use case for this library is when you need to intercept/modify specific requests or responses.

**Comment by justcoding121** [comment]
You can use `Excluded` for individual requests or set `endPoint.DecryptSsl` to false for all requests.

**Comment by justcoding121** [comment]
I think it would be better to rename `Excluded` to `DecryptSsl` as well. This would be more readable. @honfika What do you think?

**Comment by justcoding121** [comment]
We need to find a suitable automatic api documentation generator like docfx.
https://dotnet.github.io/docfx/

This will help to provide documentation of our Api in GitHub/Github.io with continuous integration. I tried to use their nuget package to generate the API documentation files but it seems not working as they claim.

**Comment by honfika** [comment]
Ok, I renamed it

**Comment by honfika** [comment]
I close this issue due to inactivity. Feel free to reopen if needed.
