### ISSUE TITLE
Use Ok To cancel request doesn't work

### ISSUE THREAD

**Issue by PejmanNik** [justcoding121/Titanium-Web-Proxy#408]
Hi
I use last beta version (3.0.398-beta). I use ExplicitProxyEndPoint with `(decryptSsl = flase)`
Now I need block or cancel request from the requset hostname. so i use `explicitEndPoint.BeforeTunnelConnectRequest`
and :
```c#
private async Task ExplicitEndPoint_BeforeTunnelConnectRequest(object sender, Titanium.Web.Proxy.EventArguments.TunnelConnectSessionEventArgs e)
{
    string hostname = e.WebSession.Request.RequestUri.Host;
     if (hostname != "google.com")
     {
         e.Ok("Blocked");
   }
 }
```

but this code has no effect and all request just send :(

**Comment by honfika** [comment]
This Ok (and other similar Respond) method should be called from the BeforeRequest (or BeforeResponse) events, not from the TunnelConnect event.

I think those methods should not be available in that event, or at least they should throw and exception. Currently there is not way to block the connect. I'll try to implement something.

**Comment by PejmanNik** [comment]
Thanks a lot 👍 
I test BeforeRequest but when `decryptSsl = false` this event never called

**Comment by PejmanNik** [comment]
I just clone project and test it, It is ok. but with last nuget version (3.0.398-beta) this event never called

**Comment by justcoding121** [comment]
It will never get called if decryptSsl is false. If you don't decrypt then you cannot block the website with a message. You can terminate the request abruptly without any message by implementing `proxyServer.AuthenticateUserFunc` event handler by returning `false`.

https://github.com/justcoding121/Titanium-Web-Proxy/blob/develop/Titanium.Web.Proxy/ProxyServer.cs#L211

@honfika I think we should add one more property inside `BeforeTunnelConnectRequest` that would let users to terminate the connection with a negative connect response like what we do with `proxyServer.AuthenticateUserFunc`

**Comment by PejmanNik** [comment]
@justcoding121 Thank you. I think we can access the host address even with SSL enabled and maybe other things like request size (limit user bandwidth) and so on...
I try this event but I need filter request by host address this function provide username and password.

So there is not any solution to filter client request by host address when decryptSsl is false?

**Comment by justcoding121** [comment]
If you don't decrypt the only detail available will be the host address of server. Limiting bandwidth is not supported, you can however write code to keep track of how much data a client sent/received using `TunnelConnectEventArgs.DataSent/DataReceived` events when decryptSsl is enabled and by keeping track of client Ip address from `TunnelConnectEventArgs.ClientEndPoint`. @honfika Not sure how reliable these events are, I would think it gets fired on all data whether relayed or decrypted.

> So there is not any solution to filter client request by host address when decryptSsl is false?

By filter if you mean deny/drop client connection, we don't support this yet. We will support this one we implement `BlockConnect`.

**Comment by PejmanNik** [comment]
Yes, you are right. Thank you.
I just mentioned an example (Limiting bandwidth) for how can this event be useful.

Ok, thanks. Can I help? Suggestion to PR?

**Comment by honfika** [comment]
In the latest beta package you can block a conection in the `BeforeTunnenConnectRequest` event with:

```
            if (hostname.Contains("google"))
            {
                e.BlockConnect = true;
            }

```

It sends:
https://github.com/justcoding121/Titanium-Web-Proxy/blob/26d815c31609b6ba68353bcae373298308698741/Titanium.Web.Proxy/RequestHandler.cs#L88-L93

I don't know what is the correct reponse status code,  but it works in Chrome. Maybe it will be configurable later.

**Comment by PejmanNik** [comment]
@honfika Thank you so much this is great.

**Comment by justcoding121** [comment]
Fyi. Albeit my suggestion `BlockConnect` sounds little strong, I just renamed it to `DenyConnect` for future releases.

**Comment by GF-Huang** [comment]
Same issue in `BeforeRequest`

![image](https://user-images.githubusercontent.com/4510984/101465384-d65acb80-397a-11eb-871f-f7805a17203c.png)

![image](https://user-images.githubusercontent.com/4510984/101465474-f2f70380-397a-11eb-948c-15f892b4edce.png)

**Comment by GF-Huang** [comment]
I found that the same request will trigger `BeforeRequest` twice.
