### ISSUE TITLE
CertificateManager exceptionFunc bug

### ISSUE THREAD

**Issue by jgilbert2017** [justcoding121/Titanium-Web-Proxy#423]
`ProxyServer.ExceptionFunc` setter should also update the `CertificateManager exceptionFunc`

**Comment by justcoding121** [comment]
Thanks for bringing out bunch of good issues we probably overlooked.

**Comment by jgilbert2017** [comment]
thank you for taking the feedback in stride and not getting pissed at me :-)!

(btw- i haven't even run the code yet... was just doing a review before i committed to see what the guts look like.  i'm sure i'll have more for you later on! hahaha).

**Comment by justcoding121** [comment]
I don't think this is a problem. 

https://github.com/justcoding121/Titanium-Web-Proxy/blob/master/Titanium.Web.Proxy/ProxyServer.cs#L107

We are passing in the [ExceptionFunc](https://github.com/justcoding121/Titanium-Web-Proxy/blob/master/Titanium.Web.Proxy/ProxyServer.cs#L221) property to `CertificateManager` which has a backing field. So if you update `proxyServer.ExceptionFunc` it would immediately refelected in `CertificateManager`.

**Comment by jgilbert2017** [comment]
@justcoding121 if you want it to work like that you need `CertificateManager` to take `Func<ExceptionFunc>` otherwise it is only evaluated once.  Just ran in debugger to make sure I am not crazy and confirmed that it is in fact an issue.

**Comment by justcoding121** [comment]
Okay. You can create a PR when you get a chance if possible.
