### ISSUE TITLE
race condition in ProxyServer.Start()

### ISSUE THREAD

**Issue by jgilbert2017** [justcoding121/Titanium-Web-Proxy#424]
```
            foreach (var endPoint in ProxyEndPoints)
            {
                Listen(endPoint);
            }

            CertificateManager.ClearIdleCertificates();

            if (RunTime.IsWindows && !RunTime.IsRunningOnMono)
            {
                WinAuthEndPoint.ClearIdleStates(2);
            }

```

should probably change to doing the `Listen` call last especially b/c there is a `Task.Delay` loop in the `Clear*()` functions.

```
            CertificateManager.ClearIdleCertificates();

            if (RunTime.IsWindows && !RunTime.IsRunningOnMono)
            {
                WinAuthEndPoint.ClearIdleStates(2);
            }

            foreach (var endPoint in ProxyEndPoints)
            {
                Listen(endPoint);
            }

```

**Comment by honfika** [comment]
@jgilbert2017 BTW, you can come to our gitter
And create pull requests for the issues you submitted:)

**Comment by jgilbert2017** [comment]
@honfika what is/where is your gitter?  I can do pull requests, just wanted to make sure you'd be receptive.  I may take a stab at some major work with the networking streams but I noticed you're working on it on the dev branch.  The current buffering is highly inefficient.  Should I hold off?

**Comment by honfika** [comment]
gitter: https://gitter.im/Titanium-Web-Proxy/Lobby

I was working on the streams recently, but i finished that. So you can check it:)
Currently I'm working on HTTP/2 support

**Comment by honfika** [comment]
Fixed, but the ClearIdleStates was removed because of the RequestId issue.
The WinAuth state is stored in an internal data property of the websession object, so the cleaner thead is not required anymore.

**Comment by justcoding121** [comment]
Please reopen if any issue arise.
