### ISSUE TITLE
Proxy incorrectly relays compressed body

### ISSUE THREAD

**Issue by jgilbert2017** [justcoding121/Titanium-Web-Proxy#428]
I'm testing via `wget --no-check-certificate -e use_proxy=yes -e http_proxy=127.0.0.1:8000 http://www.google.com`.

The request header includes `Accept-Encoding: identity` which is to say the client can't (or won't) process any encoding transformation.

Code in `RequestHandler` adds gzip and deflate encodings on the request, but the proxy does not seem to decode the body before passing it back to the client.  As a result, `wget` saves the compressed contents rather than the html as we'd want.

```
        private void PrepareRequestHeaders(HeaderCollection requestHeaders)
        {
            if (requestHeaders.HeaderExists(KnownHeaders.AcceptEncoding))
            {
                requestHeaders.SetOrAddHeaderValue(KnownHeaders.AcceptEncoding, "gzip,deflate");
            }

            requestHeaders.FixProxyHeaders();
        }
```

I don't quite understand why this code exists.  

Interested in what you guys think the proper fix is.

**Comment by justcoding121** [comment]
The code here rewrites compression headers of request before sending to server, informing that we only accept these two specific types of compression. This is because we don't have any other decompression supported in our proxy other than these two. 

The client will received the compressed body from server as it is, with the response headers mentioning the compression used by server based on the options we gave through request. 

I see the problem here. The client mentioned that it cannot accept a compressed response. So we should not override that in this particular case. 

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Encoding

**Comment by jgilbert2017** [comment]
Yeah.  The problem is that the client gets to choose what set of encodings it supports.

If the client doesn't include any encodings that the proxy understands then the proxy can't really alter the body, can it!

**Comment by justcoding121** [comment]
The proxy can, by instructing the server that we only accept identity (no compression at all).

i.e, If the client sends accept-encoding that are all not understood by proxy, then we should certainly overwrite it `accept-encoding:identity`  before we sent it to server. In fact we should add "gzip,deflate, indentity"  for all requests in above snippet you added.

**Comment by jgilbert2017** [comment]
I'm not quite following you- for example
Client: `Accept-Encoding: SomethingProxyDoesntKnow`

As I see it, the proxy has 2 options:
1. do opaque pass through to the server.
2. reject the request

If the proxy alters the `Accept-Encoding` it will not be able to re-encode the response to the client.

**Comment by justcoding121** [comment]
> If the proxy alters the Accept-Encoding it will not be able to re-encode the response to the client.

It will be able to sent the client the body uncompressed with `Content-Encoding:identity`. In fact when we overwite `Accept-Encoding: SomethingProxyDoesntKnow` to `Accept-Encoding: identity`, server have no option to pick. It will return the result uncompressed with header `Content-Encoding:identity`

**Comment by jgilbert2017** [comment]
ah, ok- got it.  so really the proxy needs to _strip_ unknown encodings from `Accept-Encoding` to make sure it doesn't receive a response it can't handle.

perhaps that should only happen if the api client is interested in handling that particular request.

**Comment by justcoding121** [comment]
Yes. We don't read the body to memory unless API user requested it (we relay it directly to client). But we do overwrite the header in all cases currently.

**Comment by justcoding121** [comment]
This should be fixed now.

**Comment by justcoding121** [comment]
Reopen if any issue arise.

**Comment by jgilbert2017** [comment]
@justcoding121 Did you add code to strip the encoding if the client doesn't support gzip/deflate?  I didn't see that in the commit.

**Comment by justcoding121** [comment]
Yes. Correct me if the logic in referenced commit above is wrong.

**Comment by jgilbert2017** [comment]
hmm.... i'm not seeing the logic.  i see changes to RequestHandler.PrepareRequestHeaders to add gzip/deflate but i don't see any patches that strip the compression on the way back to the client if they don't support it.  what file/line should i be looking at?

**Comment by justcoding121** [comment]
Why do we need to strip headers on response? We let server know that we only support compressions that are both supported by client and proxy. Server will only pick from the choices we sent. Otherwise its a protocol violation on server side.

**Comment by jgilbert2017** [comment]
ah ok, my bad on that.  now that i understand- perhaps "identity" should be in the HashSet with deflate/gzip.  Otherwise I think you add it twice if the client sends it.

**Comment by justcoding121** [comment]
No problem. Notice that I did not implement the efficient solution discussed above, which is little bit more complicated. But this would fix the bug, which was the priority. Enhancements are welcome in future.
