### ISSUE TITLE
GetResponseBodyAsString() causes an exception

### ISSUE THREAD

**Issue by sirstaho** [justcoding121/Titanium-Web-Proxy#439]
I cannot read the response body. Every time I try I get an exception that array exceeds maximum array size in Titanium.Web.Proxy.Helpers.HttpWriter..ctor(System.IO.Stream, StreamExtended.IBufferPool, Int32).
I am using the code from examples (basic and wpf).

**Comment by justcoding121** [comment]
Thanks for bringing this out. I broke this in recent change with buffer pool. Fixed in latest beta.
