### ISSUE TITLE
how to remove the warning "Your connection is not private".

### ISSUE THREAD

**Issue by askerzhang** [justcoding121/Titanium-Web-Proxy#44]
Hi, I tried to build the titanium proxy server in a remote machine A. And I set the proxy server as A:8000 on my laptop B. when it goes to https website like google, youtube. the chrome always show the warning "Your connection is not private", IE has similar warning.
How can we make the browse don't show this warning?

**Comment by justcoding121** [comment]
This is because machine B don't trust self signed certificates issued by machine A. To resolve this you need to install the root certificate we use to sign HTTPS websites in to machine B. If you haven't created any custom root certificates, this would simply mean you would need to install Titanium_Proxy_Test_Root.cer in to machine B as a root certificate. (simple copy it to machine B and follow the install wizard)

Alternatively create an intermediate certificate signed by the root certificate in machine A, and install it in machine B. This is the recommended approach if you are using this in production, since we don't want to

**Comment by mszhanyi** [comment]
Thank your reply. Titanium_Proxy_Test_Root.cer  doesn't work. I did it by export the certificate  "Titanium Root Certificate Authority" from A and import it into B's Trusted Root Certification Authorities.

**Comment by askerzhang** [comment]
Thank your reply. 'Titanium_Proxy_Test_Root.cer' doesn't work. I did it by export the 'Titanium Root Certificate Authority' from Server and import it ino client's 'trusted Root Certification Authorites'.

**Comment by justcoding121** [comment]
Hmm. can you please clarify if you added it under current user store and not under local computer store. You could use certmgr.msc from run command. Thanks for reporting.
![capture](https://cloud.githubusercontent.com/assets/2637679/13417328/a897062e-df38-11e5-9f44-587970deb4da.PNG)

**Comment by justcoding121** [comment]
Also if you are using firefox, you would need to import the certificate in to firefox certificate store. Because firefox have its own certificate store it looks at, and it doesn't respect windows certificate store.

**Comment by askerzhang** [comment]
Yes, it is in Current User, not Local Computer. 
I'm using Chrome. 
The detail warning info was below and I found the similar certificate and imported it in client's browser.
I used certmgr.exe to import.

> Attackers might be trying to steal your information from www.google.com (for example, passwords, messages, or credit cards). NET::ERR_CERT_AUTHORITY_INVALID
> Subject: www.google.com
> Issuer: Titanium Root Certificate Authority
> Expires on: Feb 3, 2026
> Current date: Mar 1, 2016

**Comment by justcoding121** [comment]
Okay. I had the same issue. I fixed it by importing the exported root certificate both to **Personal** & Root store of current user, not just the root store.

And actually the  'Titanium_Proxy_Test_Root.cer' have no meaning, one the changes in past made the proxy to generate root certificates on fly. I will remove it in next release.

**Comment by kissxrl** [comment]
Android  How to install the certificate file  .  This file is stored there.

**Comment by justcoding121** [comment]
I am not familiar with how android do certificate import. You should be able to do an import as mentioned above for windows.

[This link may help.](http://docs.telerik.com/fiddler/Configure-Fiddler/Tasks/ConfigureForAndroid)

**Comment by tonyjoker** [comment]
In past few weeks, I have faced the same issues like you. I thought it was an error from the app or wrong code. But the fault came from my computer when my antivirus software has blocked SSL connection. I have turned off it and it's worked. Check it out, this may help you to resolve it, [a guide to fix Your Connection Is Not Private](https://usefulpcguide.com/16666/your-connection-is-not-private/).

**Comment by parxal** [comment]
Hello, i'm using the last version (15/11/2016) and i have the same problem, i installed rootCert.pfx booth for local computer and current user. I am running the proxy inside a windows service. Any toughs ? thank you
