### ISSUE TITLE
Support for .Net Framework 4.0?

### ISSUE THREAD

**Issue by hychoo** [justcoding121/Titanium-Web-Proxy#451]
I try to downgrade the project to .Net Framework 4.0 but stuck on the Nuget package StreamExtended as the package only support .Net Framework 4.5 and above.

Is there any workaround as my application need to support Windows XP.

**Comment by justcoding121** [comment]
See https://github.com/justcoding121/Titanium-Web-Proxy/issues/378. We do not support 4.0.
