### ISSUE TITLE
External Proxy, one question?

### ISSUE THREAD

**Issue by sadux** [justcoding121/Titanium-Web-Proxy#459]
Hi!

I have one problem and misunderstanding about external proxy.
I got on my machine setup proxy, how i can setup titanium with this implementation?
**Request site ->My own proxy -> Titanium.Web.Proxy.Http -> Website**
Is that possible? I tried with ExplicitProxyEndPoint to listen on same port as My own proxy and nothing..
Tried with UpStreamHttpProxy and set host as my own proxy and again dont work..

Thank you very much for answer!

**Comment by sadux** [comment]
Thank you for response!

Yes, its ok on that way too.. I setup all on local machine without proxy and its work fine, i can catch resquest/response on before events etc.. but i got problem on machine when i got setup proxy, its not work.. 

How i can setup that?
Info: My own proxy is 10.3.1.109 and port is 3128

Do i need to use UpStreamHttpProxy?

Here is my code its work good without proxy
 `_proxyServer = new ProxyServer();
var explicitEndPoint = new ExplicitProxyEndPoint(IPAddress.Any, 18882, true);
_proxyServer.AddEndPoint(explicitEndPoint);
 _proxyServer.Start();
 _proxyServer.BeforeResponse += OnResponseCaptureTrafficEventHandler;`

**Comment by sadux** [comment]
Thank you for response!

So in this case Request site ->Titanium.Web.Proxy.Http -> My own proxy -> Website 
UpStreamHttpProxy host will be addess from my "own proxy"?

How to setup that? I tried and cant work..

**Comment by honfika** [comment]
`proxyServer.UpStreamHttpProxy = new ExternalProxy { HostName = "10.3.1.109", Port = 3128 };`

Is it working without your "own proxy"?

**Comment by sadux** [comment]
Its not working on machine without proxy and not working on machine that setup proxy too when i set like that..
I join titanium with Selenium, so for Chrome Options a must set Proxy to "10.3.1.109", Port = 3128 too..

`_proxyServer = new ProxyServer();
                
var explicitEndPoint = new ExplicitProxyEndPoint(IPAddress.Any, 3128 , true);
 _proxyServer.AddEndPoint(explicitEndPoint);
 _proxyServer.Start();
 _proxyServer.BeforeResponse += OnResponseCaptureTrafficEventHandler;

proxyServer.UpStreamHttpProxy = new ExternalProxy() { HostName = "http://localhost", Port = 18882 };
_proxyServer.UpStreamHttpsProxy = new ExternalProxy() { HostName = "http://localhost", Port = 18882 };`

**Comment by honfika** [comment]
In chrome options you shoud set the address and the port of the titanium.

**Comment by sadux** [comment]
So i first setup titanium proxy and listen on port 18882 all conections and added EndPoint.
Then i setup UpStream to 10.3.1.109 on port 3128
Then setup chrome proxy to localhost and port 18882 (titaniums)
dont work.. :(
`_proxyServer = new ProxyServer();
                var explicitEndPoint = new ExplicitProxyEndPoint(IPAddress.Any, 18882, true);
                _proxyServer.AddEndPoint(explicitEndPoint);
                _proxyServer.Start();
                _proxyServer.BeforeResponse += OnResponseCaptureTrafficEventHandler;

                _proxyServer.UpStreamHttpProxy = new ExternalProxy() { HostName = "10.3.1.109", Port = 3128 };
                _proxyServer.UpStreamHttpsProxy = new ExternalProxy() { HostName = "10.3.1.109", Port = 3128 };

var proxy = new Proxy
{
   HttpProxy = "http://localhost:18882",
   SslProxy = "http://localhost:18882",
   FtpProxy = "http://localhost:18882"
};
 chromeOptions.Proxy = proxy;
`

**Comment by honfika** [comment]
Could you please define what does "dont work.. :(" mean?
- The websites are not loaded?
or
- Breakpoint on `OnResponseCaptureTrafficEventHandler` is not hit.
or?

Is it working without titanium?
Request site ->My own proxy -> Website

**Comment by sadux** [comment]
Web site not loaded - *Waiting for proxy tunnel.. (Chrome)
No breakpoint on OnResponseCaptureTrafficEventHandler.

without titanium all work fine.. Regulary..

**Comment by sadux** [comment]
When i change port number its no status bar message Chrome *Waiting for proxy tunnel..  just dont open page..
Tell me just is this code should work properly? Maybe i got problem with some permisson on machine or something..

**Comment by honfika** [comment]
For me it seems to be ok. Maybe you can try to add an exception handler:
```
            _proxyServer.ExceptionFunc = async exception =>
            {
                        if (exception is ProxyHttpException phex)
                        {
                            // or log it to file/anywhere
                            Console.WriteLine(exception.Message + ": " + phex.InnerException?.Message);
                        }
                        else
                        {
                            Console.WriteLine(exception.Message);
                        }
            };

```

**Comment by sadux** [comment]
Ok.
Thank you very much for support!
