### ISSUE TITLE
HTTPS Proxy causes ERR_NETWORK_CHANGED on macOS .NET Core

### ISSUE THREAD

**Issue by kfreezen** [justcoding121/Titanium-Web-Proxy#462]
Hi,

I would like to try using Titanium-Web-Proxy for a content filter that I'm currently porting to macOS.

I'm running into various issues with SSL filtering on macOS that I'm not running into on Windows.

The first thing I tried was just bolting the proxy directly into my macOS port of our filter. That got me an ERR_CONNECTION_RESET on all connections (as I mentioned on gitter).

Today, I decided to create a test project to see if the proxy works on macOS. The proxy works flawlessly on Windows, but on Mac, it complains about ERR_NETWORK_CHANGED on the HTTPS proxy. (HTTP proxy seems to be fine)

The test project is at https://github.com/kfreezen/TitaniumWebProxyTest if you want to check it out.

Do you have any ideas on what could cause this?

**Comment by kfreezen** [comment]
I cloned the latest release (3.0.613) rather than using the nuget package, and things have started working.

I'm going to try building a SystemProxyManager() for macOS.

**Comment by justcoding121** [comment]
I am closing this since you reported its working.
