### ISSUE TITLE
RemoteEndPoint is not availbale in OnServerConnection

### ISSUE THREAD

**Issue by fabricedupre** [justcoding121/Titanium-Web-Proxy#463]
Hello,

The RemoteEndPoint is not availbale in OnServerConnectionCreate because InvokeConnectionCreateEvent is called before tcpClient.ConnectAsync:

                await proxyServer.InvokeConnectionCreateEvent(tcpClient, false);
                // If this proxy uses another external proxy then create a tunnel request for HTTP/HTTPS connections
                if (useUpstreamProxy)
                {
                    await tcpClient.ConnectAsync(externalProxy.HostName, externalProxy.Port);
                }
                else
                {
                    await tcpClient.ConnectAsync(remoteHostName, remotePort);
                }

Is there any reason why we could not call it after ?

**Comment by justcoding121** [comment]
Should be fixed in latest beta
