### ISSUE TITLE
Performance issues on macOS

### ISSUE THREAD

**Issue by kfreezen** [justcoding121/Titanium-Web-Proxy#466]
I'm currently having performance issues on .NET Core 2.1 on macOS.

There are no good profiling tools for .NET Core/macOS that I can find, but it appears that the problem goes all the way down to `System.Net.NetworkStream`

I've managed to get some times on `StreamExtended.Network.CustomBufferedStream.ReadLineAsync()` They vary between a fairly normal 130ms to a rather high 3000ms. The result is that sites load extremely slowly with the proxy.

Are there any optimizations that can be made to Titanium-Web-Proxy or StreamExtended to speed it up in macOS? Maybe I can get you guys more information on the macOS performance?

If you can give me some suggestions on where else to look for performance bottlenecks too, I would appreciate that.

**Comment by kfreezen** [comment]
Some more information:

I ran my application on Linux and did some profiling with the available tools. I don't have the perf report with me right now, but it looks like a large portion of the overhead is coming from BouncyCastle. I'm not sure why yet; I'll have to do more investigating on it.

**Comment by kfreezen** [comment]
Still trying to figure this one out. You have any thoughts @justcoding121 or @honfika? I'm willing to do research on it myself if one of you could point me in the right direction.

Maybe it's that I have something configured wrong in my usage of the project, I don't know.

**Comment by justcoding121** [comment]
I personally have never run the proxy in Linux or Mac. I don't have the environment setup. Sorry I can't help on this. One thing to keep in mind is that .Net core have different CLR implementations on each OSs, so it could be that some of the async delays you mentioned have something to do with .Net core itself especially because they started supporting non-Windows OSs only few years ago. Did you try running the project in Mono on Linux or MacOs? Mono in my understanding is a different implementation of CLR.

**Comment by kfreezen** [comment]
I built our filtering solution again using your proxy, and for some reason, it starts out much faster. But then, after a little bit of internet usage, the performance drops off.

@justcoding121 does the proxy have any arbitrary socket creation limits in place? I'm wondering if that's the issue I'm having.

**Comment by justcoding121** [comment]
We haven't set any limit on socket creation. I am not sure what is exactly causing the performance degradation over time. I see a high number of TCP connections in TIME_WAIT state when looking through [TcpView](https://docs.microsoft.com/en-us/sysinternals/downloads/tcpview).

This article may be worth looking about various parameters that may need tuning with trial and error.

http://hea-www.harvard.edu/~fine/Tech/addrinuse.html

**Comment by justcoding121** [comment]
I am adding links to location of relevant code that may need tuning.

Tcp server connection
https://github.com/justcoding121/Titanium-Web-Proxy/blob/master/Titanium.Web.Proxy/Network/Tcp/TcpConnectionFactory.cs#L270

Tcp client connection 
https://github.com/justcoding121/Titanium-Web-Proxy/blob/master/Titanium.Web.Proxy/ProxyServer.cs#L679

And closing tcp connection.
https://github.com/justcoding121/Titanium-Web-Proxy/blob/master/Titanium.Web.Proxy/Extensions/TcpExtensions.cs#L25

**Comment by kfreezen** [comment]
I decided to wrap the ReadAsync [here](https://github.com/justcoding121/StreamExtended/blob/master/StreamExtended/Network/CustomBufferedStream.cs#L472) in a stopwatch. The output looks like this.

```
ReadAsync time 0ms - 8192 to read - 5 read
ReadAsync time 32ms - 8192 to read - 2335 read
ReadAsync time 24ms - 8192 to read - 279 read
ReadAsync time 132ms - 8192 to read - 1377 read
ReadAsync time 133ms - 8192 to read - 1314 read
ReadAsync time 0ms - 8192 to read - 5 read
ReadAsync time 100659ms - 8192 to read - 0 read
ReadAsync time 100660ms - 8192 to read - 0 read
ReadAsync time 26787ms - 8192 to read - 0 read
ReadAsync time 26788ms - 8192 to read - 0 read
ReadAsync time 86673ms - 8192 to read - 0 read
ReadAsync time 86673ms - 8192 to read - 0 read
ReadAsync time 86692ms - 8192 to read - 0 read
ReadAsync time 86693ms - 8192 to read - 0 read
ReadAsync time 86713ms - 8192 to read - 0 read
ReadAsync time 86708ms - 8192 to read - 0 read
```

I looked at this particular thing before and decided it wasn't the cause of the bottleneck, but could it possibly be?

It seems like the performance degradation is particularly noticeable on large sites like cnn.com and youtube.com. google.com search is very snappy, as is github navigation.

Maybe the above snippet doesn't affect small page loads, but does affect large page loads.

**Comment by justcoding121** [comment]
When you visit news sites like that they load tons of cross domain pages as part of ad services, which creates and terminates short lived tcp connections. This in turn causes a lot of connections on browser side with TIME_WAIT state. To test if its the browse that causes the delay, you can perhaps browse from another machine when you see the degradation and see if its slow. I've added couple of parameters in latest develop to adjust TCP_WAIT time and socket reuse option.

**Comment by justcoding121** [comment]
ReadAsync delay is not surprising to me. Since its reading from network stream with a buffer it will be zero at times when data is available in buffer. But when data is not available it will wait until data is available.

https://github.com/justcoding121/StreamExtended/blob/master/StreamExtended/Network/CustomBufferedStream.cs#L181

**Comment by kfreezen** [comment]
Ya, that makes sense. The commit that references this bug, [https://github.com/justcoding121/Titanium-Web-Proxy/commit/41b0c95a57d9e0d2f11e748567edcf4ba467554a]() is broken on Linux. It yields an ERR_EMPTY_RESPONSE on Google Chrome.

One thing I'm discovering as well, which should probably go into a different bug ticket, is that for some reason the following URLs are broken when running through the proxy.

[https://app.satismeter.com/satismeter.js]()
[https://www.gnu.org/software/wget/manual/html_node/Exit-Status.html]()

Do you have any diagnostics you can turn on in Titanium.Web.Proxy to see how the server request/response compares to the client request/response? Can I get that information just by using BeforeRequest / AfterResponse?

If I can't, I can build a diagnostics API and submit a PR if you're interested in that.

**Comment by justcoding121** [comment]
Can you let me know where in the referenced commit its breaking in linux?

You can create a diagnostics API, but I hope it will be written in such a way that it be creating additional delays.

**Comment by justcoding121** [comment]
I don't see any issues with the two urls you mentioned through the proxy in Windows.

**Comment by justcoding121** [comment]
I've added a basic diagnostic timer in latest commit. We can build from there with more events.

**Comment by kfreezen** [comment]
Alright. I'll take a closer look at those issues I was having with that
commit on Monday.

**Comment by kfreezen** [comment]
This is a stupid question, but are you building your test project with .NET Core/.NET Standard or .NET Full?

I've had to add a new project file in order to build the proxy for macOS and Linux because I can't figure out how to make dotnet and Visual Studio for Mac build hybrid projects.

**Comment by kfreezen** [comment]
commit 41b0c95: If I add `proxyServer.ReuseSocket = false;` to my code, the proxy starts working as before on Linux.

The only thing I can conclude currently is that Linux, Windows, and macOS all have different bugs in their socket implementations. Fun.

**Comment by justcoding121** [comment]
Okay. Disabled socket reuse for linux.

**Comment by justcoding121** [comment]
I am not sure. I am on the process of setting the environment up for linux and mac on my home server. I might get back after a week.

**Comment by justcoding121** [comment]
Below is a location for response where we check for chunked header before deciding the write format.

https://github.com/justcoding121/Titanium-Web-Proxy/blob/master/Titanium.Web.Proxy/Helpers/HttpWriter.cs#L307

**Comment by justcoding121** [comment]
https://github.com/justcoding121/Titanium-Web-Proxy/issues/151

Above isse was onefor linux we had in the past. Though it was resolved could be related if we missed it somewhere.

**Comment by honfika** [comment]
Is this issue still exits? Please try the latest package.

**Comment by honfika** [comment]
I close this issue due to inactivity, feel free to reopen/create new if needed.
