### ISSUE TITLE
Support for context aware authentication

### ISSUE THREAD

**Issue by Wintereise** [justcoding121/Titanium-Web-Proxy#467]
The current auth callback implementation only supports username / password.

It would be nice if the proxy could support "extended" authentication (perhaps via another callback) which passes in the `SessionEventArgs` object to the auth function too (same one as OnRequest/OnTunnelConnectRequest will work).

This would allow people to auth based on destination/source IPs / individual sites / current time and much more.

Thoughts @honfika / @justcoding121? Implementing it is likely quite simple and I'd be willing to contribute a patch if there's interest.

**Comment by Wintereise** [comment]
It appears https://justcoding121.github.io/Titanium-Web-Proxy/docs/api/Titanium.Web.Proxy.ProxyServer.html#ProxySchemeAuthenticateFunc could be used to achieve this?

Does anyone have any examples?

**Comment by justcoding121** [comment]
@SteveSyfuhs Would appreciate if you can help with an example. I know you contributed this method.

**Comment by justcoding121** [comment]
Added the context parameter in latest beta.

**Comment by SteveSyfuhs** [comment]
Add a method that handles the scheme and provide a list of supported scheme types;

```
proxyServer.AuthenticateSchemeFunc = AuthenticateScheme;
proxyServer.SupportedAuthenticationSchemes = new [] { "Negotiate", "yourscheme" };
```

And do whatever you want to do once you've received a token based on the provided schemes.

```
private async Task<ProxyAuthenticationContext> AuthenticateScheme(
	SessionEventArgsBase session,
	string scheme,
	string token
)
	switch (scheme.ToLowerInvariant())
	{
		case "kerberos":
		case "negotiate":
			return await Negotiate(session, token);
		case "yourscheme":
			return await ProcessYourScheme(session, token);
	}

	return ProxyAuthenticationContext.Succeeded();
}

private async Task<ProxyAuthenticationContext> ProcessYourScheme(SessionEventArgsBase session, string token)
{
	// go do whatever processing you need
	
	// if it fails
	// return new ProxyAuthenticationContext { Result = ProxyAuthenticationResult.Failed };
	
	
	// if you need to roundtrip something 
	// return new ProxyAuthenticationContext { Result = ProxyAuthenticationResult.ContinuationNeeded, Continuation = Convert.ToBase64String(tokenBytes) };
	
	// if it succeeds
	
	return new ProxyAuthenticationContext { Result = ProxyAuthenticationResult.Succeeded };
}
```
This is intended to be relatively stateless (like all web requests) so every subsequent request that occurs as part of this handshake will flow through this method until the handshake has been completed.

**Comment by Wintereise** [comment]
I believe this can be closed, explanations for both ways have been achieved.
