### ISSUE TITLE
modifed response  header   AND  request  header   ???

### ISSUE THREAD

**Issue by kissxrl** [justcoding121/Titanium-Web-Proxy#47]
```
public void OnRequest(object sender, SessionEventArgs e)
{
             //modifed request  header  AND   query   
}
public void OnResponse(object sender, SessionEventArgs e)
{
            //modifed response  header   

             e.SetResponseBodyString(modified);
}
```

**# modifed response  header   OR  modifed request  header**

**Comment by justcoding121** [comment]
I locked allowing developers to change headers, because those not aware of the ramifications could mess up the response/request.

IMO not all headers should be allowed to change for example content-length, transfer-encoding etc.

**Comment by justcoding121** [comment]
Currently on release branch. You can change pretty much anything including request URL & headers
