### ISSUE TITLE
"Titanium Root Certificate Authority" Not trusted in MAC.

### ISSUE THREAD

**Issue by SwapnilSherekar** [justcoding121/Titanium-Web-Proxy#473]
Hi, 
I am using .net core 2.0 on mac 10.13.6  with the latest beta build of Titanium-Web-Proxy.

Using the same code I have able to add your certificate in Mac keychain it installed but not trusted.
so it is possible to trust that certificate using code.
As of now used below code:-
    
     var proxyServer = new ProxyServer();
     //locally trust root certificate used by this proxy 
     proxyServer.CertificateManager.TrustRootCertificate = true;

For more details I have attached screenshot:-
![screen shot 2018-08-03 at 4 14 05 pm](https://user-images.githubusercontent.com/1716663/43638975-4f7f1d00-9738-11e8-98ef-e71d6e579a00.png)

Please help me for the same...

**Comment by kfreezen** [comment]
I've done a little research on this myself. As far as I know, there's only two ways to programmatically trust a certificate with macOS.

1) Via commandline - [see here](https://apple.stackexchange.com/questions/80623/import-certificates-into-the-system-keychain-via-the-command-line)
```
security add-trusted-cert -d -r trustRoot -k /Library/Keychains/System.keychain <certificate>
```
That seems to be the easiest way. If you don't want a password prompt coming up for that, you'll have to make sure that your app is running with elevated privileges (i.e. sudo)

2) This is a lot more complicated and requires P/Invoke + a custom objective-c library. I personally have not figured out this library. [Apple Security](https://developer.apple.com/documentation/security/certificate_key_and_trust_services)

**Comment by SwapnilSherekar** [comment]
I tried using your command,
This command requires  .cer file only and we have rootCert.pfx file.
So we converted .pfx file to .cer file by using below command:
     `openssl pkcs12 -in rootCert.pfx  -nokeys -out  rootCert.cer`
After using the below command to install and trust same certificate:
`security add-trusted-cert -d -r trustRoot -k /Library/Keychains/System.keychain rootCert.cer`.
 Certificate added and trusted successfully but still problem with titanium after proxy start it says that 'Certificate Invalid on browser page'.
So please help me add certificate at the time of proxy start using .netcore .

**Comment by honfika** [comment]
Could you please try to xprot the cer file from titanium with the following code and try that on MAC?
`
File.WriteAllBytes("rootCert.cer", proxyServer.CertificateManager.RootCertificate.Export(X509ContentType.Cert));`

**Comment by honfika** [comment]
I close this isse, feel free to reopen if needed.
