### ISSUE TITLE
APP requests

### ISSUE THREAD

**Issue by darkrole** [justcoding121/Titanium-Web-Proxy#479]
it is working perfectly to edit browser requests, is there a way of edit/intercept http requests from running applications on my system?

**Comment by justcoding121** [comment]
If the applications would respect the system proxy settings then no problem. But if they won't then we cannot force them. As Wintereise mentioned you would have to find an OS hook software that can do that.

**Comment by darkrole** [comment]
alright thank you, fiddlercore is capable of doing that?

**Comment by justcoding121** [comment]
I don't think so.
