### ISSUE TITLE
Request POST

### ISSUE THREAD

**Issue by mauriciofonseca04** [justcoding121/Titanium-Web-Proxy#48]
I am using a HttpClient client = new HttpClient ()
to create a POST to an API that is working correctly me
as without the proxy initiated returns JSON me correctly ,
when starting the proxy and launch the application ( cliente.PostAsync ) hard
a standby time and returns an exception that says a task I was canceled ,
There was one or more errors
mscorlib , I would like to know how would have to do the POST for
add the headers that I need to send .

Thanks for the collaboration

**Comment by justcoding121** [comment]
Can you provide the client side code?

**Comment by mauriciofonseca04** [comment]
using (HttpClient client = new HttpClient())
                {
                    client.BaseAddress = new Uri(Resource_Angel.BaseAdress);
                    client.DefaultRequestHeaders.Add(Resource_Angel.API_HeaderAuthorization, string.Concat("token ", csGlobal.Token.token));
                    client.DefaultRequestHeaders.Add(Resource_Angel.API_HeaderAPIID, Resource_Angel.APIID);
                    client.DefaultRequestHeaders.Add(Resource_Angel.API_HeaderChildId, csGlobal.ChildID);
                    var result = client.GetAsync(Resource_Angel.API_GetUpdateRulesDict).Result;
                    if (!result.IsSuccessStatusCode)
                    {
                        messageAPI.Code = (int)result.StatusCode;
                        messageAPI.Data = result.Content.ReadAsStringAsync().Result;
                        Status = false;
                    }
                    else
                    {
                        Status = true;
                        
                        var jsonString = result.Content.ReadAsStringAsync().Result;
                        rules = result.Content.ReadAsAsync<rules_dict>().Result;
                    }
                }

**Comment by justcoding121** [comment]
I tried to run this. But unfortunately the code is not complete. It doesn't include the headers and url.

**Comment by justcoding121** [comment]
Fixed in #64 on beta
