### ISSUE TITLE
Reading returning web page

### ISSUE THREAD

**Issue by ltsz16** [justcoding121/Titanium-Web-Proxy#481]
Is it possible to read the full contents of a web page which is being returned to the end-user before returning it to them (and then being able to make changes to the page as needed)?  I have tried GetResponseBodyAsString and GetResponseBody but neither seem to return the full html of the page.  I am able to change content of a delivered page with the information in #392, but I still can't figure a way to read the full html of the returning page.  Is this possible?

**Comment by justcoding121** [comment]
Yes you should be able too. Can you show the code you are using?

**Comment by honfika** [comment]
As @justcoding121 wrote, GetResponseBodyAsString and GetResponseBody should return the full http response.
I close this issue now, feel free to create a new one when it is not working.
