### ISSUE TITLE
Page load speed decreased with 3.0.632 version

### ISSUE THREAD

**Issue by TheXby** [justcoding121/Titanium-Web-Proxy#486]
Hello
I have webdriver auto tests and i using TitaniumProxy.
Without Titanium my tests finish in ~2 minutes
With 3.0.213 ~2 minutes
3.0.503 ~4 minutes
3.0.632 - ~14 minutes
I try to remove all proxy events and leave just startup constructor but this doesnt make changes.

`_proxyServer = new ProxyServer();
            _proxyServer.CertificateManager.TrustRootCertificate(true);
            _proxyServer.CertificateManager.SaveFakeCertificates = false;
            RequestHistory = new List<CustomUserData>();
            ResponseHistory= new List<CustomUserData>();`

`public void InitServer()
        {
            _explicitEndPoint = new ExplicitProxyEndPoint(System.Net.IPAddress.Any, 18882);
            _proxyServer.AddEndPoint(_explicitEndPoint);
            _proxyServer.Start();
            _proxyServer.SetAsSystemProxy(_explicitEndPoint, ProxyProtocolType.AllHttp);
        }`

**Comment by justcoding121** [comment]
Are you on windows machine. If so could you try changing certificate engine, I wonder if the slowness is due to recent change to use BouncyCastle as default in Windows.

`_proxyServer.CertificateManager.CertificateEngine = Network.CertificateEngine.DefaultWindows;`

**Comment by honfika** [comment]
Please try the latest beta package.

**Comment by honfika** [comment]
I close this isse, feel free to reopen if needed.
