### ISSUE TITLE
Timers for Response of a Session 

### ISSUE THREAD

**Issue by darrincherry** [justcoding121/Titanium-Web-Proxy#489]
Can Titanium add Timers data into the SessionEventArgs?

Example of how to pull that information out for a test case.
`Proxy.AfterSessionComplete += delegate (SessionEventArgs targetSession)
                {

                    var totalRequestTime = targetSession.Timers.ClientDoneResponse -
                                           targetSession.Timers.ProxyBeginRequest;

                    var clientRenderTime = targetSession.Timers.ClientDoneResponse -
                                           targetSession.Timers.ServerDoneResponse;

                    var serverProcess = targetSession.Timers.ServerBeginResponse -
                                        targetSession.Timers.ServerGotRequest;

                    var passThruNetwork = targetSession.Timers.ServerGotRequest -
                                          targetSession.Timers.ClientDoneRequest -
                                          TimeSpan.FromMilliseconds(
                                              targetSession.Timers.DNSTime + targetSession.Timers.TCPConnectTime);

                    Log.Info(
                        "Proxy: Requested resource from URL {0} Response Code: {1} Total Time: {2} Server Milliseconds: {3} Network Milliseconds: {4}",
                        targetSession.fullUrl,
                        targetSession.responseCode,
                        totalRequestTime.TotalMilliseconds,
                        Math.Abs(serverProcess.TotalMilliseconds),
                        Math.Abs(passThruNetwork.TotalMilliseconds));
                };`

**Comment by justcoding121** [comment]
We already have some timer details available inside Session.TimeLine dictionary. We can improve this in future.

https://justcoding121.github.io/Titanium-Web-Proxy/docs/api/Titanium.Web.Proxy.EventArguments.SessionEventArgsBase.html#Titanium_Web_Proxy_EventArguments_SessionEventArgsBase_TimeLine

**Comment by darrincherry** [comment]
Do you happen to have any sample code not on Git, that can show how to get to Timeline?
It says on the docs here it is in the SessionEventArgBase, but doesn't show up the SessionEventArgs or WebSession ?     I think there might just be a bug perhaps in getting access to that data.

**Comment by justcoding121** [comment]
I was able to access this from the latest master repository example project. Are you using the latest beta build.

**Comment by kfreezen** [comment]
@darrincherry 
You should be able to access it in `AfterResponse`. The available events are currently
```
args.TimeLine["Session Created"];
args.TimeLine["Request Received"];
args.TimeLine["Server Connection Created"];
args.TimeLine["Response Received"];
args.TimeLine["Response Sent"];
```

**Comment by honfika** [comment]
TimeLine currently contains  DateTime,Now values, but in some frameworks (especially older ones) it is much slower than UtcNow. (Google it, for example: https://blogs.msdn.microsoft.com/kirillosenkov/2012/01/10/datetime-utcnow-is-generally-preferable-to-datetime-now/ )

In modern frameworks it is faster, but still slower than UtcNow.

I'll change them to UtcNow to make the performace better and I think it is a better idea to store UTC values.
