### ISSUE TITLE
Exclude everything except..

### ISSUE THREAD

**Issue by marcfielding1** [justcoding121/Titanium-Web-Proxy#49]
Hiya,

I should have asked this on my previous issue regarding IP addresses so apologies i've been away!

I'd like to automatically exclude everything EXCEPT the sites I name, is this possible?

Thanks

Marc

**Comment by justcoding121** [comment]
To exclude google.com and dropbox.com from being proxied.


            //Exclude Https addresses you don't want to proxy
            //Usefull for clients that use certificate pinning
            //for example dropbox.com
            var explicitEndPoint = new ExplicitProxyEndPoint(IPAddress.Any, 8000, true){
                ExcludedHttpsHostNameRegex = new List<string>() { "google.com", "dropbox.com" }
            };

**Comment by marcfielding1** [comment]
Hiya, sorry i've been away. What I was hoping to do is exclude EVERYTHING BUT the domains i'm specify since i'm only interested in certain domains rather than all traffic?7

**Comment by marcfielding1** [comment]
Ahh i've just looked at the source, I see it works on eclusion only rather than exclude everything unless I specify, i've just forked and will see if I can implement this feature

**Comment by Tau9** [comment]
Wouldn't negated regexes work though?

**Comment by marcfielding1** [comment]
Wow, I didn't even think of that, Tau if that works you're a genius!

**Comment by justcoding121** [comment]
Dead thread for long time. Closing this.
