### ISSUE TITLE
`Content-Encoding: br` not supported

### ISSUE THREAD

**Issue by kfreezen** [justcoding121/Titanium-Web-Proxy#494]
Brotli compression is not supported by the current version of the proxy.

```
Exception: Unsupported decompression mode: br
```

I have a fix for this here https://github.com/kfreezen/Titanium-Web-Proxy/tree/add-brotli-compression

This branch is not yet ready for merging due to the fact of it requiring use of a brotli compression dll that is not currently strong-named. I just wanted to create a ticket for it so others with this problem don't waste time duplicating work.

Brotli Library being used: https://github.com/master131/BrotliSharpLib

Note that this fix is also currently Windows only.

**Comment by justcoding121** [comment]
Okay. You can create a PR whenever ready.

**Comment by justcoding121** [comment]
@kfreezen Why is that this would work only on windows? The library as I see it is published with both .Net standard and .Net 45 support.

**Comment by kfreezen** [comment]
@justcoding121 That's my mistake. I had researched other Brotli libraries that used native+P/Invoke and got them mixed up with this one. The RunTime.IsWindows check can be removed.
