### ISSUE TITLE
Sample code issue in WinForms

### ISSUE THREAD

**Issue by mattsmall1972** [justcoding121/Titanium-Web-Proxy#499]
Following this code here:
1            var proxyServer = new ProxyServer();
2            proxyServer.CertificateManager.TrustRootCertificate = true;
3            proxyServer.BeforeRequest += ProxyServer_BeforeRequest;
4            proxyServer.AfterResponse += ProxyServer_AfterResponse;

I get the error on line 2.
Cannot assign to 'TrustRootCertificate' because it is a 'method group'	

Not sure what I'm doing wrong.

**Comment by justcoding121** [comment]
Can't think of anything. Could this be due to the wrong handler name?

https://stackoverflow.com/questions/29840120/cannot-assign-to-method-because-it-is-a-method-group
