### ISSUE TITLE
Is there a same framework for OSX

### ISSUE THREAD

**Issue by bansalvks** [justcoding121/Titanium-Web-Proxy#50]
I need to implement the same thing that you are doin in OSX. However, I am not able to find a utility like Titanium. Your suggestions are highly apprecialted.
Many thanks for building Titanium

**Comment by justcoding121** [comment]
We might be able to port this to .NET core or may be Mono which will run cross platform on OS X and Linux. I don't have any immediate plans.

**Comment by pr4bh4sh** [comment]
Fiddler has mono port http://fiddler.wikidot.com/mono
It also uses makecert.exe, I not sure if is possible to use that(legal or any other issue).

**Comment by justcoding121** [comment]
Should be supporting Mono now (I haven't verified though)
