### ISSUE TITLE
How to specify  upstream proxy  for each request

### ISSUE THREAD

**Issue by boyyao** [justcoding121/Titanium-Web-Proxy#512]
How to specify  upstream proxy  for each request
I have a proxy pool. The custom request header controls the “ upstream proxy” in app.
So I hope to use a specific  upstream proxy for each request.
Be similar to
private async Task OnRequest(object sender, SessionEventArgs e)
{
   if(e.WebSession.Request.Headers.HeaderExists("useExPrxoy")){
        e.WebSession.Request.Proxy = New WebProxy("122.122.122.122",8888);  <= how to??
        or
        e.CustomUpStreamProxyUsed = new ExternalProxy() { HostName="122.122.122.122",Port=8888}; <= how to??
        e.WebSession.Request.Headers.RemoveHeader("useExPrxoy");
     }
}
Thx...

**Comment by POMATu** [comment]
link dead

**Comment by honfika** [comment]
The github.io page is not available anymore. @justcoding121 why?
But this file is in the repository, you can download it and check locally:
https://github.com/justcoding121/titanium-web-proxy/tree/develop/docs/api

**Comment by justcoding121** [comment]
https://justcoding121.github.io/titanium-web-proxy/docs/api/Titanium.Web.Proxy.ProxyServer.html

The repository was renamed to lower case few months ago.

**Comment by justcoding121** [comment]
AlsoI think the nuget package token expires annually, and it expired. I will update it in yml file so that beta build can publish @honfika
