### ISSUE TITLE
Can't respond directly to client (cancelling the request to server) after reading body of request

### ISSUE THREAD

**Issue by roblascelles** [justcoding121/Titanium-Web-Proxy#515]
If there's a BeforeRequest handler that reads the request body & then cancels the server request by sending a response straight back to client with SessionEventArgs.Ok() - e.g.

```
public async Task OnRequest(object sender, SessionEventArgs e)
{
    if (e.WebSession.Request.Url.Contains("interceptthis.com"))
    {
        if (e.WebSession.Request.HasBody)
        {
            var body = await e.GetRequestBodyAsString();
        }

        e.Ok("<html><body>TitaniumWebProxy-Stopped!!</body></html>");
        return;
    }
    await Task.FromResult(0);
}
```

...then the proxy never responds to client (removing the GetRequestBodyAsString line above, or sending a request without a body, & it works fine). 

I've added a failing test & a possible fix here: 

https://github.com/justcoding121/Titanium-Web-Proxy/compare/master...roblascelles:read-body-and-cancel-request-to-server?expand=1

I think it's because it's trying to ready the request body again, but not entirely sure.

**Comment by danielherken** [comment]
I can confirm that your changes fixed the issue for me as well. Thanks!

**Comment by justcoding121** [comment]
This should be fixed in master. Thanks for the patch.
