### ISSUE TITLE
ReRequest fails on RequestUri changes

### ISSUE THREAD

**Issue by nirbil** [justcoding121/Titanium-Web-Proxy#519]
I need to automatically follow redirect responses internally and return just the final response.
So I did something like this:

    public async Task OnResponse(object sender, SessionEventArgs e)
    {
        if (e.WebSession.Response.StatusCode >= 300 &&
            e.WebSession.Response.StatusCode <= 307 &&
            e.WebSession.Response.Headers.HeaderExists("Location"))
        {
            Uri redirectUri;
            if (!Uri.TryCreate(e.WebSession.Request.RequestUri, e.WebSession.Response.Headers.GetFirstHeader("Location").Value, out redirectUri))
            {
                e.WebSession.Response.StatusCode = (int)HttpStatusCode.InternalServerError;
                e.WebSession.Response.StatusDescription = "Location error";
                return;
            }

            if (e.WebSession.Request.RequestUri.AbsoluteUri.ToLower() != redirectUri.AbsoluteUri.ToLower())
                e.WebSession.Request.RequestUri = redirectUri;
                e.WebSession.Request.Host = e.WebSession.Request.RequestUri.Host;
                e.ReRequest = true;
            }
        }
    }

But apparently ReRequest only allows sending the request over an existing server connection, so changing the request uri and requesting a ReRequest does not work.

Here's the relevant responseHandler's code:

    // if user requested to send request again
    // likely after making modifications from User Response Handler
    if (args.ReRequest)
    {
        // clear current response
        await args.ClearResponse(cancellationToken);
        await handleHttpSessionRequest(args.WebSession.ServerConnection, args);
        return;
    }

**Comment by nirdil** [comment]
Looking at the responseHandler's relevant code:
    if (args.ReRequest)
    {
        // clear current response
        await args.ClearResponse(cancellationToken);
        await handleHttpSessionRequest(args.WebSession.ServerConnection, args);
        return;
    }

I might be wrong but it seems like the ReRequest function only supports sending a new request over an existing server connection and will not start a new connection if necessary.
Am wondering re feasibility and how difficult would it be to implement a change.

**Comment by nirdil** [comment]
Went ahead and patched it like so:

In ResponseHandler.cs, before user callback invocation, save the request uri:

    // if user requested call back then do it
    var preCallbackReqUri = args.WebSession.Request.RequestUri;
    if (!response.Locked)
    {
        await invokeBeforeResponse(args);
    }

In ResponseHandler.cs, when handling ReRequest, raise a new connection if necessary:

    // if user requested to send request again
    // likely after making modifications from User Response Handler
    if (args.ReRequest)
    {
        // clear current response
        await args.ClearResponse(cancellationToken);
        if ((preCallbackReqUri.Host != args.WebSession.Request.RequestUri.Host) ||
            (preCallbackReqUri.Scheme != args.WebSession.Request.RequestUri.Scheme))
        {
            await tcpConnectionFactory.Release(args.WebSession.ServerConnection, true);
            args.WebSession.ServerConnection = await tcpConnectionFactory.GetServerConnection(this, args, isConnect: false, applicationProtocol: args.ProxyClient.ClientConnection.NegotiatedApplicationProtocol, noCache: false, cancellationToken: cancellationToken);
        }

        await handleHttpSessionRequest(args.WebSession.ServerConnection, args);
        return;
    }

Seems to be working fine for my requirements...
@justcoding121 - I would love some input if this makes sense or am I missing/messing up anything.

**Comment by justcoding121** [comment]
Thanks I will take a look when I get time

**Comment by justcoding121** [comment]
Should be fixed in latest beta.
