### ISSUE TITLE
Proxy start fails with exception in monodroid

### ISSUE THREAD

**Issue by nirbil** [justcoding121/Titanium-Web-Proxy#521]
Executing proxyServer.Start() on Android  fails with exception.

This behavior is only reproducible when running the library in release mode.

The exception was traced to a file system access violation exception while writing the generated root certificate to disk cache.

Here's the relevant code in DefaultCertificateDiskCache.cs for getting the target certificate folder:

    private string getRootCertificateDirectory()
    {
        if (rootCertificatePath == null)
        {
            string assemblyLocation = GetType().Assembly.Location;

            // dynamically loaded assemblies returns string.Empty location
            if (assemblyLocation == string.Empty)
            {
                assemblyLocation = Assembly.GetEntryAssembly().Location;
            }

            string path = Path.GetDirectoryName(assemblyLocation);

            rootCertificatePath = path ?? throw new NullReferenceException();
        }

        return rootCertificatePath;
    }

The target folder is set to be along side the assembly location.
However - this is not necessarily a writable path, as in the Android example.
Instead, I believe this folder should be used:
`rootCertificatePath = Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData);`

**Comment by justcoding121** [comment]
You can implement you own certificate cache to prevent this.

**Comment by justcoding121** [comment]
Since filesystem APIs are quite difference for each platform (for example UWP, Xamarin iOS & Android), I don't think its appropriate for the proxy to handle each scenarios. Just implement the certificate cache interface.

https://github.com/justcoding121/Titanium-Web-Proxy/blob/master/src/Titanium.Web.Proxy/Network/ICertificateCache.cs

Your implementation won't be very different that what we have as default.
https://github.com/justcoding121/Titanium-Web-Proxy/blob/master/src/Titanium.Web.Proxy/Network/DefaultCertificateDiskCache.cs

**Comment by justcoding121** [comment]
If someone would like to add default certificate cache for each of the platforms I would be open to merge. We can use those defaults based on the RunTime.

**Comment by nirbil** [comment]
Here's what I got.
I've tested this on Linux (Android) and UWP.
I'm not sure what's the writable folder in Mac, so it's just a guess.
On standard windows it defaults to the old mechanism (the assembly's location). I'm not sure that's a good thing...

    private string getRootCertificateDirectory()
    {
        if (rootCertificatePath == null)
        {
            if (RunTime.IsUwpOnWindows)
            {
                rootCertificatePath = Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData);
            }
            
            else if (RunTime.IsLinux)
            {
                rootCertificatePath = Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData);
            }

            else if (RunTime.IsMac)
            {
                rootCertificatePath = Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData);
            }

            else
            {
                string assemblyLocation = GetType().Assembly.Location;

                // dynamically loaded assemblies returns string.Empty location
                if (assemblyLocation == string.Empty)
                {
                    assemblyLocation = Assembly.GetEntryAssembly().Location;
                }

                string path = Path.GetDirectoryName(assemblyLocation);
                rootCertificatePath = path ?? throw new NullReferenceException();
            }
        }

        return rootCertificatePath;
    }

**Comment by justcoding121** [comment]
Thanks. Looks simpler than I thought. I will take a look.
