### ISSUE TITLE
Proxy start fails on UWP

### ISSUE THREAD

**Issue by nirbil** [justcoding121/Titanium-Web-Proxy#522]
Under UWP, running ProxyServer.Start throws a System.IO.FileLoadException for Microsoft.Win32.Registry. Was mapped to the following code:

    // clear any system proxy settings which is pointing to our own endpoint (causing a cycle)
    // due to ungracious proxy shutdown before or something else
    if (systemProxySettingsManager != null && RunTime.IsWindows)
    {
        var proxyInfo = systemProxySettingsManager.GetProxyInfoFromRegistry();

As a system proxy is irrelevant for UWP anyways, I suggest to just wrap this cleanup with a try catch, that worked for me and allowed it to run on UWP.

**Comment by justcoding121** [comment]
Should be fixed in latest beta.
