### ISSUE TITLE
Empty response for google sites

### ISSUE THREAD

**Issue by judebigj** [justcoding121/Titanium-Web-Proxy#523]
Hello,
           I noticed that some of my windows machine are having trouble accessing Google sites via proxy.
The titanium proxy is running locally and have included "google.com" url.
The same Proxy application works well on other machines on the network. 

I also checked the same with Fiddler but it google sites works without any issues. The error code I get on  the chrome browser is 504 , Empty response. I recon this could be a timeout issue, but not sure.

Can you please advice what could be causing this issue on some machines and not on the others?

Note: youtube.com is blocked at firewall level.  While using fiddler when I access "google.com"  via browser, it does show a trace of accounts.youtube.com being blocked in Fiddler, but other requests works successfully and the page open without problem.
Could it be that in case of Titanium, any request failure (youtube.com in our case)  might cause other requests to fail also?

**Comment by honfika** [comment]
Please try the latest package.

**Comment by honfika** [comment]
I close this isse, feel free to reopen if needed.
