### ISSUE TITLE
Certificate Trust Issue with Windows Service

### ISSUE THREAD

**Issue by harrip12** [justcoding121/Titanium-Web-Proxy#532]
Hi,
I am using Windows Service and installed Titanium from Nuget, I am getting Certificate True issue.
`proxyServer = new ProxyServer();
 proxyServer.BeforeRequest += OnRequest;
 proxyServer.BeforeResponse += OnResponse;

 explicitEndPoint = new ExplicitProxyEndPoint(IPAddress.Parse("127.0.0.1"), 12001);
 proxyServer.AddEndPoint(explicitEndPoint);
 proxyServer.Start();`

I tried with
`proxyServer.CertificateManager.CertificateEngine = Titanium.Web.Proxy.Network.CertificateEngine.DefaultWindows;
proxyServer.CertificateManager.TrustRootCertificateAsAdmin(true);
proxyServer.CertificateManager.TrustRootCertificate(true);`

But, got exception at TrustRootCertificateAsAdmin saying 
     "Could not install certificate as it is null or empty"
Please help me to find the solution.

**Comment by xinghusp** [comment]
I have the same problem, the same code works fine in both Winform and Console, but it is not work in Windows services. Several Titanium versions have been tried.

**Comment by justcoding121** [comment]
Windows services by default run with fewer privileges. This has nothing to do with the proxy. You will have to find some way to install the root certificate.

**Comment by harrip12** [comment]
Certificate problem is solved with:
`proxyServer.CertificateManager.CertificateEngine = Titanium.Web.Proxy.Network.CertificateEngine.DefaultWindows;
 proxyServer.CertificateManager.EnsureRootCertificate();`

Now I have another problem, Exception at proxy.Start();

> Could not load file or assembly 'Microsoft.Win32.Registry, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.":"Microsoft.Win32.Registry, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a"

I have created a library with .NetStandard 2.0, which is referenced by Windows Service build with netFramework 4.5 and that library is using Titanium DLL.

**Comment by justcoding121** [comment]
If you are using .Net 4.5 why are we referencing .net standard. You could directly use 
net 4.5 version of the proxy. .net standard don't support registry API since its windows specific.

**Comment by harrip12** [comment]
I need to create a Library which can be used with both .NetFramework and .NetCore, So I am creating that library with .NetStandard2.0 and it is responsible to Start, Stop proxy and handling the requests.

In Windows OS we have Windows Service to start proxy on machine startup, but in MAC and linux there is nothing like that so we have start proxy with Batch file or Shell Scripting.

**Comment by justcoding121** [comment]
I think we can add these required packages as a dependency for our nuget package for .NET core framework. I will work on this later.
