### ISSUE TITLE
Can this tool monitor the local net data?

### ISSUE THREAD

**Issue by Fengtao1314520** [justcoding121/Titanium-Web-Proxy#533]
I want monitor my application data from web  front to background server on local. can this tool support this funciton?

**Comment by justcoding121** [comment]
Yes. It works like Fiddler.

**Comment by Fengtao1314520** [comment]
thanks for your receive my message.
now i have two new questions.
1. My network has an external access VPN，if I want use tool, I need uncheck "Automatically detect settings" on IE setting, could you hava some suggestion to solve this ?
2.when i use "AfterResponse" event to get the response body data, I use 
`(SessionEventArgs)e.Response.Body`
`(SessionEventArgs)e.Response.BodyString`
these void were failed  because "System.Exception", 
and 
`(SessionEventArgs)e.GetRequestBody()`
`(SessionEventArgs)e.GetRequestBodyString()`
just get the response header information.

How can i get the response the body data? 
thanks for you help .

**Comment by justcoding121** [comment]
1. VPN proxy settings conflict. You probably can uncheck "Automatically detect settings" from code by modifying registry values
2. You need to first call `e.GetRequestBody()` inside `OnRequest` handler. If not, the body would never get read and cached, its just buffered to client.  System.Exception details will have the same message.
