### ISSUE TITLE
Rotating IP Addresses Per Request

### ISSUE THREAD

**Issue by adamfisher** [justcoding121/Titanium-Web-Proxy#534]
Is it possible to use Titanium Web Proxy to:

1. Rotate between a pool of IP addresses, using a different IP address for each request?
2. Perform periodic health checks on each IP address and remove unhealthy endpoints in the background?
3. Ability to add new proxy IP endpoints dynamically at run time?

**Comment by justcoding121** [comment]
1. Can you please elaborate. Are you talking about a reverse proxy load balancer setup? If so, yes you can. In the request handler, modify the request URL to the IP address of the machine you want the traffic to hit. Or when you say "different IP address" for each request, do you mean to use different local NIC cards of the proxy machine (with each an assigned IP address) to make the request via. It is also possible by modifying `LocalEndPoint` for each request session.
https://justcoding121.github.io/Titanium-Web-Proxy/docs/api/Titanium.Web.Proxy.EventArguments.SessionEventArgsBase.html#Titanium_Web_Proxy_EventArguments_SessionEventArgsBase_LocalEndPoint

2. This you can implement yourself, just write code that periodically does health checks and keep a list of valid IP addresses. Then use one of the valid IP addresses when rewriting request URL as noted in point number one above.

3. Yes, you can add or remove proxy listening endpoints dynamically.

**Comment by honfika** [comment]
Close this isseu due to inactiity. Feel free to reopen if neeed.
