### ISSUE TITLE
IsLocalIpAddress check returns false positives

### ISSUE THREAD

**Issue by jmh76** [justcoding121/Titanium-Web-Proxy#535]
Broken by [refactor local IP check](https://github.com/justcoding121/Titanium-Web-Proxy/commit/0d628c6dbdb6d21e0a82bf06a2ee151d2efb86fd): `isLocalhost = hostEntry.AddressList.Any(x => hostEntry.AddressList.Any(x.Equals));` will always return true.

While fixing this I refactored the class slightly to reduce LOC and also include a few more checks, will submit pull request.

**Comment by justcoding121** [comment]
Thanks. Merged.
