### ISSUE TITLE
How to troubleshoot proxy on server, when it doesn't connect?

### ISSUE THREAD

**Issue by nefcanto** [justcoding121/Titanium-Web-Proxy#540]
I'm using Titanium Web Proxy alongside Selenium for automation purposes. Here's my code:
```

IWebDriver driver;
int port = 18882;
var proxyServer = new ProxyServer
{
};
proxyServer.CertificateManager.TrustRootCertificate(true);
var explicitEndPoint = new ExplicitProxyEndPoint(System.Net.IPAddress.Any, port, true);
proxyServer.AddEndPoint(explicitEndPoint);
proxyServer.Start();
proxyServer.SetAsSystemHttpProxy(explicitEndPoint);
proxyServer.SetAsSystemHttpsProxy(explicitEndPoint);
proxyServer.BeforeRequest += OnRequestEventHandler;
proxyServer.BeforeResponse += OnResponseEventHandler;
var proxy = new OpenQA.Selenium.Proxy
{
    HttpProxy = $"http://localhost:{port}",
    SslProxy = $"http://localhost:{port}",
    FtpProxy = $"http://localhost:{port}"
};
var options = new ChromeOptions
{
    Proxy = proxy
};
driver = new ChromeDriver(options);
// doing some stuff using Titianium Web Proxy combined with Selenium
proxyServer.Stop();
```

Which works perfectly on my local machine. And I can `telnet localhost 18882` on my local machine and it connects.

However, when I deploy to the server (a simple VPS) the `telnet localhost 18882` doesn't connect, and also Chrome shows this screen:

![capture](https://user-images.githubusercontent.com/12782347/50980821-d0e67380-150e-11e9-9e26-01e66670d0c6.PNG)

I've added port `18882` to both inbound and outbound allowed ports in Windows Firewall. I also made sure everything is running as administrator. But still no results. Could you please help on how should I troubleshoot this?

**Comment by honfika** [comment]
Have you added the 18882 inbound allowed port to the VPS Windows server? Maybe they have another firewall which should open this port.

**Comment by honfika** [comment]
I close this issue due to inactivity. Feel free to reopen it when problem still exists.
