### ISSUE TITLE
Losing UserData when DecryptSsl is enabled

### ISSUE THREAD

**Issue by macgyver2k** [justcoding121/Titanium-Web-Proxy#541]
I have configured an explicit endpoint with DecryptSsl enabled.

`new ExplicitProxyEndPoint(IPAddress.Any, port, true);`

I also configured a `ProxyBasicAuthenticateFunc` callback to authenticate the client.
In the callback user and password are validated and a custom `SessionInfo` object is set as the UserData of the session event args. The callback returns `true` if authentication was successfull, `false` otherwise.

`sessionEventArgsBase.UserData = sessionFindResult.SessionInfo`

Even further, I configured a `GetCustomUpStreamProxyFunc` callback which looks up a proxy according to the previously set `sessionEventArgsBase.UserData`. The callback returns the appropriate proxy as `ExplicitProxy`.

The problem is, the `GetCustomUpStreamProxyFunc` gets called a second time, but the assigned `sessionEventArgsBase.UserData` is `null` now.

There is no second execution of `GetCustomUpStreamProxyFunc` if DecryptSsl is disabled.

**Comment by justcoding121** [comment]
Added a test case and was able to reproduce this. 
https://github.com/justcoding121/Titanium-Web-Proxy/blob/master/tests/Titanium.Web.Proxy.IntegrationTests/NestedProxyTests.cs#L41

This was fixed in the latest beta nuget package release.
