### ISSUE TITLE
Bad responses from server

### ISSUE THREAD

**Issue by nirbil** [justcoding121/Titanium-Web-Proxy#544]
Occasionally a request routed through the server fails due to a malformed response.
I've managed to reproduce it on an Android app. I tried reproducing it also on a win console app but couldn't.
It seems to be related to high load on the server, but I'm not certain.

Steps to reproduce:
1. Create a new xamarin.android project
2. Via nuget add Titanium.Web.Proxy
3. Add the following class to the project and instantiate it in the main activity, this class just returns an empty 200OK for each request:

       class ProxyManager
       {
              ProxyServer _proxyServer;
              public ProxyManager()
              {
                     _proxyServer = new ProxyServer();
                     _proxyServer.ExceptionFunc = exception =>
                     {
                            if (exception is ProxyHttpException phex)
                            {
                                   System.Diagnostics.Trace.WriteLine(exception.Message + ": " + phex.InnerException?.Message);
                            }

                            else
                            {
                                   System.Diagnostics.Trace.WriteLine(exception.Message);
                            }
                     };

                     _proxyServer.AddEndPoint(new ExplicitProxyEndPoint(IPAddress.Any, 12345));
                     _proxyServer.BeforeRequest += OnRequest;
                     _proxyServer.Start();
              }

              Task OnRequest(object sender, SessionEventArgs e)
              {
                     e.GenericResponse("", HttpStatusCode.OK);
                     return Task.FromResult(true);
              }
       }

4. Start adb command prompt: VS2017 -> Tools -> Android -> Android Adb Command Prompt
5. Forward the relevant TCP port: adb forward tcp:12345 tcp:12345
6. Start issuing random requests to that port

I used Fiddler to simulate load on the server by duplicating one request and then issuing that same request in batches. If you run them sequentially then everything is fine, but once you run them in parallel things start to glitch.

Here's a typical response batch, some of the responses are fine but some are malformed:

![results1](https://user-images.githubusercontent.com/20151466/51605313-6292af80-1f17-11e9-889b-01dd334ff9cd.png)

![results2](https://user-images.githubusercontent.com/20151466/51605314-632b4600-1f17-11e9-83c3-fd4ebee3378d.png)

![results3](https://user-images.githubusercontent.com/20151466/51605315-632b4600-1f17-11e9-9a3f-639af3b053d5.png)

![results4](https://user-images.githubusercontent.com/20151466/51605316-632b4600-1f17-11e9-9222-ccf35e1242fd.png)

**Comment by nirbil** [comment]
I found the root cause of the problem.
It's in the HttpWriter.cs class, in the writeAsyncInternal function.
In case the write operation uses a buffer pool, it returns the buffer to the pool ahead of time, before the async write operation finishes. If that happens while another request is accessing the pool then they both might use the same buffer at the same time and things get messy.

This is how I fixed it:

        private Task writeAsyncInternal(string value, bool addNewLine, CancellationToken cancellationToken)
        {
            int newLineChars = addNewLine ? newLine.Length : 0;
            int charCount = value.Length;
            if (charCount < BufferSize - newLineChars)
            {
                value.CopyTo(0, charBuffer, 0, charCount);

                var buffer = bufferPool.GetBuffer(BufferSize);
                try
                {
                    int idx = encoder.GetBytes(charBuffer, 0, charCount, buffer, 0, true);
                    if (newLineChars > 0)
                    {
                        Buffer.BlockCopy(newLine, 0, buffer, idx, newLineChars);
                        idx += newLineChars;
                    }

                    return stream.WriteAsync(buffer, 0, idx, cancellationToken).ContinueWith((antecedent) => bufferPool.ReturnBuffer(buffer));
                }
                catch(Exception ex)
                {
                    bufferPool.ReturnBuffer(buffer);
                    throw ex;
                }
            }
            else
            {
            ...

**Comment by justcoding121** [comment]
Thanks for the code. I will check and fix this in master when I get time or you can create a PR.

**Comment by justcoding121** [comment]
Thanks.
