### ISSUE TITLE
GetRequestBody sometimes returns 0 bytes even when ContentLength > 0

### ISSUE THREAD

**Issue by jmh76** [justcoding121/Titanium-Web-Proxy#545]
This seems to occur semi randomly. On an HTTP POST with content-length > 0, SessionEventArgs.GetRequestBody sometimes returns 0 bytes. I do get SessionEventArgs's OnDataSent event (byte[0], 0, 0) after IsBodyRead=true, but I do not get the OnDataSent event while IsBodyRead=false (fired from the event handler for HttpWriter's onCopy event). So the ReadAsync inside HttpWriter.copyBytesFromStream must be returning 0.

Any ideas?

**Comment by justcoding121** [comment]
Do you see this in the latest stable release a few hours ago? We had an issue with buffer pool that got fixed which may be related to this.

**Comment by jmh76** [comment]
Same issue with new release. What do you think of the delayed body data theory? How would you suggest attempting to reread if expected data isn't read?

**Comment by justcoding121** [comment]
If you clone the stream-extended project and reference it directly instead of nuget, you would be able to step into the ReadAsync call and see what is happening. Just a debugging tip in case you didn't thought about it.

**Comment by justcoding121** [comment]
If you could come up with an integration test fail case to reproduce this it would be great.

One sample integration is below.
https://github.com/justcoding121/Titanium-Web-Proxy/blob/master/tests/Titanium.Web.Proxy.IntegrationTests/InterceptionTests.cs

**Comment by jmh76** [comment]
Thanks for the feedback. I'd been working with stream-extended also. It's very inconsistent. Haven't been able to reproduce with my integration tests yet but that's helped me understand the flow better. I'm still working on that plus libcurl client verbose logging in the real world. Hope that points to something eventually.

**Comment by jmh76** [comment]
Problem solved. I was waiting on SessionEventArgs.GetRequestBody even for "Expect: 100-continue" requests. The client would wait for the 100 Continue response, which it never got because the request was blocked. If the continue timeout expired before curl's low speed timeout it would send the data, otherwise it would close the connection. When the latter happened it then SessionEventArgs.GetRequestBody would return with 0 bytes.

**Comment by jmh76** [comment]
PS I had started with code copied from [this stackoverflow question](https://stackoverflow.com/questions/47687999/how-to-write-a-reverse-proxy-using-titanium-web-proxy) which I've noticed other issues have the same copied code. I left a warning comment there.
