### ISSUE TITLE
Host on IIS?

### ISSUE THREAD

**Issue by JobaDiniz** [justcoding121/Titanium-Web-Proxy#549]
Any idea how to host Titanium Web Proxy used for _Reverse Proxy_ ([example](https://github.com/justcoding121/Titanium-Web-Proxy/issues/344#issue-280793538)) on IIS?

For example, https://webproxy.mydomain/ would hit Titanum Web Proxy implementation.

**Comment by justcoding121** [comment]
No, it's not possible. The proxy can only run as an independent process.

IIS itself can be configured to work as a reverse proxy using its Url Rewrite module. So you may not even need Titanium Web Proxy in that case.

**Comment by JobaDiniz** [comment]
> IIS itself can be configured to work as a reverse proxy using its Url Rewrite module. So you may not even need Titanium Web Proxy in that case.

In my case, there's a logic involved to figure out where to proxy to, e.g getting a custom header with the url to proxy to...

**Comment by justcoding121** [comment]
You don't need IIS if you directly listen using Titanium Web Proxy as a reverse proxy.

**Comment by jimbuck** [comment]
Maybe look into [ProxyKit](https://github.com/damianh/ProxyKit)? It's a reverse proxy built on ASP.NET Core.

**Comment by honfika** [comment]
I close this issue due to inactivity. Feel free to reopen if needed.
