### ISSUE TITLE
Http connection hangs

### ISSUE THREAD

**Issue by gatodev** [justcoding121/Titanium-Web-Proxy#552]
in RequestHandler.cs, at line 372 ```args.CopyRequestBodyAsync(writer, TransformationMode.None, cancellationToken)``` is called, in which ```reader.ReadAsync(buffer, 0, bytesToRead, cancellationToken)``` at HttpWriter.cs line 273 is called,
```ServerConnectionException``` thrown at ```handleHttpSessionResponse(args)``` line 383,
```retryPolicy<ServerConnectionException>().ExecuteAsync(...)``` at line 293 catches it and retries the action,
again, ```args.CopyRequestBodyAsync(writer, TransformationMode.None, cancellationToken)``` at line 372,
eventually, stuck in ```reader.ReadAsync(buffer, 0, bytesToRead, cancellationToken)``` at HttpWriter.cs line 273.

On Linux, Mono 5.18.0.240 (tarball Wed Jan 16 09:13:03 UTC 2019) (64-bit), Google Chrome

**Comment by honfika** [comment]
Is this issue still exists in the latest package?

**Comment by gatodev** [comment]
I can't tell. Maybe I did something wrong. Forget about this.
