### ISSUE TITLE
Fixing Expect 100-continue requests

### ISSUE THREAD

**Issue by jmh76** [justcoding121/Titanium-Web-Proxy#553]
If BeforeRequest handler sets a locked response (e.g. 4xx/5xx on error conditions), or if the server responds with a final status other than 100 or 417 (this is allowed according to spec), RequestHandler still tries to read the request body. In this case it should just send the response immediately.

I'm ok with fixing these cases and adding integration tests. But I don't understand what behavior is intended when Enable100ContinueBehaviour is false. Can you explain what should happen? Or maybe the flag should be removed and 100-continue behavior should always be enabled...

**Comment by justcoding121** [comment]
Enable100ContinueBehaviour was a flag I added long ago when I had problems following the 100-continue rfc as it is. I am not sure in practice if the protocol is strictly followed. See below line for example.

https://github.com/justcoding121/Titanium-Web-Proxy/blob/master/src/Titanium.Web.Proxy/Http/HttpWebClient.cs#L132

If you think the flag is not warranted and after testing different sites it seems working okay then I am okay with removing it.

**Comment by jmh76** [comment]
I got it. Must have been tired. The spec is at https://tools.ietf.org/html/rfc2616#section-14.20 and https://tools.ietf.org/html/rfc2616#section-8.2.3

When Enable100ContinueBehaviour is true and an expect:100 request is received, the proxy will send the headers and wait for a response. If the server doesn't meet the spec it may not respond at all. The spec says clients should send the body anyway (curl does this). Ideally, to handle a possibly broken server the proxy should be waiting for the request body at the same time that it's waiting for a server response.

Instead the default behavior is not to not send the expect request at all until the body has been received from the client. This doesn't meet the spec but besides the delay it won't break well behaved clients. To fully meet the spec the proxy should keep track of server http version etc and send back 417 responses if it knows the expectation will fail. That's a ton of work, and anyway curl's handling of 417 responses is broken: https://curl.haxx.se/docs/knownbugs.html#Expect_100_meets_417

So the current default behavior is a good compromise for handling possibly broken servers. The Enable100ContinueBehavior flag should only be set if the client is sending expect:100 requests and the server is known to be good.

I'll still fix the broken cases that I mentioned before.

**Comment by honfika** [comment]
May I close this issue?
