### ISSUE TITLE
unable to navigate to google.com using SSL

### ISSUE THREAD

**Issue by stlpedro** [justcoding121/Titanium-Web-Proxy#557]
I'm using Xamarin with the latest stable version of Titanium (3.0.895). normal sites work but im unable to navigate to google.com is it becayse I need to downlaod the root cert and trus it manually in the device? or Am I missing something?

            _proxyServer = new ProxyServer(true, true, true);
            _proxyServer.CertificateManager.CreateRootCertificate(true);
            _proxyServer.CertificateManager.TrustRootCertificate(true);
            _proxyServer.CertificateManager.TrustRootCertificateAsAdmin(true);

            //locally trust root certificate used by this proxy 
            _proxyServer.CertificateManager.TrustRootCertificate(true);
            //_proxyServer.CertificateManager.

            //optionally set the Certificate Engine
            //Under Mono only BouncyCastle will be supported
            _proxyServer.CertificateManager.CertificateEngine = Titanium.Web.Proxy.Network.CertificateEngine.BouncyCastle;

            //Temp Disabled
            _proxyServer.BeforeRequest += OnRequest;
            //_proxyServer.BeforeResponse += OnResponse;
            _proxyServer.ServerCertificateValidationCallback += OnCertificateValidation;
            _proxyServer.ClientCertificateSelectionCallback += OnCertificateSelection;

            _explicitEndPoint = new ExplicitProxyEndPoint(IPAddress.Any, 8000, true)
            {
                //Use self-issued generic certificate on all https requests
                //Optimizes performance by not creating a certificate for each https-enabled domain
                //Useful when certificate trust is not required by proxy clients
                //GenericCertificate = new X509Certificate2(Path.Combine(System.IO.Path.GetDirectoryName(System.Reflection.Assembly.GetExecutingAssembly().Location), "genericcert.pfx"), "password")
            };

            //Fired when a CONNECT request is received
            //temp disabled
            _explicitEndPoint.BeforeTunnelConnectRequest += OnBeforeTunnelConnectRequest;

            //An explicit endpoint is where the client knows about the existence of a proxy
            //So client sends request in a proxy friendly manner
            _proxyServer.AddEndPoint(_explicitEndPoint);
            _proxyServer.Start();

            //Transparent endpoint is useful for reverse proxy (client is not aware of the existence of proxy)
            //A transparent endpoint usually requires a network router port forwarding HTTP(S) packets or DNS
            //to send data to this endPoint
            var transparentEndPoint = new TransparentProxyEndPoint(IPAddress.Any, 8001, true)
            {
                //Generic Certificate hostname to use
                //when SNI is disabled by client
                GenericCertificateName = "google.com"
            };

            _proxyServer.AddEndPoint(transparentEndPoint);

            //_proxyServer.UpStreamHttpProxy = new ExternalProxy() { HostName = "localhost", Port = 8888 };
            //_proxyServer.UpStreamHttpsProxy = new ExternalProxy() { HostName = "localhost", Port = 8888 };

            foreach (var endPoint in _proxyServer.ProxyEndPoints)
            {
                System.Diagnostics.Debug.WriteLine("Listening on '{0}' endpoint at Ip {1} and port: {2} ",
                    endPoint.GetType().Name, endPoint.IpAddress, endPoint.Port);
            }

            //Only explicit proxies can be set as system proxy!
            //_proxyServer.SetAsSystemHttpProxy(_explicitEndPoint);
            //_proxyServer.SetAsSystemHttpsProxy(_explicitEndPoint);

**Comment by honfika** [comment]
Normal sites = HTTP only? Or other HTTPS sites are worrking except google?

Yes, you should trust the root certificate somehow (I never tried it on a phone/tablet) Android or IPhone/Pad?

**Comment by honfika** [comment]
I close this issue due to inactivity. Feel free to reopen is needed.
