### ISSUE TITLE
win7 32bit error : https didnot work  unless remake a new pfx and TrustRootCertificate() again

### ISSUE THREAD

**Issue by windtrace** [justcoding121/Titanium-Web-Proxy#559]
Https can work only on the first run ,after  delete the old .pfx file.Because the proxy will rebuild the cert and reinstall.
But after close the proxy and reopen it , https did not work, because the app can not get the PrivateKey of the .pfx.An explain in www is because of the 32bit os.
var privateKey = x509.GetCngPrivateKey(); Error

![Uploading 2.png…]()

**Comment by honfika** [comment]
Please try to use BouncyCastle certificate engine.

**Comment by honfika** [comment]
I close this issue due to inactivity, feel free to reopen/create new if needed.
