### ISSUE TITLE
SetAsSystemHttpProxy method throwing exception on Linux

### ISSUE THREAD

**Issue by raivor** [justcoding121/Titanium-Web-Proxy#564]
Hello,

I am trying to set up proxy server to work with Selenium WebDriver. On windows machine better said in Visual Studio everything works well but when put on Linux agent on Azure DevOps it stuck in creating and configuring proxy server.
Running from Linux machine it throws exception when configuring proxy with endpoint. 

```
    this.proxy = new ProxyServer();

    var endPoint = new ExplicitProxyEndPoint(System.Net.IPAddress.Any, 12345, true);
    this.proxy.AddEndPoint(endPoint);
    this.proxy.Start();

    this.proxy.SetAsSystemHttpProxy(endPoint);
    this.proxy.SetAsSystemHttpsProxy(endPoint);
    this.proxy.BeforeRequest += OnRequest;
    this.proxy.BeforeResponse += OnResponse;
```

System.NullReferenceException : Object reference not set to an instance of an object.
   at Titanium.Web.Proxy.ProxyServer.SetAsSystemProxy(ExplicitProxyEndPoint endPoint, ProxyProtocolType protocolType)

**Comment by justcoding121** [comment]
SetAsSystemProxy won't work in Linux/Mac. It should actually throw a NotSupportedException instead of null reference exception.

You would have to find a way to tell Linux to use the proxy server listening port and address manually.
