### ISSUE TITLE
Fake Tunnel

### ISSUE THREAD

**Issue by ljh1991125** [justcoding121/Titanium-Web-Proxy#565]
I think titanium proxy has no **FAKE TUNNEL** function.
Before using titanium proxy, I have used FIDDLER and fiddler has fake tunnel function.
This is my source code from fiddler using fake tunnel.

<pre>
if (oSession.HTTPMethodIs("CONNECT"))
{
  oSession.oFlags["x-replywithtunnel"] = "FakeTunnel";
  return;
}
</pre>

https://stackoverflow.com/questions/23062986/capture-https-request-to-nonexistent-server-with-fiddlercore

When i connect to nonexistent SSL server using titanium proxy, occurs "Error occured whilst handling session request" exception.
Used titanium proxy version is 3.0.907.

**Comment by ljh1991125** [comment]
I am using ExplicitProxyEndPoint and i changed server address to exist SSL server at BeforeTunnelConnectRequest, BeforeTunnelConnectResponse functions but it does not work.
Is there any method to fake connect ssl server?

**Comment by ljh1991125** [comment]
I think cause of this problem is same as #543.
But only solved for Transparent Proxy but not for Explicit Proxy.

> Yeah, I was the one asking the question on stackoverflow.
> Got the solution by basically doing the same thing from Transparent to Explicit.
> remove these
> 
> <pre>
> Task<TcpServerConnection> prefetchConnectionTask = null;
> bool closeServerConnection = false;
> bool calledRequestHandler = false;
> </pre>
> and it should work, but got no idea what is the consequence of doing so.

**Comment by justcoding121** [comment]
I will take a look on this.

**Comment by justcoding121** [comment]
Meanwhile, if the issue indeed is with pre-fetching connection as noted by another user above then you counld try disabling it.

Set `EnableTcpServerConnectionPrefetch` to false.


https://justcoding121.github.io/Titanium-Web-Proxy/docs/api/Titanium.Web.Proxy.ProxyServer.html#Titanium_Web_Proxy_ProxyServer_EnableTcpServerConnectionPrefetch

**Comment by ljh1991125** [comment]
Problem has been solved.
Thank you very much!

**Comment by justcoding121** [comment]
My suggestion above is not a fix, its a hack. I will close this later when this is resolved.

**Comment by justcoding121** [comment]
This should be fixed in latest beta nuget package

**Comment by PElanchezhiyan** [comment]
Hi Team,

I'm using _Titanium web proxy_ and I have used it to block the URL. I tried to log in the _OneDrive with a 365 account_. But, I couldn't. I see that _login.microsoftonline.com_ does not allow login when the proxy is turned on.  Also, I have tried the above cmd prompt method, but it doesn't work. I have attached the error image and the code for your reference. Please let me know if there is any fix or workaround.

Cmd: https://prnt.sc/urNn__wiN-E3

Proxy Image: https://prnt.sc/0uXlo9tkUvsO

Error Image: https://prnt.sc/-JQLb00YmGlJ,  **Couldn't authenticate host 'odc.officeapps.live.com' with certificate '*.officeapps.live.com'**

Github: [BlockURLApp](https://github.com/Elanchezhiyan-AIT/BlockURLApp/tree/main)
