### ISSUE TITLE
Cannot Add New Request Header

### ISSUE THREAD

**Issue by sportyturks** [justcoding121/Titanium-Web-Proxy#567]
Maybe its something I'm missing, but I cannot add a new request header as per the code below:

![image](https://user-images.githubusercontent.com/47993996/54512120-422b2280-49a7-11e9-8b86-14b0012c5f2f.png)

The response header is fine and opening the developer tools in firefox or chrome you can see that only the response header has been added:

![Capture](https://user-images.githubusercontent.com/47993996/54512184-7a326580-49a7-11e9-8792-da3fd951920e.PNG)

I tried the latest nuget package and still no luck, I am using version 3.0.503.

**Comment by sportyturks** [comment]
Forgot to mention that I am using selenium passing through the proxy server to the web driver.  Everything seems to be working well apart from adding the new host header. Hopefully it's something obvious I've left out.

**Comment by sportyturks** [comment]
After viewing the web server logs, I noticed that the request headers are going through nicely, even though they won't be seen by the browser which I think makes sense.

**Comment by justcoding121** [comment]
If you setup is as below, then you won't see that in browser dev tools. Only web driver will see it.

browser=> proxy => web driver

**Comment by honfika** [comment]
Yes, since the header is added by the proxy, the browser does not know about the added request header. It is normal. (And the server does not know about the added response header)

Is this issue solved, can be closed?

**Comment by JutGreg** [comment]
> Yes, since the header is added by the proxy, the browser does not know about the added request header. It is normal. (And the server does not know about the added response header)
> 
> Is this issue solved, can be closed?

Yes
