### ISSUE TITLE
err_tunnel_connection_failed while DenyConnect

### ISSUE THREAD

**Issue by bainbin** [justcoding121/Titanium-Web-Proxy#595]
I use explicitEndPoint. 
at onBeforeTunnelConnectRequest set
e.DenyConnect = true for specific host
And I get ERR_TUNNEL_CONNECTION_FAILED at chrome.
No change If I set response statuscode & description...

**Comment by honfika** [comment]
I think that is normal. If you set the DenyConnect then chrome shows that error.
What were you expecting?

**Comment by honfika** [comment]
I close this isse, feel free to reopen if needed.
