### ISSUE TITLE
Get Browser Name or Application Name

### ISSUE THREAD

**Issue by surendharb** [justcoding121/Titanium-Web-Proxy#601]
Is there anyway to get the Browser name or Application name that is using the internet from the Response/Request data?

**Comment by honfika** [comment]
You can get the UserAgent string and guess the browser/application from that. But for applications it can be fake, they usually tells that they are browsers.

**Comment by surendharb** [comment]
@honfika How can I get the Process ID in Response/Request data

**Comment by honfika** [comment]
Check this sample project:
https://github.com/justcoding121/Titanium-Web-Proxy/blob/4c6a8f502555cef4cda800aaabb65bae2fed73dd/examples/Titanium.Web.Proxy.Examples.Wpf/SessionListItem.cs#L182

**Comment by surendharb** [comment]
@honfika Thanks, I'll look into this
