### ISSUE TITLE
SSL Certificate for Firefox

### ISSUE THREAD

**Issue by vsrinivasaprime** [justcoding121/Titanium-Web-Proxy#606]
I am not able to import the SSL certificate generated by the web proxy in Firefox. It gives me an error as below.

![image](https://user-images.githubusercontent.com/34157817/61226308-d338bd00-a73f-11e9-8b57-805eb470da18.png)

Could anyone please let me know if I am missing any step.

**Comment by honfika** [comment]
Was there any error message when you improted the certificate to firefox? Did you impot the pfx file directly or converted to another format before import? The image you atteched is not a certficate import error message, it is shown when you load a site and it fails.

**Comment by vsrinivasaprime** [comment]
I did not get any error message when I imported the certificate. After importing I am able to see the certificate under "Your Certificates" tab

![image](https://user-images.githubusercontent.com/34157817/61278842-8a7e1400-a7d2-11e9-9ae9-bd1805376988.png)

**Comment by honfika** [comment]
I think it should be imported to the Authorities, not to "Your certificates", please check the Fiddler's documentation.
https://docs.telerik.com/fiddler/Configure-Fiddler/Tasks/FirefoxHTTPS

**Comment by honfika** [comment]
I tried it on my maxhine. It seems that Firefox cannot accept pfx files. 
There is no error message when you import is, just simply not added to the list.
So you need to import cer file. Maybe you can use any 3rd party tool  to convert the pfx to cer, and import that.

Or export it from Titanium:
`File.WriteAllBytes("rootCert.cer", proxyServer.CertificateManager.RootCertificate.Export(X509ContentType.Cert));`


I was able to import this cer file, and it seems to work.

**Comment by vsrinivasaprime** [comment]
Thanks for your help @honfika it worked.

**Comment by mahajantushar41** [comment]
Hey , i am facing same issue , i am installing rootCert.pfx  to local machine store .   It is   showing the firefox proxy error
