### ISSUE TITLE
Titanium Proxy  3.0.1005.0 Body/BodyAsString always null

### ISSUE THREAD

**Issue by vegas2ny** [justcoding121/Titanium-Web-Proxy#623]
Hello,

I am listening for ProxyServer.BeforeResponse, and the body and bodyasstring properties are always null no matter if hasbody is true or not. This is true for every response from the web server no matter which web site im targeting. Has anyone else had this issue or can provide any guidance? I have attached a screenshot showing this.
![body always null](https://user-images.githubusercontent.com/33836703/63888253-88e86400-c9ac-11e9-9d68-14531224e2fe.png)

Thanks

**Comment by honfika** [comment]
In the screenshot you can see that the body is not null... it is throwing an exception.
Where the message is clear:
`Response body is not read yet. Use SessionEventArgs.GetResponseBody() or SessionEventArgs.GetResponseBodyAsString() method to read the response body.`

**Comment by honfika** [comment]
You should call the `GetResponseBody`, not the `GetRequestBody`...

Anyway, it calling the `GetRequestBody` should throw an exception in that case, that is a bug if it hangs.

**Comment by vegas2ny** [comment]
hey yea silly me, sorry about that after calling GetResponseBody, it hangs, i can attach a video of this if possible.

**Comment by vegas2ny** [comment]
So actually when i put a try/catch block around the code im actually getting an exception. I have attached it, but that doesn't make any sense for that one line of code.
![read pas stream](https://user-images.githubusercontent.com/33836703/63959151-8b54c780-ca59-11e9-8fd7-f888ba326fa5.png)

**Comment by vegas2ny** [comment]
I also get the same result when i call e.GetResponseBodyAsString(). Any ideas y this is happening? Thanks

**Comment by honfika** [comment]
Could you please attach a whole sample project which fails?

For me it works, and also there is a WPF sample in this repository which reads the request/response body. (It needs .net core 3.0 - currently preview - SDK

**Comment by vegas2ny** [comment]
Thanks for all your help. I got it working. All i did was update to the latest version, and made sure i set keepbody to true before calling getbodyasstring.  Thanks!

**Comment by honfika** [comment]
Ok, but it should work without KeepBody, too.

**Comment by honfika** [comment]
For me it works, and you wrote that it is now OK for you, too (however I don't understand what did you do), so I close this issue. Feel free to reopen/create new if needed.
