### ISSUE TITLE
Unused variables with type casting

### ISSUE THREAD

**Issue by ByronAP** [justcoding121/Titanium-Web-Proxy#629]
I don't understand why these lines are here? @honfika do they serve a purpose that I am not seeing?

https://github.com/justcoding121/Titanium-Web-Proxy/blob/42e35359878e6f14870697a5deedf853938d1c5a/examples/Titanium.Web.Proxy.Examples.Wpf/MainWindow.xaml.cs#L274

https://github.com/justcoding121/Titanium-Web-Proxy/blob/42e35359878e6f14870697a5deedf853938d1c5a/examples/Titanium.Web.Proxy.Examples.Wpf/MainWindow.xaml.cs#L281

**Comment by honfika** [comment]
It is just a copy-paste from the other events. This is only a sample project, it contains a lot of unused/commented code.
