### ISSUE TITLE
Can I perform the request myself?

### ISSUE THREAD

**Issue by Arcanaeum** [justcoding121/Titanium-Web-Proxy#630]
Currently when I set up the proxy server, it performs the incoming http requests for me. I'd like to perform the requests myself, using my own custom method. Is this functionality achievable with this library? Ideally, I'd perform the request myself, get the response, and then feed that back to the client using this library.

Thanks in advance

**Comment by honfika** [comment]
If I understood corretly you want to answer to the HTTP request coming from the browser without calling the web server. Yes, you can to that with this library. Jsut call the `Respond` method on the event argument of the `BeforeRequest` event.

**Comment by honfika** [comment]
Answer was provided, so I close this issue. Feel free to reopen if needed.
