### ISSUE TITLE
Is it possible to use the "cer" certificate generated by fiddler

### ISSUE THREAD

**Issue by igufei** [justcoding121/Titanium-Web-Proxy#635]
Is it possible to use the "cer" certificate generated by fiddler,the "pfx" certificate is not trusted on the Android device

**Comment by su3817806** [comment]
File.WriteAllBytes("ca.cer", proxyServer.CertificateManager.RootCertificate.Export(System.Security.Cryptography.X509Certificates.X509ContentType.Cert));

export

**Comment by honfika** [comment]
Similar problem with firefox: #606

**Comment by honfika** [comment]
Answer was provided, so I clsoe this issue. Feel free to reopen if needed.
