### ISSUE TITLE
Whether can modify SessionEventArgsBase. Method DataReceived return values

### ISSUE THREAD

**Issue by su3817806** [justcoding121/Titanium-Web-Proxy#636]
```
  e.DataReceived += (sender, args) =>
            {
                    args.Buffer //modification


            };
```

**Comment by honfika** [comment]
Yes, since it is a byte[], you can modify it, but you should not do that since it may cause problems. In the future versions of TWP it should be ReadOnlyMemory<byte>

**Comment by su3817806** [comment]
> Yes, since it is a byte[], you can modify it, but you should not do that since it may cause problems. In the future versions of TWP it should be ReadOnlyMemory

May I ask what method should be adopted now

**Comment by honfika** [comment]
I don't understand your question. What do you want to do?

**Comment by su3817806** [comment]
> I don't understand your question. What do you want to do?

How to modify the current version of DataReceived Buffer

**Comment by honfika** [comment]
You can't do that, it is "readonly". Why do you want to do that? I think it is not a good idea, this is the raw data recevied from the webserver, which is usually encrypted (TLS) and/or compressed. And only contains a chunk... how do you want to modify a for example 4k chunk of SSL data? Basically this event is good for calculating the received bytes or log the whole communication.

**Comment by su3817806** [comment]
> You can't do that, it is "readonly". Why do you want to do that? I think it is not a good idea, this is the raw data recevied from the webserver, which is usually encrypted (TLS) and/or compressed. And only contains a chunk... how do you want to modify a for example 4k chunk of SSL data? Basically this event is good for calculating the received bytes or log the whole communication.

Some websites use HTTP CONNECT, which transmits an HttpClient, and I need to modify this HttpClient
![web](https://user-images.githubusercontent.com/15986703/65833072-8c01a780-e2fe-11e9-9ee6-d9ffacf7dffc.png)
![2](https://user-images.githubusercontent.com/15986703/65833073-902dc500-e2fe-11e9-97b9-6d15518ac91c.png)

**Comment by honfika** [comment]
You should use the BeforeTunnelConnectRequest/BeforeRequest events, not the DataReceived. Is somthing not possible with them?

**Comment by honfika** [comment]
I close this issue, feel free to reopen if needed.
