### ISSUE TITLE
Respone's Chinese part was garbled

### ISSUE THREAD

**Issue by LexiSong67** [justcoding121/Titanium-Web-Proxy#637]
@honfika I have a strange problem: the Chinese characters in the returned HTML in repsonse are scrambled, as shown in figure 1 and 2.
I observed with Fiddler that the parameters in request were garbled, but the contents in response were normal, as shown in figure 3, 4 and 5.
Then I guess several possibilities: 1. Is it because the parameters in the request are garbled and the content in the response is garbled?2. Is the content in response incorrectly encoded?3. Is there any problem with the response content when unzipped with GZIP?
After debugging the code, I guess that it is not the reason. After I coded the parameter in request with GBK, the Chinese in the parameter can be displayed normally, but the content in response is still messy.Conjecture ii has tried to decode the response content with various encoding formats but failed to display the Chinese part of the content properly.Conjecture three experiments can not determine whether GZIP decompression will cause Chinese garbled code
Please help me find out the reason. Thank you very much.

![1](https://user-images.githubusercontent.com/42715899/65869331-d2addb00-e3ac-11e9-8e21-4e5cb23d8b27.PNG)
![2](https://user-images.githubusercontent.com/42715899/65869337-d6416200-e3ac-11e9-8ef0-4b89258c0d3d.PNG)
![3](https://user-images.githubusercontent.com/42715899/65869341-d6d9f880-e3ac-11e9-9246-47fd8d0ed0cb.PNG)
![4](https://user-images.githubusercontent.com/42715899/65869342-d7728f00-e3ac-11e9-9a3e-764d1688097d.PNG)
![5](https://user-images.githubusercontent.com/42715899/65869344-d7728f00-e3ac-11e9-817c-7a756fc96a8d.PNG)
![6](https://user-images.githubusercontent.com/42715899/65869345-d80b2580-e3ac-11e9-8112-f83b2d93c4de.PNG)
![7](https://user-images.githubusercontent.com/42715899/65869346-d80b2580-e3ac-11e9-8d0e-26ae05c48622.png)

**Comment by honfika** [comment]
I wrote you on Skype

**Comment by honfika** [comment]
I wrote you on skype 2 weeks ago. I think this issue is solved. Please try the latest version. Closing this issue now, feel free to reopen if needed.
