### ISSUE TITLE
LOH grows huge when a large file is requested

### ISSUE THREAD

**Issue by ByronAP** [justcoding121/Titanium-Web-Proxy#643]
The LOH grows out of control when a large file is requested. I used https://speed.hetzner.de/10GB.bin

![mem](https://user-images.githubusercontent.com/7310089/66270623-b59d6000-e823-11e9-869f-fd399e83e69a.PNG)

**Comment by honfika** [comment]
Could you please include the proxy confituration? What events do you subscribe? Do you read the metgod body? (Because of course it needs to store the whole response in memory)

**Comment by ByronAP** [comment]
yeah it looks like it is my before response handler but it is essentially the same as the code in the wpf sample

```
if (SessionHandler.TryGetSession(e.HttpClient, out var item))
            {
                item.Update(e);

                if (e.HttpClient.Response.HasBody)
                {
                    e.HttpClient.Response.KeepBody = true;
                    await e.GetResponseBody().ConfigureAwait(true);

                    item.Update(e);
                }
            }

**Comment by ByronAP** [comment]
yup ok my bad

**Comment by honfika** [comment]
Then that is the reason, it is normal. What do you want to achive? Do you really need to read the response to the memory (by calling GetResponseBody)?

**Comment by ByronAP** [comment]
no i screwed up and had code from before request in before response DOH

**Comment by ByronAP** [comment]
One thing i cant seem to get right is determining when a request is done. After response works perfectly for completed requests but if the request fails it doesn't get hit.
