### ISSUE TITLE
Could titanium proxy be used as a replacement of cntlm ?

### ISSUE THREAD

**Issue by nilleb** [justcoding121/Titanium-Web-Proxy#65]
I experience performance related issues with cntlm, notably when using npm.

Could titanium-web-proxy be used as an authentication proxy ?

**Comment by justcoding121** [comment]
Not yet

**Comment by nilleb** [comment]
Could you please elaborate? You must have a precise idea of the factors
preventing it from being an authentication proxy. Maybe I can help..

Le dim. 22 mai 2016 20:59, justcoding121 <notifications@github.com> a
écrit :

**Comment by justcoding121** [comment]
NTLM, Kerberos, Digest authentication is not supported by this proxy. As such windows authentication is only supported with Basic authentication.

It needs to be implemented. I do need to do more research.
But would be happy if someone can contribute.

You may find below links useful to implement NTLM. 
https://github.com/toolchain/Nancy.Authentication.Ntlm
https://blogs.msdn.microsoft.com/chiranth/2013/09/20/ntlm-want-to-know-how-it-works/

**Comment by justcoding121** [comment]
#139 Duplicate
