### ISSUE TITLE
SetRequestBodyString does not set a new body

### ISSUE THREAD

**Issue by developervariety** [justcoding121/Titanium-Web-Proxy#652]
This seems to be #70 reproducing itself in v3.1.1037

```csharp
e.SetRequestBodyString("bda=tesddfsddfdf");

string bodyString = await e.GetRequestBodyAsString();
Console.WriteLine(bodyString);
```

Expected output: `bda=tesddfsddfdf`
Output given: `bda=W3sidmFsdWUi`

**Comment by honfika** [comment]
This was not the same problem az in #70. It should be fixed in the latest beta package, please try it.

**Comment by honfika** [comment]
Issue was fixed 2 weeks ago, so I clsoe this issue. Feel free to reopen if needed.
