### ISSUE TITLE
3.1.1080 not working in VB

### ISSUE THREAD

**Issue by chacham2** [justcoding121/Titanium-Web-Proxy#653]
I had a vb.net project that was working fine, upgraded, it is not not working. So, i created a sample program to test. VB, Windows, Console. In Project->Manage NuGet packages... Added Titanium.Web.Proxy and installed it (with all its dependencies). Then added the following code:

```
Imports Titanium.Web.Proxy

Module Module1

    Sub Main()
        Using Proxy_Server = New ProxyServer
            Proxy_Server.AddEndPoint(New Models.ExplicitProxyEndPoint(Net.IPAddress.Any, 8080))
            Proxy_Server.Start()
            MsgBox("wait")
            Proxy_Server.Stop()
        End Using
    End Sub

End Module
```
Added the proxy to internet options under LAN, did not work. Went back to NuGet, and "updated" the version to 3.1.1037 and it works fine. Changed it in the main project and it works there now too.

**Comment by ByronAP** [comment]
what constitutes "not working"?

**Comment by honfika** [comment]
I think this issue is fixed in the latest package, please try version 3.1.1107+

**Comment by chacham2** [comment]
Cannot confirm. I tried a simple test on my current project which is using 3.1.1037. The test was simply to execute the project and see if it does everything it is supposed to do. I use Titanium in this project to save incoming PDFs to specific directories, via the .BeforeResponse handler.

When i upgraded to  to 3.1.1122 the files were not saved (and the debug messages did not show either). I went back to 3.1.1037 and all worked fine again.

I noticed something strange though. I am using Selenium with the Chrome driver, with an option to use headless or to display the browser. When it was headless, the browser seemed to just hang at some point. When the browser was shown, it ran, it just didn't seem to execute .BeforeResponse.

----

I feel a little like i'm complaining here and yet i have not complimented all the effort that goes into a project like this. Titanium is a wonderful project and i really appreciate all the effort that goes into it. It makes my project possible. Thank you!

**Comment by honfika** [comment]
hmm.. What framework version do you use?
Could you please try exactly TWP 3.1.1107?

**Comment by chacham2** [comment]
Currently using TWP 3.1.1037.
Testing against TWP 3.1.1122.

I did not test TWP 3.1.1107 because it is not the latest version, and your last reply said to "try version 3.1.1107+".

**Comment by honfika** [comment]
Yes, I said that earlier.. Now I ask you to test exactly 3.1.107 please.

**Comment by chacham2** [comment]
Sorry, i seem to have misunderstood you. I just tried 3.1.1107, and it similarly failed, including the difference between headless and showing the browser.

**Comment by honfika** [comment]
I can't reproduce this issue :( @ByronAP's test code seems to work for me.

Do you have app.config file? Are you sure that all binding redirects are OK?

**Comment by honfika** [comment]
@ByronAP : Can you reproduce the issue with the latest stabel TWP package?

@chacham2 : Could you please create a small test project which reproduces the issue?

**Comment by chacham2** [comment]
Sure. To test it i created a Windows Forms project with two buttons, one to start the proxy and one to stop it. I added TitaniumProxy 3.1.1107:

```
Imports Titanium.Web.Proxy
Imports Titanium.Web.Proxy.EventArguments

Public Class Form1

    Private WithEvents Proxy_Server As ProxyServer

    Private Sub Button1_Click(sender As Object, e As EventArgs) Handles Button1.Click
        Proxy_Server = New ProxyServer
        Proxy_Server.AddEndPoint(New Models.ExplicitProxyEndPoint(Net.IPAddress.Any, 8080))
        Proxy_Server.Start()
    End Sub

    Private Sub Button2_Click(sender As Object, e As EventArgs) Handles Button2.Click
        Proxy_Server.Stop()
    End Sub

    Async Function Before_Response(Sender As Object, Arguments As SessionEventArgs) As Task Handles Proxy_Server.BeforeResponse
        Debug.WriteLine(Arguments.HttpClient.Request.Url)
    End Function

```
Started it, pressed the button, changed the system proxy, loaded google, debug output was mostly (i removed the arguments):

```
https://www.google.com/
https://www.google.com/gen_204?
https://www.google.com/gen_204?
https://adservice.google.com/adsid/google/ui

```

When i used 3.1.1122, it drops the domain, and shows more like:
```

/gen_204?
/gen_204?
/adsid/google/ui
```

**Comment by ByronAP** [comment]
Results seem good to me

> INFO: Proxy Started
> Press any key to close
> INFO: Connection started on 127.0.0.1:55216
> INFO: Connect request to echo.proxy.services:443
> INFO: Completed connect request to echo.proxy.services:443
> INFO: Connection started on 127.0.0.1:55219
> INFO: Request for http://echo.proxy.services/
> INFO: Completed equest for http://echo.proxy.services/
> 

Code used:


```Imports System.Net.Sockets
Imports System.Security.Cryptography.X509Certificates
Imports Titanium.Web.Proxy
Imports Titanium.Web.Proxy.EventArguments

Module Module1
    Sub Main()
        Using proxyServer = New ProxyServer
            proxyServer.CheckCertificateRevocation = X509RevocationMode.NoCheck
            AddHandler proxyServer.BeforeRequest, AddressOf BeforeRequestHandler
            AddHandler proxyServer.OnClientConnectionCreate, AddressOf ClientConnectionCreateHandler
            AddHandler proxyServer.AfterResponse, AddressOf AfterResponseHandler
            proxyServer.AddEndPoint(New Models.ExplicitProxyEndPoint(Net.IPAddress.Any, 8080, True))
            proxyServer.AddEndPoint(New Models.ExplicitProxyEndPoint(Net.IPAddress.IPv6Any, 8080, True))
            proxyServer.ExceptionFunc = AddressOf ExceptionHandlerSub
            proxyServer.Start()

            Console.WriteLine($"INFO: Proxy Started{Environment.NewLine}Press any key to close")
            Console.ReadKey()

            proxyServer.Stop()
        End Using
    End Sub

    Private Function ClientConnectionCreateHandler(sender As Object, e As TcpClient) As Task
        Console.WriteLine($"INFO: Connection started on {e.Client.RemoteEndPoint}")
        Return Task.CompletedTask
    End Function

    Private Function BeforeRequestHandler(sender As Object, e As SessionEventArgs) As Task
        If (e.HttpClient.ConnectRequest Is Nothing) Then
            Console.WriteLine($"INFO: Request for {e.HttpClient.Request.RequestUri}")
        Else
            Console.WriteLine($"INFO: Connect request to {e.HttpClient.ConnectRequest.Host}")
        End If
        Return Task.CompletedTask
    End Function

    Private Sub ExceptionHandlerSub(exception As Exception)
        Debugger.Break()
    End Sub

    Private Function AfterResponseHandler(sender As Object, e As SessionEventArgs) As Task
        If (e.HttpClient.ConnectRequest Is Nothing) Then
            Console.WriteLine($"INFO: Completed equest for {e.HttpClient.Request.RequestUri}")
        Else
            Console.WriteLine($"INFO: Completed connect request to {e.HttpClient.ConnectRequest.Host}")
        End If
        Return Task.FromResult(True)
    End Function
End Module
```

**Comment by honfika** [comment]
So the problem is  that the hostname is not in the Url anymore? Please use the RequestUri property.

**Comment by chacham2** [comment]
All i know is that where an 3.1.1107 worked, later version do not. You asked for a test, so i worked on a simple one (my actual program uses logins that i cannot share) and showed a difference between the two versions.

From your replies i am guessing this is intended behavior, so i'll probably just continue using the earlier version as its suits my needs. I apologize if i wasted your time on this.
