### ISSUE TITLE
Inbound Listener to relay HTTPS to HTTP

### ISSUE THREAD

**Issue by sleonard70** [justcoding121/Titanium-Web-Proxy#66]
I have an ASP.Net WebForm delivered over HTTPS and within that page there is a jQuery AJAX call to a third-party REST service that interfaces with hardware connected to the client's PC at http://localhost:8080.  The third-party service doesn't have an HTTPS endpoint, so the browsers block the AJAX call to to the client's local service because the page contains "Mixed-Content".

Can Titanium be set up as a MITM proxy to listen for inbound requests to the client's PC at https://localhost:8080, forward them to http://localhost:8080 and relay the responses back?

**Comment by justcoding121** [comment]
I think its possible. Listen on localhost:8080 with a transparent endpoint and then modify the request url inside the OnRequest handler to a http request. The endpoint should set the generic certificate name as localhost.
