### ISSUE TITLE
Update buildbot 

### ISSUE THREAD

**Issue by justcoding121** [justcoding121/Titanium-Web-Proxy#663]
* I can't log in with the credentials for buildbot121 account anymore. It asking me to verify unusual access using my phone number, I don't have access to the old phone number, I will have to update that to new bot buildbot171 when I get a chance. Existing builds will just work fine, but would be a problem if one day we need to log in.

**Comment by honfika** [comment]
Hi,

Resharper shows an error in docfx.json:
![kép](https://user-images.githubusercontent.com/7543982/69497122-baa09680-0ed9-11ea-886a-d7d6e2cc58e6.png)

Do you think it can be removed?

**Comment by justcoding121** [comment]
Hmm. I am actually not sure, probably you need to look at docfx documentation on the latest format of the file. I wouldn't bother unless this breaking something.
