### ISSUE TITLE
Bypass remote certificate validation

### ISSUE THREAD

**Issue by kakamokoloko** [justcoding121/Titanium-Web-Proxy#67]
Is there a way to bypass the remote certificate validation for each request?

I've placed this code in many places but I couldn't get it to work:

```cs
ServicePointManager.ServerCertificateValidationCallback =
    (s, certificate, chain, sslPolicyErrors) => true;
````

**Comment by justcoding121** [comment]
Added this feature in latest beta release. Initialize as follow.
```
  ProxyServer.RemoteCertificateValidationCallback += OnCertificateValidation;
```

And then set e.IsValid = true to bypass validatoion errors.

```
       // Allows overriding default certificate validation logic
        public void OnCertificateValidation(object sender, CertificateValidationEventArgs e)
        {
                e.IsValid = true;
        }
```

[Nuget link for beta](https://www.nuget.org/packages/Titanium.Web.Proxy/2.1.111-beta)
