### ISSUE TITLE
Decompression Exception

### ISSUE THREAD

**Issue by low1337** [justcoding121/Titanium-Web-Proxy#672]
When trying to get the response body for https://web.whatsapp.com/ with a version later than 3.1.1099-beta will throw an exception (intercepted traffic from both Firefox and Google Chrome (others probably too)).

Unsupported decompression mode: Unsupported

```csharp
public async Task OnResponse(object sender, SessionEventArgs e)
{
    try
    {
        string b = await e.GetResponseBodyAsString();
        e.SetResponseBodyString(b + "changed");
    }
    catch (Exception ex)
    {
        Console.WriteLine(ex.Message);
    }
}
```

**Comment by honfika** [comment]
This should be fixed in the latest package.

**Comment by low1337** [comment]
it's fixxed
