### ISSUE TITLE
web.whatsapp.com websocket doesn't work

### ISSUE THREAD

**Issue by low1337** [justcoding121/Titanium-Web-Proxy#676]
https://web.whatsapp.com/ or more specifically wss://web.whatsapp.com/ws does return "Error during WebSocket handshake: Unexpected response code: 400" the result of it is that the QR code doesn't load and makes the side unusable. On some rare occasion it works but 95% it doesn't.

**Comment by honfika** [comment]
Yes, I also noticed that. It is also probably fixed in master (I got Connection is null exceptions in the websocket of whatsapp site, that issue is fixed, I think it is the same problem)

I'll merge that to the beta now... Please try it... if it is still wrong, jsut let me know, and I'll check it in the evening.

**Comment by low1337** [comment]
Sorry to say but it still doesn't work :(

**Comment by honfika** [comment]
Yes, for the first time it sends resposne code 400... it seems that it does not like if TWP is using a cached server connection (which was already used for getting a page). I've never seen similar problems with websockets and did not found any specification that websockets needs a new connection, but now TWP is not using any cached server connecions for websockets. Please try the latest beta.

**Comment by low1337** [comment]
Unfortunately it's still not working. Is there a possible workaround so it works consistently?

**Comment by honfika** [comment]
Please try it again with the latest beta

**Comment by low1337** [comment]
Looks good now. Thanks for all the work you have done to fix this. Gonna close this now.
