### ISSUE TITLE
Latest beta doesn't seem to read/decode request line properly

### ISSUE THREAD

**Issue by ByronAP** [justcoding121/Titanium-Web-Proxy#682]
Calling from apache bench on ubuntu to the latest beta running on windows is throwing exceptions which appear to be some kind of decoding issue. Debug shows what looks like messed up unicode.

EDIT: Only happens for secure connections. (http works fine, https fails).

Command Used:
`ab -l -n 500 -c 20 -P Username:Password -X 192.168.1.26:8080 https://echo.proxy.services/`

> {"Invalid HTTP request line: \u0016\u0003\u0001\0Ù\u0001\0\0Õ\u0003\u0003'Ï\u0098\u0098è\u0088¯óÂL rQFól2C\u001c·ïÚnoD?¯wÝ#ñ\u009e\0\08À,À0\0\u009fÌ©Ì¨ÌªÀ+À/\0\u009eÀ$À(\0kÀ#À'\0gÀ"}

> System.Exception
>   HResult=0x80131500
>   Message=Invalid URI: 'http://'
>   Source=Titanium.Web.Proxy
>   StackTrace:
>    at Titanium.Web.Proxy.Http.Request.get_RequestUri()
>    at ProxyServer.EventHandlers.ProxyException(Exception exception) in EventHandlers.cs:line 185
>    at Titanium.Web.Proxy.ProxyServer.onException(HttpClientStream clientStream, Exception exception)
>    at Titanium.Web.Proxy.ProxyServer.<handleClient>d__2.MoveNext()
> 
> Inner Exception 1:
> UriFormatException: Invalid URI: The hostname could not be parsed.

![request_ex_output](https://user-images.githubusercontent.com/7310089/69562628-926a7380-0f7d-11ea-9cf0-c8d0eff64175.PNG)

**Comment by honfika** [comment]
Could you please attach the stack trace?

**Comment by ByronAP** [comment]
I can actually duplicate this by simply using a transparent endpoint. I was using explicit when I got it before. I changed to transparent and got the error right away and caught this which i think is what you are looking for.

> at Titanium.Web.Proxy.Http.Request.ParseRequestLine(String httpCmd, String& httpMethod, ByteString& httpUrl, Version& version)
>    at Titanium.Web.Proxy.ProxyServer.<handleHttpSessionRequest>d__196.MoveNext()

**Comment by honfika** [comment]
There is no more stack trace? I'd liket to know from which method is it called.
Can you reproduce it on the windows machine? (Download the site from the same machine as where the proxy is)

**Comment by honfika** [comment]
This is very strange, it looks that it tries to read a line from the encrypted stream. I cannot reproduce this problem with explicit endpoint.

**Comment by ByronAP** [comment]
That last one was on windows. I took the basic example and switched it to use a transparent endpoint and boom it errors right away.

**Comment by ByronAP** [comment]
SEE: https://github.com/ByronAP/Titanium-Web-Proxy/tree/bug-repro 

It looks to be the same issue as i experienced at first but shows up slightly differently with a transparent endpoint.

**Comment by ByronAP** [comment]
here we go

>   at Titanium.Web.Proxy.Helpers.HttpServerStream.<ReadResponseStatus>d__2.MoveNext() in C:\Users\bapen\OneDrive - Cryptomic\Desktop\Titanium-Web-Proxy\src\Titanium.Web.Proxy\Helpers\HttpServerStream.cs:line 50
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
>    at Titanium.Web.Proxy.Http.HttpWebClient.<ReceiveResponse>d__39.MoveNext() in C:\Users\bapen\OneDrive - Cryptomic\Desktop\Titanium-Web-Proxy\src\Titanium.Web.Proxy\Http\HttpWebClient.cs:line 174
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
>    at Titanium.Web.Proxy.ProxyServer.<handleHttpSessionResponse>d__201.MoveNext() in C:\Users\bapen\OneDrive - Cryptomic\Desktop\Titanium-Web-Proxy\src\Titanium.Web.Proxy\ResponseHandler.cs:line 26
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
>    at Titanium.Web.Proxy.ProxyServer.<handleHttpSessionRequest>d__198.MoveNext() in C:\Users\bapen\OneDrive - Cryptomic\Desktop\Titanium-Web-Proxy\src\Titanium.Web.Proxy\RequestHandler.cs:line 341
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
>    at Titanium.Web.Proxy.ProxyServer.<>c__DisplayClass197_0.<<handleHttpSessionRequest>b__1>d.MoveNext() in C:\Users\bapen\OneDrive - Cryptomic\Desktop\Titanium-Web-Proxy\src\Titanium.Web.Proxy\RequestHandler.cs:line 294
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
>    at Titanium.Web.Proxy.Network.RetryPolicy`1.<ExecuteAsync>d__4.MoveNext() in C:\Users\bapen\OneDrive - Cryptomic\Desktop\Titanium-Web-Proxy\src\Titanium.Web.Proxy\Network\RetryPolicy.cs:line 44

**Comment by honfika** [comment]
How can I test this transparent proxy easily on my machime? I always use explicit endpoint.

Could you please reproduce the problem with explicit endppoint? You told me that you got the exception first time with explicit enspoint.

**Comment by ByronAP** [comment]
Setup the basic example to use the transparent endpoint as i did in https://github.com/ByronAP/Titanium-Web-Proxy/tree/bug-repro then grab a copy of postman (https://www.getpostman.com/) and in settings set the proxy to the local machine (127.0.0.1:8000). Then make a get request to https://echo.proxy.services the bug should show up.

**Comment by ByronAP** [comment]
huh weird if i grab the basic example as it is right now from master and I try and get https://echo.proxy.services  it creates a tunnel but nothing else.

**Comment by honfika** [comment]
I got an email, that the master code works, did you delete that comment? Is the master cranch ok?

**Comment by ByronAP** [comment]
I just took the basic example from master, disabled setting it as the system proxy (since I don't want everything going through it) and set the the proxy in postman. When i do that every https request fails. WEIRD

**Comment by ByronAP** [comment]
i deleted it, i was trying some stuff to see what works and what doesn't.

**Comment by honfika** [comment]
Then could you please tell me what sould I configure in postman step by step?

**Comment by ByronAP** [comment]
wrench icon -> settings -> proxy -> 
![Capture](https://user-images.githubusercontent.com/7310089/69645500-43cbe080-1034-11ea-975e-1ee05640c412.PNG)

**Comment by ByronAP** [comment]
no account or anything needed, that is just if you want to save stuff to there cloud sync service.

**Comment by ByronAP** [comment]
weird file -> settings should open that screen above

**Comment by ByronAP** [comment]
went to skype since this is getting too long in here

**Comment by ByronAP** [comment]
closing this... when i find a way to reproduce the initial issue easily will make a new tkt
