### ISSUE TITLE
HTTPS sites fail to open in Edge starting from 3.1.1099

### ISSUE THREAD

**Issue by mrc77** [justcoding121/Titanium-Web-Proxy#685]
Hi, I've found a bug introduced in release 3.1.1099 (3.1.1096 was ok), and still present in the latest beta. If you setup a simple proxy (without "SSL decryption"), some MS tools (Edge, MS Store, WinUpdate, etc) fail to access HTTPS resources (Edge says the certificate is invalid), while other programs (Chrome, Firefox, etc) work fine.

1. Create a .NET Core 3.0 console app, with the following code in the Program.cs file:

```
using System;
using System.Net;
using Titanium.Web.Proxy;
using Titanium.Web.Proxy.Models;

namespace ConsoleProxy
{
    class Program
    {
        static void Main()
        {
            using ProxyServer ps = new ProxyServer(false, false, false);
            ps.AddEndPoint(new ExplicitProxyEndPoint(IPAddress.Any, 8081, false));
            ps.AddEndPoint(new ExplicitProxyEndPoint(IPAddress.IPv6Any, 8081, false));
            ps.Start();
            Console.WriteLine("Running, press any key to exit...");
            Console.ReadKey();
            ps.Stop();
        }
    }
}
```

2. Set the system proxy to "localhost:8081"

3. Open Edge and go to any HTTPS web site

4. If Titanium is >= 3.1.1099 the site won't open

**Comment by honfika** [comment]
This should be fixed, please try the latest package.

**Comment by mrc77** [comment]
I can confirm that this bug has been fixed in the latest release.
Thank you for the quick feedback.
I'm closing this issue.
