### ISSUE TITLE
How use external proxy an Titanium Web Proxy?

### ISSUE THREAD

**Issue by killdns** [justcoding121/Titanium-Web-Proxy#69]
By default, it only works with direct connection to the Internet. How can set it up, that he responsed and received packages through an external proxy?

**Comment by justcoding121** [comment]
Are you saying a reverse proxy?

Just listen on port 80 for http and port 443 for https on your machine.

**Comment by dejanberic** [comment]
I think what he needs, and what I need, is a way to set external proxy for each request that is being made. So, for example, If I set chrome to use proxy 127.0.0.1:8080, and I configure Titanium Web Proxy to listen to 127.0.0.1:8080, I would like to have an ability to set some external proxy for each of those requests from chrome. So in short, my proxy (titanium web proxy) would use another proxy.

**Comment by justcoding121** [comment]
I see. Currently that's not supported.

**Comment by justcoding121** [comment]
Added this feature in latest beta release
```
ProxyServer.UpStreamHttpProxy = new ExternalProxy() { HostName = "someproxy.com", Port = 8888 };
ProxyServer.UpStreamHttpsProxy = new ExternalProxy() { HostName = "someproxy.com", Port = 8888 };
```

[Nuget link for beta](https://www.nuget.org/packages/Titanium.Web.Proxy/2.1.111-beta)

**Comment by dejanberic** [comment]
Have you added an ability to enter username and password for protected proxies?

**Comment by justcoding121** [comment]
We don't really know what type of protection external proxy would be enforcing. It could be basic, digest or even a webpage asking for login.

Its up to the developer to provide the credentials accordingly,
[See this question](http://stackoverflow.com/questions/14284256/how-to-manually-set-upstream-proxy-for-fiddler-core). If you are using basic authentication the second answer would help.

**Comment by parxal** [comment]
string userCredentials = string.Format("{0}:{1}", "user", "password");
string base64UserCredentials = Convert.ToBase64String(Encoding.UTF8.GetBytes(userCredentials));
oSession.RequestHeaders["Proxy-Authorization"] = "Basic " + base64UserCredentials;

RequestHeaders is Dictionary<string, HttpHeader> so it should be : 
oSession.RequestHeaders["Proxy-Authorization"] =  new HttpHeader("Basic ",base64UserCredentials);

Need Help. It does not work...

**Comment by parxal** [comment]
Sorry this must be old, because now you can just

_proxyServer.UpStreamHttpProxy = new ExternalProxy() { HostName = ip, Port = port };
_proxyServer.UpStreamHttpsProxy = new ExternalProxy() { HostName = ip, Port = port };                  
_proxyServer.UpStreamHttpsProxy.UserName =userName;
_proxyServer.UpStreamHttpsProxy.Password = password;
_proxyServer.UpStreamHttpProxy.UserName = userName;
_proxyServer.UpStreamHttpProxy.Password = password;
