### ISSUE TITLE
Bypass URLs from decrypting with Transparent Proxy.

### ISSUE THREAD

**Issue by harrip12** [justcoding121/titanium-web-proxy#705]
Hello,
       I am using Titanium Web Proxy as a Transport Proxy. It is decrypting all the URLs, because of this some of the websites and Intranetworking sites are having trust issue, it shows the message "Your connection is not private/secure".

Please help me out to resolve this issue.

**Comment by honfika** [comment]
Subscribe to proxyServer.BeforeSslAuthenticate
and set the args.DecryptSsl to false.

Alternatively you can disable it globally for your endpoint in the TransparentProxyEndPoint object.
