### ISSUE TITLE
Set upstream endpoint broken in latest build

### ISSUE THREAD

**Issue by ByronAP** [justcoding121/Titanium-Web-Proxy#716]
The latest version seems to have broken setting the upstream endpoint. No idea why though...

// output from my test
INFO: Caller from 41.150.65.200
INFO: Using 41.150.65.200 as upstream endpoint.
WARN: Remote address detected 100.129.224.118

**Comment by honfika** [comment]
Is this a free open proxy? On what port?

Fro me it seems to work on localhost with Fiddler upstream proxy.

**Comment by honfika** [comment]
Sorry, I was forget to add a Bind when refactored the server connectio factory beause of the Socks support. New package will be released in 10 minutes.

**Comment by ByronAP** [comment]
FIXED ty
