### ISSUE TITLE
Large files download fail

### ISSUE THREAD

**Issue by kinezikupovina** [justcoding121/Titanium-Web-Proxy#72]
Connection gets broken when downloading big files, for instance http://saimei.acc.umu.se/debian-cd/current/amd64/iso-dvd/debian-8.4.0-amd64-DVD-1.iso

**Comment by justcoding121** [comment]
Fixed in latest beta release

[Nuget link for beta](https://www.nuget.org/packages/Titanium.Web.Proxy/2.1.111-beta)
