### ISSUE TITLE
Failed to save fake certificate error

### ISSUE THREAD

**Issue by johnprice820** [justcoding121/Titanium-Web-Proxy#735]
Hello, I upgraded my project from 3.1.1270 to 3.1.1276 and am now receiving an error during the ProxyServer.Start() method. I have ProxyServer.CertificateManager.SaveFakeCertificates = true as well. When this runs, I'm catching an exception with the error message of "Failed to save fake certificate." 

I searched the code base and found the message located here:
https://github.com/justcoding121/Titanium-Web-Proxy/blob/master/src/Titanium.Web.Proxy/Network/CertificateManager.cs

Can you help?

Thanks, John

**Comment by honfika** [comment]
Please try the latest beta package

**Comment by johnprice820** [comment]
That fixed the issue. Thank you for the prompt response.
