### ISSUE TITLE
PR_END_OF_FILE_ERROR in Firefox

### ISSUE THREAD

**Issue by markszente** [justcoding121/Titanium-Web-Proxy#739]
Hello,

I am trying to implement Titanium Web Proxy with Selenium, using FirefoxDriver. Plain HTTP works perfectly, but HTTPS results in a `PR_END_OF_FILE_ERROR` error in Firefox. 

Any idea what may cause this? Root certificate is trusted.

Thanks, and sorry if I've missed something obvious.

**Comment by markszente** [comment]
It seems that I used .net core 2.0, upgrading solved the issue.

**Comment by honfika** [comment]
Cool.... so there is a bug in .NET Core 2.0 which was fixed in 3.x... good to know...

**Comment by vflame** [comment]
Just an FYI for folks out there, this is resolved by setting the default certificate engine and calling EnsureRootCertificate.
