### ISSUE TITLE
https requests are not getting through proxy server

### ISSUE THREAD

**Issue by amitbhutta** [justcoding121/Titanium-Web-Proxy#74]
Hi, I'm working on a project where I need to create a proxy server to handle the web traffic (both http and https). Using the Titanium web proxy, i am able to handle the http requests but https are not working and I am getting empty string value for httpCmd at line 98 on requesthandler.cs while processing the https requests (e.g. google.com). Due to which request is not being generated. I have a project very much similar to the titanium test project except I'm not using any explicit end points or transparent end points. Can you please advise what could be the reason for that? Much appreciated!! Thanks.

**Comment by justcoding121** [comment]
Https request should work. Did you make sure that makecert.exe is copied to your application directory?

**Comment by amitbhutta** [comment]
Yes, it is copied.

**Comment by mgerasika** [comment]
I have some problem.But after run vs in administrative rights all works for me.

**Comment by amitbhutta** [comment]
I got that working.. It was missing upstream proxy settings for HTTPS, that's why was not working. Thanks!
