### ISSUE TITLE
Getting size of SSL response

### ISSUE THREAD

**Issue by Arcanaeum** [justcoding121/Titanium-Web-Proxy#741]
Hi, for my use case I need to measure the size of incoming responses, both with and without SSL. It's easy enough to enable SSL decryption, and then count header size and body size in OnAfterRequest. But I've noticed that decrypting SSL adds an overhead of roughly 800ms to every SSL request (on windows, at least). The specs of the computer are most definitely high enough that I am convinced it is not a CPU power issue. Additionally, for SSL requests this counts the decrypted size, not the actual encrypted response size. While this is okay, for my use case it would be better if I could record the size of the encrypted response.

Is there a way to achieve what I need without decrypting SSL? Or am I going to have to suck it up and accept the additional overhead in responsiveness.

**Comment by justcoding121** [comment]
May be #626 will help. Sounds related.

**Comment by Arcanaeum** [comment]
Thanks! This was exactly what I needed. I somehow managed to miss that previous issue.
