### ISSUE TITLE
How do I get just one Web address to use titanium-web-proxy

### ISSUE THREAD

**Issue by LexiSong67** [justcoding121/Titanium-Web-Proxy#742]
@honfika 
Hi,
How do I get just one Web address to use titanium-web-proxy?
For example: you just want http://www.baidu.com to go titanium-web-proxy, and all other sites don't go Proxy.

**Comment by honfika** [comment]
Hi,

You can confugure this with a PAC file in your browser:
https://en.wikipedia.org/wiki/Proxy_auto-config

**Comment by honfika** [comment]
I close this issue, feel free to reopen if needed.
