### ISSUE TITLE
How Find Mac Address and HostName Of Client ?

### ISSUE THREAD

**Issue by mbtolou** [justcoding121/Titanium-Web-Proxy#746]
How Find Mac Address and HostName Of Client ?

**Comment by honfika** [comment]
This is not a TWP question.

Check for example this:
https://www.experts-exchange.com/questions/24815535/Get-MAC-Address-of-remote-IP-Address-on-local-network-using-C.html

and:
https://docs.microsoft.com/en-us/dotnet/api/system.net.dns.gethostentry?view=netframework-4.8

You can get the mac address only if you are in the same local network.
