### ISSUE TITLE
Interface Binding/Upstream proxy support

### ISSUE THREAD

**Issue by vflame** [justcoding121/Titanium-Web-Proxy#75]
Does/will Titanium Web Proxy support binding to specific NICs? I'm interested in using this library to replace Fiddler but desire the ability to specify which NIC/interface to bind traffic to (http://fiddler.wikidot.com/egressip). Also interested in upstream proxy support as well (e.g., client -> titanium -> socks/http proxy - > server)

**Comment by justcoding121** [comment]
Currently we do not support binding to specific NICs for outgoing traffic. However you can bind to specific NICs (using its IP address) for incoming traffic by specifying it in EndPoint initialization.

Upstream proxy is supported, but not to socks proxy.

**Comment by ilushka85** [comment]
Just wanted to let you know that upstream proxy support is built in now.

**Comment by justcoding121** [comment]
Also currently supports Binding to Specific local IP address via [UpStreamEndPoint](https://github.com/justcoding121/Titanium-Web-Proxy/blob/develop/Titanium.Web.Proxy/ProxyServer.cs#L124) property of proxy server.
