### ISSUE TITLE
Can i use library as fake web server ?

### ISSUE THREAD

**Issue by mbtolou** [justcoding121/Titanium-Web-Proxy#751]
Hi,

Can i use library as fake web server (whitout set proxy server)?  

for example:
can i open port 127.0.0.1:9000 and send all urls to "http://www.example.com"  ?

http://127.0.0.1:9000/test -------> http://www.example.com/test

**Comment by honfika** [comment]
Yes

**Comment by mbtolou** [comment]
can you write example code ?

**Comment by honfika** [comment]
Please check the example code:
https://github.com/justcoding121/Titanium-Web-Proxy/blob/master/examples/Titanium.Web.Proxy.Examples.Basic/ProxyTestController.cs

I think you need a transparent endpoint and change the url in the beforerequest handler.

**Comment by Minx-SigEp** [comment]
Another Library I have used with success is WireMock.Net. Its goal of WireMock is much different than Titanium. Both tools are very good and can solve different problems. 

https://www.nuget.org/packages/WireMock.Net/
https://github.com/WireMock-Net/WireMock.Net

```C#
using Microsoft.VisualStudio.TestTools.UnitTesting;
using WireMock.Server;

namespace Infrastructure.Http.Test.Unit
{
    // https://www.meziantou.net/2018/02/12/mstest-v2-test-lifecycle-attributes
    // https://blogs.msdn.microsoft.com/nnaderi/2007/02/01/comparing-the-mstest-and-nunit-frameworks/
    [TestClass]
    public class HttpServer
    {
        public static FluentMockServer Instance { get; private set; }

        [AssemblyInitialize]
        public static void AssemblyInitialize(TestContext context)
        {
            // https://github.com/WireMock-Net/WireMock.Net/wiki/Stubbing-and-Request-Matching
            // https://alastaircrabtree.com/stubbing-your-way-to-automated-e2e-testing-api-first-with-wiremock/
            Instance = FluentMockServer.Start();
        }

        [AssemblyCleanup]
        public static void AssemblyCleanup()
        {
            Instance.Stop();
            Instance.Dispose();
            Instance = null;
        }
    }
}

```

**Comment by mbtolou** [comment]
> Please check the example code:
> https://github.com/justcoding121/Titanium-Web-Proxy/blob/master/examples/Titanium.Web.Proxy.Examples.Basic/ProxyTestController.cs
> 
> I think you need a transparent endpoint and change the url in the beforerequest handler.

Thanks.
