### ISSUE TITLE
Catch Files Stream Uploading Through Proxy to online storage or email storage.

### ISSUE THREAD

**Issue by surendharb** [justcoding121/Titanium-Web-Proxy#752]
@honfika  @justcoding121 

I was trying to intercept files being uploaded into online storage or email. Right now I can able to intercept the upload request with some logic of filename and extension validation.

I need some suggestion on below items.

Is there any way to get the file stream(File uploading) from HTTPS Request?, So I can monitor what is the file which he tried to upload.

Is there any way to find in HTTPS Request files being uploading. So I can intercept this request easily. As i said early file extension validation is restricted to only some file types, because we cannot scale all of the file format which is available.

**Comment by honfika** [comment]
So the problem is that the file is too big, and you want a stream, it is not possible to load the whole file in memory?

**Comment by surendharb** [comment]
I don't care about the memory, as long as I can able to detect the file upload into online.

**Comment by honfika** [comment]
please check the sample project:
https://github.com/justcoding121/Titanium-Web-Proxy/blob/02541efdad00962e868776efff41c49a4a8590f5/examples/Titanium.Web.Proxy.Examples.Basic/ProxyTestController.cs#L320-L363

`var bodyBytes = await e.GetResponseBody();`

**Comment by honfika** [comment]
Sorry, I linked wrong method, this is the onResponse, but it is the dame for the request.. you can read the body in a same way.

**Comment by surendharb** [comment]
Thanks @honfika for your comments. It will helps me a lot.
Is there any way can we get name of the File or the Directory where it choose from.
I only know how to get the Process ID from the request.

**Comment by honfika** [comment]
The filename should be there, but i think the directory name is not in the HTTP traffic..
