### ISSUE TITLE
dotnet global tool

### ISSUE THREAD

**Issue by mungojam** [justcoding121/Titanium-Web-Proxy#755]
Great library! 

I plan to use it as a bridge between apps that can't handle windows auth and a corporate proxy that requires windows auth. I will probably start with your example console app which should do the job.

But I wondered if you could also provide a dotnet global tool version of it. That would make it really easy to get started with it. I later plan to extend it for more advanced purposes.

I can have a go at doing it myself if you'd be up for adding it?

**Comment by honfika** [comment]
What should I do for adding that global tools?

I can merge PRs, but for other actions I think you need to ask @justcoding121

**Comment by ByronAP** [comment]
@mungojam are you talking about this? https://www.dotnetcurry.com/dotnet/1495/dotnet-core-global-tools

**Comment by mungojam** [comment]
I was talking about that but now I've changed my mind as I think it's better to wait for .net 5 and make a single exe version. I also saw that this library doesn't have Kerberos authentication support (I think), so it won't suit my needs in current form. Sorry I haven't got time at the moment to help move it forward
