### ISSUE TITLE
Question: 304

### ISSUE THREAD

**Issue by myangelkamikaze** [justcoding121/Titanium-Web-Proxy#756]
`Response body is not read yet. Use SessionEventArgs.GetResponseBody() or SessionEventArgs.GetResponseBodyAsString() method to read the response body.
at Titanium.Web.Proxy.Http.Response.EnsureBodyAvailable(Boolean throwWhenNotReadYet)
at Titanium.Web.Proxy.EventArguments.SessionEventArgs.GetResponseBody(CancellationToken cancellationToken)`

(I have no idea how to post a stack trace)

I've been getting this exception when trying to read the response body in the BeforeResponse handler. The exception makes no real sense because I'm always using GetResponseBody. What I did notice after a while is that this only happens on response status 304.

Is it possible that GetResponseBody is failing because of 304?

**Comment by honfika** [comment]
Yes, it is because of 304.... it has no body.

**Comment by myangelkamikaze** [comment]
If it's not too much work, would it be possible to add a better exception for cases like this? Though this issue might be enough already. Thanks for the clarification!

**Comment by honfika** [comment]
Added: https://github.com/justcoding121/Titanium-Web-Proxy/commit/f2076892c676ba5e8ca1627e9984da1f75612b26

**Comment by honfika** [comment]
I close this issue.. feel free to reopen if needed.
