### ISSUE TITLE
Why there are Chinese garbled 为什么会有中文乱码呢

### ISSUE THREAD

**Issue by soDLL** [justcoding121/Titanium-Web-Proxy#757]
i do this:
e.HttpClient.Response.ContentType = "application/json;charset=UTF-8";
byte[] bData = Encoding.Default.GetBytes("{\"data\":\"chinese中文test\"}");
string body = Encoding.UTF8.GetString(bData);
e.Ok(body);

then  i access target url
the result is 
"chinese????test"
why?  whan can i do ?

**Comment by honfika** [comment]
why do you convert the string to byte[] than back to string?

Try this:
`                e.Ok("{\"data\":\"chinese中文test\"}" , new Dictionary<string, HttpHeader> {{"Content-Type", new HttpHeader("Content-Type", "application/json;charset=UTF-8") }});
`

**Comment by soDLL** [comment]
hi i do this:
public static void ResponseJsonStr(SessionEventArgs e, string jsonStr)
        {
            LogHelper.showLog(jsonStr);

            //byte[] bData = Encoding.Default.GetBytes("{\"data\":\"chinese中文test\"}");
            byte[] bData = Encoding.Default.GetBytes(jsonStr);
            e.HttpClient.Response.ContentType = "application/json;charset=UTF-8";
            byte[] bDataUtf8 = Encoding.Convert(Encoding.Default, Encoding.UTF8, bData);
            e.Ok(bDataUtf8);
            //string body = Encoding.UTF8.GetString(bDataUtf8);
            //e.Ok(body);  // 参数是字符串的话 会产生中文乱码
        }
now it is ok
Thank you for reply

**Comment by honfika** [comment]
This line is useless:
`e.HttpClient.Response.ContentType = "application/json;charset=UTF-8";`

Since you respond with .Ok(), and it creates a new resposne ofbject, so anything you set in the e.HttpClient.Response is ignored.

**Comment by soDLL** [comment]
Turned out to be so, now I understand, thank you
