### ISSUE TITLE
Certificate Issue for Particular Websites

### ISSUE THREAD

**Issue by surendharb** [justcoding121/Titanium-Web-Proxy#761]
Recently I was navigating this particular website https://www.iditect.com/ using titanium Proxy.
For some reason this website was not loaded, Then I browsed without Titanium this website was opening. I found this issue through crome.
![image](https://user-images.githubusercontent.com/33457694/80865645-64b1f500-8ca8-11ea-822b-d3710a19fef2.png)

I think the problem is with the certificate what we creating.

I there anyway to skip issuing certificate and  allow with load their own certificates, if any problem occurs.

**Comment by honfika** [comment]
This problem shuold be fixed in the latest package with enabled ssl decryption.

> I there anyway to skip issuing certificate and allow with load their own certificates, if any problem occurs.

Yes, you can always disable the SSL decryption for any particular website with the following code:

```
            explicitEndPoint.BeforeTunnelConnectRequest += onBeforeTunnelConnectRequest;

        private async Task onBeforeTunnelConnectRequest(object sender, TunnelConnectSessionEventArgs e)
        {
            string hostname = e.HttpClient.Request.RequestUri.Host;

            if (hostname.Contains("dropbox.com"))
            {
                // Exclude Https addresses you don't want to proxy
                // Useful for clients that use certificate pinning
                // for example dropbox.com
                e.DecryptSsl = false;
            }
        }
```

Of course if you set this, you won't be able to see/modify the decrypted traffic, loaded urls.

**Comment by honfika** [comment]
I close this issue, feel free to reopen if needed.
