### ISSUE TITLE
What can I do to ignore the certificate check? 如何忽略证书错误

### ISSUE THREAD

**Issue by ghost** [justcoding121/Titanium-Web-Proxy#762]
Hello, I've had a certificate error.
I want to ignore the certificate error, 
I don't need to check that the certificate is correct
What can I do to ignore the certificate check?

the error info:
Titanium.Web.Proxy.Exceptions.ProxyHttpException: Error occured whilst handling session request 
---> System.Security.Authentication.AuthenticationException: 根据验证过程，远程证书无效。
   在 System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   在 System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
   在 System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
   在 System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)

**Comment by honfika** [comment]
Please check the sample code for disabling the certificate validation.

**Comment by soDLL** [comment]
thank you 
i see it
i do this is ok

 mProxyServer.ServerCertificateValidationCallback += OnCertificateValidation;

 /// <summary>
        ///     Allows overriding default certificate validation logic
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        public async Task OnCertificateValidation(object sender, CertificateValidationEventArgs e)
        {

            // set IsValid to true/false based on Certificate Errors
            //if (e.SslPolicyErrors == System.Net.Security.SslPolicyErrors.None)
            //{
            //    e.IsValid = true;
            //}

            e.IsValid = true; // 不用验证网站证书
        }

**Comment by honfika** [comment]
I close this issue, feel free to reopen if needed.
