### ISSUE TITLE
Can I modify the header?

### ISSUE THREAD

**Issue by bbhxwl** [justcoding121/Titanium-Web-Proxy#785]
Can I use e.HttpClient.Request.Headers in onRequest to modify the submitted header?

**Comment by honfika** [comment]
Yes.

**Comment by honfika** [comment]
Do you need help? Header modification is easy, jsut use intellisense, and you will se the Add/Remove methods.
May I clsoe this issue?

**Comment by honfika** [comment]
The question was answered, so I close this issue.
