### ISSUE TITLE
Option to use dummy certificate

### ISSUE THREAD

**Issue by danieljohannsen** [justcoding121/Titanium-Web-Proxy#79]
In a scenario using Titanium with a server application where all certificate errors are ignored, it would benefit proxy performance if the certificate creation could be bypassed by using a custom dummy certificate, loaded from a PFX-file on initialization - this certificate could for instance be returned on all calls to the CertificateManager.CreateCertificate method.

This would also solve the pain of not being able to install the root certificate on a server automatically since manual accept of the initial root certificate installation is required by design.

**Comment by justcoding121** [comment]
I think we do that with the 'genericCertificateName' property for transparent end points. May be we can do that for ExplicitEndPoints as well.

But currently the certificate file have to be in the local store.
