### ISSUE TITLE
Handshake fails for the WebSocket while utilizing the TransparentEndPoint

### ISSUE THREAD

**Issue by ardroh** [justcoding121/Titanium-Web-Proxy#792]
Hi,

In my app, I have difficulties with establishing WebSocket handshake while utilizing TransparentEndPoint. The connection fails each time. 
I have made a closer Wireshark analysis:

- The browser request is properly forwarded to the webserver by the Proxy, 
- The web server response (HTTP/1.1 101) is transferred to the Proxy but **it is not** forwarded to the Browser.

While debugging own code and the Titanium-Web-Proxy library I have traced the issue to this line inside of the **src/Titanium.Web.Proxy/WebSocketHandler.cs**:
```
if (!args.IsTransparent)
{
    await clientStream.WriteResponseAsync(response, cancellationToken);
}
```
after removing the `if` the web socket connection seems to be established correctly by the embedded Chromium.

Could you please tell me what is the purpose of that check and could this be removed from the library code? 

ver. 3.1.1301

**Comment by honfika** [comment]
Good question, it seems to be a bug, since thw response should be sent in transparent mode, too.
I remove that.

Transparent mode is not really tested.. at least by me:(

By the way, do you use .net core/.net 5 or the old .net 4.x famework?

**Comment by ardroh** [comment]
Thanks for the quick feedback!
I'm sticking with the older .net framework for now (4.7.2 to be exact).

**Comment by honfika** [comment]
I created a beta nuget package, so you can sue that.
I close this issue, feel free to reopen if needed.
