### ISSUE TITLE
Youtube and vimeo videos don't play

### ISSUE THREAD

**Issue by mergoktas** [justcoding121/Titanium-Web-Proxy#8]
i am testing this software time to time. 
Youtube and vimeo videos don't play while this proxy running.

**Comment by titanium007** [comment]
Can you elaborate? 

Another OP had reported the same problem earlier. But it works for me.

Which browser are you using (Firefox won't work unless you import the Root Certificate)
Antiviruses/firewall allowing proxy to listen for HTTPS? 
Are you running the proxy on a remote machine?

If all these are on right track, then your only option is to debug the specific request "youtube.com" by putting break point on your visual studio. And then let me know if you find anything causing the problem on debugging.

**Comment by mergoktas** [comment]
Directly tested the downloaded solution file with vs2010 on win7
1.I tested with three different browser which are ie, chrome and yandex.2.It works for some HTTPS sides.3.Performance really degrades when running proxy.4. Even some sides don't show up properly. You can check this news side, before and after running the proxy. Rota haber - Güncel Haber - Haber - En Son Haber - İnternet Haber - Sıcak haber - Yerel Haberler - Spor Haberleri
|   |
|   |  |   |   |   |   |   |
| Rota haber - Güncel Haber - Haber - En Son Haber - İnter...güncel haberler, son dakika haberleri, ensonhaber, flaş haber, internet haber, sıcak haber, doğru haber, haber sitesi, gazete, magazin, spor, foto galeriler |
|  |
| View on www.rotahaber.com | Preview by Yahoo |
|  |
|   |

5.TrotiNet is also another open source (c#) proxy. It does not use any external file for security issues like makecert.exe something and vary fast. But the futures exposed to programmers are not easy going like yours. For instance not possible to get the url and request body. Any way it makes me consider that the issue is laying under the external files related with security. I have also  Fiddler4 installed on my machine.
Can you make it like TwotiNet, without any dependency to any external file?6. I don't exactly understand the SessionEventArgs Decode() and Ok(html) purposes.If you comment some line like below
public void OnRequest(object sender, SessionEventArgs e)        {// string Random = e.RequestURL.Substring(e.RequestURL.LastIndexOf(@"/") + 1); // int index = _URLList.IndexOf(Random); // if (index >= 0)            {
                string URL = e.Decode();
                if (_lastURL != URL)                {                    OnChanged(new VisitedEventArgs() { hostname = e.Hostname, URL = URL, remoteIP =                         e.ipAddress, remotePort = e.Port });
                }
                e.Ok(null);                _lastURL = URL;            }}
then Decode() doesn't work properly. It sounds to me that if there is no any response before, then Decode() and Ok() should be called. If so, why?  is my understanding is wrong or not?
That's all now. Sorry for long answer.
Muharrem 


     On Wednesday, July 8, 2015 9:39 PM, titanium007 <notifications@github.com> wrote:
   

 Can you elaborate? Another OP had reported the same problem earlier. But it works for me.Which browser are you using (Firefox won't work unless you import the Root Certificate)
Antiviruses/firewall allowing proxy to listen for HTTPS? 
Are you running the proxy on a remote machine?If all these are on right track, then your only option is to debug the specific request "youtube.com" by putting break point on your visual studio. And then let me know if you find anything causing the problem on debugging.—

**Comment by titanium007** [comment]
I think I overlooked some of the major bugs in the code as far as e.Decode() is concerned. I am going to mark this project as still in development. I will get back once I make the breaking changes one day soon.

**Comment by titanium007** [comment]
1) Decode not working

Give a try for decode now. I changed the Api, 
Use GetRequestHtmlBody and SetRequestHtmlBody. 

2) Performance

The site you gave is slow regardless of proxy. However it loads in my machine. Tell me if the performance degrades now. I made some changes.

**Comment by mergoktas** [comment]
I just downloaded the latest version and run the sample, without touch anything else, but it is very very slow. 
Taking even minutes and a little things (even nothing) coming out to browser. 

PS. I opened the solution file with vs2010 and built.
Before run the app, I cleared the ie proxy setting and on the command line run
>netsh winhttp reset proxy

**Comment by titanium007** [comment]
Thanks for testing.

While there is scope for improvement, your contention that nothing is working made me think something was wrong in the test project.

I simplified it. Give it a try when you get time.

**Comment by titanium007** [comment]
The title of this issue is misleading. Youtube works perfectly fine on the boxes I tested. Apparently OP is talking about performance degradation. It is addressed in issue #10

**Comment by mergoktas** [comment]
bool certTrusted = CertManager.CreateTrustedRootCertificate();returns false. Therefore for SSL (https) sites, it does not register itself as proxy server. If I register it for secure sites by manual through ie internet options, proxy server does not work.Browsers are giving time out error.
P.S : I removed all the certificates of DO_NOT_TRUST_FiddlerRootthen reboot and made test. Please make your test when system proxy set is done for both http and https.   


     On Saturday, July 25, 2015 1:47 AM, titanium007 <notifications@github.com> wrote:
   

 The title of this issue is misleading. Youtube works perfectly fine on the boxes I tested. Apparently OP is talking about performance degradation. It is addressed in issue #10 —

**Comment by mergoktas** [comment]
Yesterday I downloaded it again, unzipped, open with vs 2015 community edition and rebuilt.
Run in debug mode and run outside the visual studio, monitoring the  HTTPS too.
Result is same. not possible to connect any HTTPS side, even to hotmail.
My box is win7 home premium. Is it necessary take some actions before running?
What am I missing or something is wrong with certificate issues?

Null exception with the message "Value cannot be null.Parameter name: serverCertificate"
and stack trace as follows
   at System.Net.Security.SslState.ValidateCreateContext(Boolean isServer, String targetHost, SslProtocols enabledSslProtocols, X509Certificate serverCertificate, X509CertificateCollection clientCertificates, Boolean remoteCertRequired, Boolean checkCertRevocationStatus, Boolean checkCertName)
   at System.Net.Security.SslStream.AuthenticateAsServer(X509Certificate serverCertificate, Boolean clientCertificateRequired, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation)
   at Titanium.Web.Proxy.ProxyServer.HandleClient(TcpClient Client) in C:\Deneme\Titanium-master-2015\Titanium-master\Titanium.Web.Proxy\RequestHandler.cs:line 138
   at Titanium.Web.Proxy.ProxyServer.<>c__DisplayClass59_0.<Listen>b__0() in C:\Deneme\Titanium-master-2015\Titanium-master\Titanium.Web.Proxy\ProxyServer.cs:line 149
   at System.Threading.Tasks.Task.Execute()


at the following line
 //Successfully managed to authenticate the client using the fake certificate
 slStream.AuthenticateAsServer(_certificate, false, SslProtocols.Tls | SslProtocols.Ssl3 | SslProtocols.Ssl2, false);
                        

PS: Selecting Yes to monitor the HTTPS does not set it as proxy server for HTTPS. I done it
manually through IE internet options.

**Comment by mergoktas** [comment]
I don't understand, why you have labeled this discussion as invalid, but  I figured out the reason.
My computer works with English version but with Turkish locale. Date time format in CertCreateFormat  string is for US locale format, causing to crash of makecert.exe. So I cancelled the -b flag for makecert.exe since default date time is current time. 
 //private const string CertCreateFormat =
        //    "-ss {0} -n \"CN={1}, O={2}\" -sky {3} -cy {4} -m 120 -a sha256 -eku 1.3.6.1.5.5.7.3.1 -b {5:MM/dd/yyyy} {6}";
 private const string CertCreateFormat =
                    "-ss {0} -n \"CN={1}, O={2}\" -sky {3} -cy {4} -m 120 -a sha256 -eku 1.3.6.1.5.5.7.3.16}"; 

Now it is working. As a result CertCreateFormat should be in current locale, not fixed to US locale.

Great work, any way.
Many thanks,

Muharrem

**Comment by titanium007** [comment]
Apologies, I thought its some networking issue. Thanks for reporting this.

**Comment by mergoktas** [comment]
Some more items (kindly).
1.Lets say I am interested in  only  some http or https sites. can I make proxing for only those web sites with titanium or any other settings on the computer?
2.When the web proxy turned on please check the www.yahoo.com. Try to select some items to see them. When I try that I am getting a page showing "Hmm, we can't reach this page." from remote site. I looks like that some requests are not being sent to remote server correctly. Or I guess so maybe. But when you stop the proxy server every thing comes to its own normal life.
3.when you refresh (ie) or reload (chrome) no data received from server while the proxy server is running. 

Please check

**Comment by titanium007** [comment]
1) Not really. That's because browser sends all requests to the proxy when system proxy settings are changed. However notice that if you are not modifying the request or response we are literally relaying the request without reading request/response body. 

2) 3) Will check later

**Comment by mergoktas** [comment]
1.For some sites, if you make refresh/reload that means soft refresh, page dose not refresh as it should be. Page layout is somehow weird. But if you make hard refresh/reload that means Ctrl+F5 then the page is Ok as it should be. Check it from the sites:
http://news.yahoo.com/
http://www.rotahaber.com

yahoo site say that "Flash is blocked from loading", but with Ctrl+F5 it gets everything OK..
2. I only need to inspect and modify the contents of some site's pages especially for https.
So I added a Property of type List, named as IncludedHttpsHostNameRegex , smiliar to ExcludedHttpsHostNameRegex.Any and made the following changes

//var excluded = ExcludedHttpsHostNameRegex.Any(x => Regex.IsMatch(httpRemoteUri.Host, x));
var included = IncludedHttpsHostNameRegex.Any(x => Regex.IsMatch(httpRemoteUri.Host, x));

 //Client wants to create a secure tcp tunnel (its a HTTPS request)
 //if (httpVerb.ToUpper() == "CONNECT" && !excluded && httpRemoteUri.Port == 443)
 if (httpVerb.ToUpper() == "CONNECT" && included && httpRemoteUri.Port == 443)
{

........
}
So I do only deal with the  https sites that I am interested in and rest of the others go in their own way. I mean proxy server just relay them, no certification etc.

Am I on the true way or am I mistaken?

**Comment by titanium007** [comment]
Your issue with news.yahoo.com and yahoo.com was fixed. Also fixed error with certificate creation.

**Comment by titanium007** [comment]
What you should do to relay websites is to add below code at line 52 of RequestHandler.cs. 

```cs
               if(!included)
                {
                    clientStreamReader.ReadAllLines();
                    WriteConnectResponse(clientStreamWriter, httpVersion);
                    TcpHelper.SendRaw(clientStreamReader.BaseStream, null, null, httpRemoteUri.Host, httpRemoteUri.Port,
                        false);
                    Dispose(client, clientStream, clientStreamReader, clientStreamWriter, null);
                    return;
                }
```

**Comment by titanium007** [comment]
I think [StackOverflow](http://stackoverflow.com/questions/tagged/titanium-web-proxy) would be a better place to address your questions about inclusion/exclusion. Make sure you ask with a Titanium-Web-Proxy as hashtag.

**Comment by titanium007** [comment]
Actually your request is an enhancement. I will add a feature to allow hosts to be bypassed by the proxy.

**Comment by mergoktas** [comment]
Another question is  how to create the certificate uniquely per-computer like Fiddler creates per each installation? I think CertCreateFormat string should be changed somehow but unfortunately I am not an expert on that so  I could not resolve what to do on that string.

**Comment by justcoding121** [comment]
We can add feature to create root certificate on fly in future.

**Comment by justcoding121** [comment]
Certificates are generated on fly as of now
