### ISSUE TITLE
Problem with restrarting titanium web proxy

### ISSUE THREAD

**Issue by voshod-nerd** [justcoding121/Titanium-Web-Proxy#81]
I use the latest version of nuget packet Titanium Web Proxy. Thera are some problem with stop titanium  proxy server. If I do method stop(), and then use start(), then windows show me next message 
"An unhandled exception of type 'System.Net.Sockets.SocketException' occurred in System.dll

Additional information: Usually allowed only one usage of each socket address (protocol / network address / port )" 
if i close program, and run again all fine. 
Thanks you for your answers!

**Comment by justcoding121** [comment]
Fixed in beta nuget package release
