### ISSUE TITLE
bug -- BeginAcceptTcpClient/EndAcceptSocket

### ISSUE THREAD

**Issue by jgilbert2017** [justcoding121/Titanium-Web-Proxy#810]
there is mismatched BeginAccept/EndAccept in ProxyServer.cs.  BeginAcceptTcpClient is being called and then EndAcceptSocket.  It should be calling BeginAcceptSocket() in 2 places.  .net 5.0 is intolerant of this.

**Comment by honfika** [comment]
thanks, fixed

**Comment by jgilbert2017** [comment]
no prob, thanks for putting so much effort into a great project!
