### ISSUE TITLE
Net 5.0 Support

### ISSUE THREAD

**Issue by vuminhquang** [justcoding121/Titanium-Web-Proxy#811]
Hello,
I tested Titanium with Net 5.0. Seems that the proxy not work
<TargetFrameworks>net5.0</TargetFrameworks>

1. Rebuilt with no problem
2. Start proxy server instance:
listen(endPoint) -> passed with port opened
3. Tested by using proxy as system proxy: no connection could be made.

Sincerely

**Comment by CRC32EX** [comment]
Same here.

# Windows
`net5.0` and version `3.1.1301` is not working on my environment.
But, `net5.0` and version `3.0.684` is working on my environment.

```ps1
dotnet add package Titanium.Web.Proxy --version 3.0.684
```

**HttpProxyServer.csproj**
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Titanium.Web.Proxy" Version="3.0.684" />
  </ItemGroup>

</Project>

```

![image](https://user-images.githubusercontent.com/25629617/99353399-c570ea00-28e7-11eb-9d74-5a77ab8c0e80.png)

### Environment
- Windows 10 1903 64bit 18362.1082
- dotnet --version
5.0.100
- proxy check application
Proxifier

# Linux
Version is not matter.

`net5.0` and version `3.1.1301` is not working on my environment.
`net5.0` and version `3.0.684` is not working on my environment.

`netcoreapp3.1` and version `3.1.1301` is working on my environment.
`netcoreapp3.1` and version `3.0.684` is working on my environment.

### proxy test
I'm wait 1 minutes, but no response on `net5.0`
```
curl http://api.ipify.org/ -x http://127.0.0.1:1234
```

### Environment
- cat /etc/lsb-release
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.1 LTS"
```

- dotnet --version
5.0.100

**Comment by vuminhquang** [comment]
Hello,
Tested on Windows, latest running version is 3.1.1218.

Thanks CRC32EX

**Comment by honfika** [comment]
please try te latest package

**Comment by vuminhquang** [comment]
tested the latest package, can run on Windows. Thanks @honfika , @justcoding121
