### ISSUE TITLE
Can not create certificate in 3.1.1341

### ISSUE THREAD

**Issue by topfunet** [justcoding121/Titanium-Web-Proxy#815]
I just upgrade Titanium to 3.1.1341, found there is a bug.
When i call EnsureRootCertificate, a error come out and says "Could not install certificate as it is null or empty.".

**Comment by honfika** [comment]
Which target framework, architecture, OS?
Can you reproduce it with the sample project? If not, then please provide a code to reproduce the problem.

**Comment by topfunet** [comment]
Just create a console project target .netcore3.1 or .net5.0, put this line in Main function then run this project you will see error.

`new ProxyServer().CertificateManager.EnsureRootCertificate();`

OS: Window 10 1909
VS: Visual Studio 2019 (16.8.1)
Framework: .NetCore3.1.10 and .Net5.0.0

I hope this helps.

**Comment by honfika** [comment]
thanks... fixed.. please try the latest package
