### ISSUE TITLE
Microsoft Teams not working while proxy is used.

### ISSUE THREAD

**Issue by Rouanvdw** [justcoding121/Titanium-Web-Proxy#819]
When the users uses the titanium proxy and tries to login to Microsoft Teams. They get the following Error code - caa70004. If we set Teams to run with Compatibility mode then Teams works while the proxy is running.

**Comment by Rouanvdw** [comment]
Could it be that because UDP traffic is not supported by TWP it does not get handled by the proxy and if fails? I know Teams uses UDP

**Comment by honfika** [comment]
HTTP 1.x and /2 is using TCP. So is Teams is usnig UDP, it is probably not HTTP. (HTTP/3 is not is still draft as far as I know)

**Comment by Rouanvdw** [comment]
@honfika Is there a way for the proxy to ignore UDP traffic? and just pass it along. I doubt it but maybe you know of a way.

**Comment by honfika** [comment]
TWP is ignoring all UDP traffic.

**Comment by Rouanvdw** [comment]
@honfika So if windows would send UDP data to TWP then it would just be ignored and thus the UDP traffic will now work correctly. I have tested this using wireshark. Running without the proxy I can see alot of UDP traffic going through my adapter when using microsoft teams. But when the proxy is running the UDP traffic stops and Microsoft teams stops working. 

Does TWP support tls 1.3?

**Comment by honfika** [comment]
This is not how the network works.

Windows is not sending UDP packages to applications. They are sent to ports (TCP or UDP)

An application can listen on a port. TWP is not listening on any UDP port.

So if somebody is sending an UDP packet to a port, and no application is listening on that port, that package will be lost.

I don't think that your problem is related to any UDP communicaation.

**Comment by honfika** [comment]
Tls can be supproted by your .NET, but you hace to use that framework which suppoorts it. (for example .NET 5.0) just set it in ProxyServer.SupportedSslProtocols.

**Comment by Rouanvdw** [comment]
I solved the issue by add the following to the proxy exclusion list.  *.microsoftonline.com;*.microsoftonline-p.com
