### ISSUE TITLE
Capture traffic from applications

### ISSUE THREAD

**Issue by TheExeQ** [justcoding121/Titanium-Web-Proxy#837]
My program works fine to capture traffic via my browser aswell as Chromium Embedded applications. But other apps do not get captured. Is there a way to capture the other programs aswell? and if so what do i have to do to be able to do so?

**Comment by TheExeQ** [comment]
I used fiddler to what could be missing, and the thing i could think of is the user-agent if that is important? Most of the traffix has mozilla user-agent but some uses its own user-agent. (Im still new to how this all works so if what i said makes no sense im sorry XD)

**Comment by delebash** [comment]
Did you figure out the problem? I am having the same issue.
