### ISSUE TITLE
 SSL_ERROR_SESSION_KEY_GEN_FAILURE

### ISSUE THREAD

**Issue by SoundGoddess** [justcoding121/Titanium-Web-Proxy#86]
I'm trying to run the Examples.Basic with Firefox Developer 49.  Regular HTTP seems to work fine.  Unfortunately I can't seem to browse to any SSL sites, I get that error.  makecert.exe is copying to the right place.

![screenshot](http://metasmug.com/i/1467108784_firefox.png)

**Comment by justcoding121** [comment]
This is because FireFox have its own certificate infrastructure, and it don't respect windows store.
Try exporting your root certificate using certmgr.msc and then import that to FireFox.
