### ISSUE TITLE
Allow explicitly setting a PAC file for determining upstream proxy

### ISSUE THREAD

**Issue by mirgil** [justcoding121/Titanium-Web-Proxy#884]
There is an option to use upstream proxy, it’s done by setting _ForwardToUpstreamGateway_ to true.
When its set, windows proxy configuration is used - there is no option to implicitly set a proxy script. 
Sometimes, its required to set a proxy script which is different than the one set in the system.
Another scenario is that the proxy runs a service, under the system account. In this case, the system proxy is not available to the proxy and there is no way to set it.

**Comment by honfika** [comment]
I close this since the PR was merged.
