### ISSUE TITLE
Issue Related to Certificate

### ISSUE THREAD

**Issue by maruashok** [justcoding121/Titanium-Web-Proxy#89]
Hello Bro.,
When i start proxy it ask to install certificate and till here everything works fine but after that nothing happens.

my problem is after installing certificate my C# Windows Form Application shows nothing..

if i restart it after installing certificate everything works fine.means on first run it asks and install certificate but nothing happens with my application.

please check it and whether this is issue or i am missing something.
sorry for bad English but i hope you get my problem.

**Comment by justcoding121** [comment]
I can't reproduce this issue.

I deleted my root certificate from my machine and started the proxy. It asked me to install the certificate and as soon as clicked yes it worked as expected.

If you don't want to pop up, you should have your own root certificate and install it to the machine. After than you can specify the name of your root certificate and its issuer name manually during proxy initialization.

**Comment by maruashok** [comment]
Ok Get It..
Thanks for reply
