### ISSUE TITLE
root certificate path

### ISSUE THREAD

**Issue by zhaoyanliang8** [justcoding121/Titanium-Web-Proxy#895]
### Discussed in https://github.com/justcoding121/titanium-web-proxy/discussions/894

<div type='discussions-op-text'>

<sup>Originally posted by **zhaoyanliang2** December 27, 2021</sup>
`Assembly.GetEntryAssembly().Location` returns an empty string in a single file application.

https://github.com/justcoding121/titanium-web-proxy/blob/2825191dc8734108072e5f6af98b4a9ce3554492/src/Titanium.Web.Proxy/Certificates/Cache/DefaultCertificateDiskCache.cs#L129
https://docs.microsoft.com/en-us/dotnet/core/deploying/single-file</div>

**Comment by honfika** [comment]
Using AppContext.BaseDirectory in this case.
