### ISSUE TITLE
Is it necessary to install certificate via Titanium Web Proxy..??

### ISSUE THREAD

**Issue by maruashok** [justcoding121/Titanium-Web-Proxy#97]
I create my certificate with makecert and than install it to Trusted Root Certificate.
Suppose its name is "XYX Ltd" and pass this name to ProxyServer.RootCertificateIssuerName = "XYX Ltd";
and ProxyServer.RootCertificateName =  "XYX Ltd"; (In my case both Name & Issuer Name is same),

But when i start Titanium Web Proxy it asks me to install certificate..!

so my doubt is above specified options are used install certificate with custom name or it tells Titanium Web Proxy to use specified certificate (i.e XYZ Ltd)..??

if case is second one than why Titanium Installs certificate with same name (in my case i  already install certificate before starting Proxy)

Please help what should i do.??

**Comment by justcoding121** [comment]
No. If you specified the correct issuer name and root certificate name it wouldn't prompt to install.

You should have your certificate in current user trusted certificate store.

If you step in to the code in below line you will get an idea on what's wrong.
https://github.com/justcoding121/Titanium-Web-Proxy/blob/master/Titanium.Web.Proxy/ProxyServer.cs#L269

**Comment by maruashok** [comment]
Thanks Bro..!!
Instead of Current User I Install it to Local Machine.
Now its working perfect.
Again Thanks for reply.
